### ISSUE TITLE
Saturday not recognized as weekend day at diffInWeekendDays function

### ISSUE THREAD

**Issue by pflirae** [briannesbitt/Carbon#1007]
Environment:

PHP: 7.1
Carbon: 1.22.1

Case:

```php
$date1 = Carbon::createFromDate(2017, 9, 13); # (is Wednesday)
$date2 = Carbon::createFromDate(2017, 9, 16); # (is Saturday)
$date3 = Carbon::createFromDate(2017, 9, 17); # (is Sunday)

var_dump($date1->isWeekend()); # -> false
var_dump($date2->isWeekend()); # -> true
var_dump($date3->isWeekend()); # -> true

var_dump($date1->diffInWeekendDays($date2)); # -> 0 -> should be 1
var_dump($date1->diffInWeekendDays($date3)); # -> 1 -> should be 2
```

it looks like the diffIn...Days function do not consider Saturday as a weekend day. The same is observed when using diffInDaysFiltered.

Hope can be fixed in future update.

**Comment by Glavic** [comment]
I see that method `diffFiltered()` uses `DatePeriod` class, which ignores last date. Based on that, your results are correct, since from `13.9.17` until `15.9.17` (first `diffInWeekendDays()` call) there is no weekends, so results is. From `13.9.17` until `16.9.17` there is only 1 weekend (second `diffInWeekendDays()` call).

Too solve this issue, we would need to increase `$end` object for DateInterval `$ci`. Before this line https://github.com/briannesbitt/Carbon/blob/9545b4c962713b63c8877c628f71e8f2f816648e/src/Carbon/Carbon.php#L2703 we add `$end->add($ci);`. But.... that will break backward compatibility, and tests will fail....

@kylekatarnls & @briannesbitt : any thoughts?

**Comment by briannesbitt** [comment]
Its like give me a random number between 1 and 10.  Is 10 inclusive or exclusive ?

```
$start = new DateTime('2012-07-01');
$interval = new DateInterval('P1D');
$end = new DateTime('2012-07-7');

$period = new DatePeriod($start, $interval, $end);

foreach ($period as $date) {
    echo $date->format('Y-m-d')."\n";
}
```

Underlying DatePeriod in that example won't print the 2012-7-7 date.

Change the $end to `$end = new DateTime('2012-07-7 00:00:01');` and it will though  :-)  The time gets defaulted to 00:00:00 in the first example so there really isn't a "day" there.

I think we just augment the documentation to be clear but leave the implementation as is.

Can use `endOfDay()` or `addDay()` before the call so the end day is included.

**Comment by pflirae** [comment]
Ok, it is more clear with your example, and it makes sence to not touch the code. A little improvement on documentation will be great, so we can have a clearer expectatino on the result.

**Comment by kylekatarnls** [comment]
Hi, documentation lives on the gh-pages branch, you can propose an adding by editing `.src.html` files and submit pull-resuest.
