### ISSUE TITLE
Return morning, afternoon, evening or night

### ISSUE THREAD

**Issue by kheme** [briannesbitt/Carbon#1066]
I thought it would be a nice idea if Carbon could return morning, afternoon, evening or night, of a date

**Comment by Glavic** [comment]
Can u show us some examples of what you mean?

**Comment by kheme** [comment]
Considering 1 = Morning, 2 = Afternoon and 3 = Evening, an example could look something like this:
```
$dt = Carbon::parse('2017-2-2 00:00:00');
var_dump($dt->greeting); // returns 1, for morning, or simply returns "Good Morning"
```
Or
```
$dt = Carbon::parse('2017-2-2 12:02:00');
var_dump($dt->greeting); // returns 2, for afternoon, or simply returns "Good Afternoon"
```
Or
```
$dt = Carbon::parse('2017-2-2 17:00:00'); // or starting after 18:00 (6pm)
var_dump($dt->greeting); // returns 3, for evening, or simply returns "Good Evening"
```

Does Carbon need such??

**Comment by Glavic** [comment]
Interesting. Let's see what others have to say about this.

**Comment by kylekatarnls** [comment]
IMO, this should come in an extended class, or the macro/extension system if we do it.

Then, I would not change a public member, it should be a getter method.

This how you can deal with that with an extended class (or the `macro()` if you use laravel):

```php
// extend way
class MyCarbon extends Carbon
{
    public function greet() {
        $hour = $this->format('H');
        if ($hour < 12) {
            return 'Good morning';
        }
        if ($hour < 17) {
            return 'Good afternoon';
        }
        return 'Good evening';
    }
}

// macro way (with Laravel)
Carbon::macro('greet', function () {
    $hour = $this->format('H');
    if ($hour < 12) {
        return 'Good morning';
    }
    if ($hour < 17) {
        return 'Good afternoon';
    }
    return 'Good evening';
});
```

**Comment by simonschaufi** [comment]
Interesting but I'm not sure if culturally possible. I travel a lot and know from other countries that they use evening already when for me it is still afternoon. Is there any "universal" definition when evening / night starts?

**Comment by 36864** [comment]
This is all very subjective. Especially around DST changes, some people will look at the clock and start saying "good evening" and then look outside and change to "good afternoon" (or the other way around).

This may be a language thing, but I wouldn't say "good morning" to anyone I was meeting before dawn (as the stated example shows that anything from midnight to noon would be "good morning"). If this were to be implemented, you'd need to be able to define how many intervals there are, and be able to easily modify those intervals to adjust for changes to length of days.

**Comment by briannesbitt** [comment]
I think it would have to be based on the amount of daytime sunlight for that day.  In the summer we start saying good evening later in the day compared to the darker winter months.  Not to mention the translations ... oh boy ! Seems better suited for an extended class.

**Comment by magnosis** [comment]
@kylekatarnls any clue why I'm getting an "**Undefined method Carbon::macro()**" exception?
Using Laravel 5.5, I checked the source and Carbon does in fact use Macroable; so I'm really not sure what's that about...

**Comment by kylekatarnls** [comment]
Hi, first we're implementing macro natively (no longer need of Laravel Macroable) for the next version, do you use the "dev-master" version? else can you tell me your current Carbon version?

**Comment by J2TeamNNL** [comment]
Hi, I want to contribute some methods like check if morning so where should I code? @kylekatarnls 
Thanks

**Comment by kylekatarnls** [comment]
Hi, I still think it should better be a macro in your own application code.

First, because it's cultural, it's often until 12:00, but can be more or less in some places:
https://github.com/briannesbitt/Carbon/blob/2fd2c4a77d58a4e95234c8a61c5df1f157a91bf4/src/Carbon/Lang/tg.php#L80
https://github.com/briannesbitt/Carbon/blob/2fd2c4a77d58a4e95234c8a61c5df1f157a91bf4/src/Carbon/Lang/zh_Hant.php#L83

And what's the beginning? Technically 00:00 and then, the check can just be done with:

```php
if (Carbon::now()->hours < 12) {
    echo "It's the morning";
}
```
But then I think `->hours < 12` explicit check in code is clear enough and don't need a dedicated method.

Also I wouldn't say to someone "Good morning" at 00:00, it's midnight, so literally the middle of the night and unless we consider night and morning overlap, then, morning should start at sunrise. So even in a given culture we might have different opinions and, users/applications expecting different outputs for what is the morning. If a method is only hiding 1 line of code but you have to inspect it to be sure what it means, then it's not helping and you should likely type this line of code directly or have [your own macro like this](https://github.com/briannesbitt/Carbon/issues/1066#issuecomment-365232744).

Finally if we have `isMorning()` it would be unexpected not to have `isAfternoon()` and we'll have to deal with the same kind of ambiguities.
