### ISSUE TITLE
DST subSecond/addSecond yields unconsistend result

### ISSUE THREAD

**Issue by paslandau** [briannesbitt/Carbon#1236]
Hey,

I just ran into a weird bug when using subSecond / addSecond on a time object right at the daylight saving time switch in Europe/Berlin timezone.

```php
$c = Carbon::createFromFormat(
    $format = "Y-m-d H:i:s",
    $time = "2018-03-25 02:00:00",
    $timezone = "Europe/Berlin"
);

$c1 = clone $c;
$c1->subSecond();

$c2 = clone $c1;
$c2->addSecond();

echo "original  :". $c->toRfc3339String() . "\n";
echo "subSecond :". $c1->toRfc3339String() . "\n";
echo "addSecond :". $c2->toRfc3339String() . "\n";

```

yields

```
original  :2018-03-25T03:00:00+02:00
subSecond :2018-03-25T03:59:59+02:00
addSecond :2018-03-25T04:00:00+02:00
```

Subtracting and adding a second to the same datetime should not change the datetime ("original" should be the same as "addSecond" in the output above)

The underlying problem seems to be, that subSecond() return 
2018-03-25T0**3**:59:59+02:00 althought it should be 
2018-03-25T0**1**:59:59+02:00.

This seems to be a bug in the underlying \DateTime object as well:

```
        $c = \DateTime::createFromFormat(
            $format = "Y-m-d H:i:s",
            $time = "2018-03-25 02:00:00",
            $timezone = new \DateTimeZone("Europe/Berlin")
        );

        $c1 = clone $c;
        $c1->sub(new \DateInterval("PT1S"));
        $c2 = clone $c1;
        $c2->add(new \DateInterval("PT1S"));
```

Related issues might be #88 and #444 

It does not occur when a UTC is used as a timezone, hence I propose the following fix:

Override method "modify" in Carbon:

```php
    /**
     * @param string $value
     * @return static
     */
    public function modify($value)
    {
        $originalTz = $this->getTimezone();
        $this->setTimezone("UTC");
        parent::modify($value);
        $this->setTimezone($originalTz);

        return $this;
    }
```

Cheers
Pascal

**Comment by kylekatarnls** [comment]
Hi Pascal, the code you mention in Carbon is an old one that no longer exist. We change the way we handle DST now with addSeconds and addRealSeconds, please upgrade to the last version of Carbon and check the note about DST in the doc here: http://carbon.nesbot.com/docs/#api-difference

Thanks.

**Comment by paslandau** [comment]
Hey @kylekatarnls,

thx for the quick reply.

Using `addRealSeconds` / `subRealSeconds` seconds yields the expected result (thx for pointing me to the right direction).

Just to make sure:
`addSeconds` / `subSeconds` still relies on the faulty `modify` method (see
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L3160 / 
https://github.com/briannesbitt/Carbon/blob/1.25.0/src/Carbon/Carbon.php#L3160
)

Question: Does that mean that `addSeconds` should not be used anymore and that `addRealSeconds` is the correct replacement in every case? Still wondering, because the docs still mention `addSeconds` and do not mark them as deprecated?

Cheers
Pascal

**Comment by kylekatarnls** [comment]
Not at all, what you call a "bug" in this situation is an expected behavior in some other situations. `addSeconds` and `subSeconds` (and all hour/min/sec methods without "real") respect the native PHP DateTime behavior that make "jumps" at DST changes. This can help to deal with 23/25 hours days in macro features such as calendars. This way, when you add 24 hours in a DST day, it will not shift the date (you will not have to care about "is this a DST day in this timezone?"), PHP will add a day (of 23, 24 or 25 hours). And the same with `diffInHours()` and so, you get time ignoring DST.

When you want to deal by yourself with DST, `addReal*` and `diffinReal*` are the tools to use. This way, you always get real durations (considering moments passed in the real life), and you are on your own when adding 24 hours in a DST day by example (this can leads to +1/-1 hour at the clock since it's a DST day).

**Comment by paslandau** [comment]
Hey @kylekatarnls,
thx for taking the time to explain. Interesting perspective - I can see that this might lead to unexpected results when it comes to day changes.

Good to know that both solutions exist, depending on the situation.
