### ISSUE TITLE
startOfDay is off by microseconds

### ISSUE THREAD

**Issue by wdbaker54** [briannesbitt/Carbon#1258]
I am a neophyte using Carbon and mistakenly used startOfDay() instead of today() in a comparison with another Carbon instance that was using today(). I am not sure why they are not synonymous? Here is an
example from within Laravel's artisan tinker:

`>>> use \Carbon\Carbon
>>> $today = (new Carbon())->today()
=> Carbon\Carbon @1524034800 {#1128
     date: 2018-04-18 00:00:00.0 America/Los_Angeles (-07:00),
   }
>>> $startOfDay = (new Carbon())->startOfDay()
=> Carbon\Carbon @1524034800 {#1134
     date: 2018-04-18 00:00:00.204816 America/Los_Angeles (-07:00),
   }
`

As you can see, the startOfDay() returns an instance that is microseconds different than today() so $today->eq($startOfDay) does not return true.

I am using the current stable version of Carbon (1.26.4) with php 7.0.29

**Comment by kylekatarnls** [comment]
Duplicate #1231 #1209 and it's a PHP 7.0 known bug we already documented:
https://carbon.nesbot.com/docs/#note-about-microseconds

Also note that by doing new Carbon() then change the date, you call 2 methods, it's faster to do:
`Carbon::today()`

And last thing startOfDay and today are synonymous only it the source date is already today.
- today is `->modify('today')` of native PHP DateTime
- startOfDay is `->modify('00:00:00.000000')` of native PHP DateTime
It's different, and in PHP 7.1 and 7.2, it gives the right time for both (00:00:00.000000) but in PHP 7.0, microseconds are immutable so it will always be the initial one and if you do `new Carbon()` (same as `Carbon::now()`) you will get the current microseconds, this does not happen if you use `Carbon::today()` instead of a new instance.
