### ISSUE TITLE
336 Days in a Year

### ISSUE THREAD

**Issue by npars** [briannesbitt/Carbon#1353]
`‌‌CarbonInterval::year(1)->totalDays` produces a result of 336. This result can also be seen in [this test case](https://github.com/briannesbitt/Carbon/blob/master/tests/CarbonInterval/TotalTest.php#L27).

What is the reasoning behind this? If it's on purpose I feel like the reasoning should probably be documented somewhere (and mentioned in the user facing docs). Otherwise the result should probably be updated to be 365 to match the number of days in a [common year](https://simple.wikipedia.org/wiki/Common_year).

**Comment by imbrish** [comment]
Hey! The weird result comes from the fact that when calculating totals we cascade units behind the scenes. The calculation is linear and to calculate days we progress from years through months and weeks.

Because of that we could not be accurate in all the cases and some assumptions have been made: 1 year is 12 months, 1 month is 4 weeks, 1 week is 7 days. Thus the result: `1 * 12 * 4 * 7 = 336` as in the linked test case. This is actually mentioned in the docs, albeit indirectly - search for "cascade".

To get accurate 365 days per year we would need to assume that 1 month is `365 / 12 / 7 ≈ 4.345` weeks. Which would be a controversial default knowing that all DateInterval units are stored as integers, thus we settled on 4. Note that when using accurate factor, 30 days would not cascade to 1 month, because a month would be equal to approximately 30.415 days and 31 days would convert to 1 month but cause more than half of a day to vanish, because of decimal 0.685 days being cut off.

**Comment by imbrish** [comment]
That was the original reasoning. However now, that pre-processing of cascade factors and `getFactor` method have been implemented, it could be possible to allow various more precise factors for different units, for example 1 year being equal to 12 months, but also 365 days.

On the downside the algorithm to choose right factors won't be trivial. Think about 1 month being equal to 4 weeks but as well 30 days, while internally weeks are completely virtual. It would mean that 1 month is both 28 days and 30 days. Not sure if it's worth it.

@Glavic @kylekatarnls what do you think?

**Comment by npars** [comment]
Here is another gotcha with the current implementation:
```
> ‌‌Carbon::parse('2018-01-01')->diffAsCarbonInterval(Carbon::parse('2019-01-01'))->totalDays;
‌336
```

**Comment by npars** [comment]
Perhaps it's time to spin off another class for dealing with "real" time, maybe something similar to Python's [`timedelta`](https://github.com/python/cpython/blob/master/Lib/datetime.py#L453). I think trying to overload DateInterval (which is kind of like Python's [`relativedelta`](http://dateutil.readthedocs.io/en/stable/relativedelta.html)) is just going to lead to more and more of these surprises to developers using the library.

**Comment by kylekatarnls** [comment]
This is definitely not how to count days bteween dates. Use  simply `diffInDays` method.

An interval is never real time, it's only a duration in différents units, and you can set any custom factors you want to sum/cascade. If it does not fit, then do not use total/cascade at all, because it's not a way to get precise duration between instants. The date interval has no start or en, so if I tell you 1 day, it can be 24 hours (often), but not always, on DST change, it can be 23 or 25 hours, on a leap second year last day it's 24 hours + 1 second. Then with month and year, it's even more unpredictable.

Any decision breaks an other features. By example, you can disable month/week cascade to directly jump to the year and take 365 days or whatever you want:
```php
CarbonInterval::setCascadeFactors(array(
    'minute' => array(60, 'seconds'),
    'hour' => array(60, 'minutes'),
    'day' => array(24, 'hours'),
    'year' => array(365, 'days'),
));
```

The timedelta library you mention has no bigger unit than day so of course no problem with week/month/year.

And a delta of dates is not a problem neither, if you have either the start date or the end and an interval, you can do any precise calculation. But the CarbonInterval (and DateInterval) is not that, its purpose is to represent an abstract duration stored as separated units. cascade/total are just helpers for some work time logging, and quick converters, like `CarbonInterval::hours(5)->totalSeconds` to be added to some cookie expiration, timestamp or those kind of things.

**Comment by npars** [comment]
Created a PR to update the docs: https://github.com/briannesbitt/Carbon/pull/1355

**Comment by kylekatarnls** [comment]
Thanks! Much appreciated.
