### ISSUE TITLE
Human readable date minus human readable time returning inconsistent resulsts

### ISSUE THREAD

**Issue by OhKannaDuh** [briannesbitt/Carbon#1411]
Given date x (15 August 2018) and time y (2 days)
Creating a carbon object from x . " - " . y and calling toDateTimeString prints "2018-08-13 00:00:00" which is expected however if time y (2days 13 hours) calling toDateTimeString prings "2018-08-13 13:00:00" seemingly adding the hours rather than subtracting them.

**Comment by kylekatarnls** [comment]
Carbon is not responsible for the string parsing, this is the native behavior of PHP DateTime object, and we will not override it, because this is not the purpose of the library and the syntax is already well documented.

Please refer to http://php.net/manual/en/datetime.formats.php

You will see in the PHP documentation than there is no minus operator, in fact `-2` is an atomic symbol: the negative number. Also order in this string does not matter, so you get first the absolute value as start point: `15 August 2018`

Then you get:

| Unit | Count |
|--|--|
| day | -2 |
| hour | 13 |
