### ISSUE TITLE
Is the online PHP doc for v1 or v2?

### ISSUE THREAD

**Issue by mnapoli** [briannesbitt/Carbon#1421]
Hello,

I encountered an issue with the following code:
```php
CarbonInverval::make(...);
```
Carbon version: **1.25.0**
PHP version: **7.2**

I expected the `make()` method to be recognized by the IDE.

But actually the IDE did not recognize the method.

Since I found out about the `make()` method via the online documentation my question is:

**Is the online documentation for v2.0 (unreleased) or v1.x?**

**Comment by kylekatarnls** [comment]
`make` has been released on **1.28.0** so you won't have it with **1.25.0** and the documentation is for latest 1 (now **1.33.0**).

Version 2 documentation will soon be released and will bring version notes (you will have versions history for each method). I'm working on it: https://github.com/kylekatarnls/Carbon/tree/gh-pages-v2

**1.25.0** is a bit old now and so you will miss many things from the documentation, if you're locked on it because of using Laravel 5.6, I recommend you to use `"nesbot/carbon": "1.33.0 as 1.25.0"` in your **composer.json**. There is no incompatibility, Laravel only locked Carbon version for stability purpose.
