### ISSUE TITLE
Behavior of AddWeekDays on Saturday and Sunday

### ISSUE THREAD

**Issue by ssbrandsma** [briannesbitt/Carbon#1424]
Hello,

I encountered an issue with the following code:
```php
require 'Carbon/Carbon.php';
use Carbon\Carbon;

$today = Carbon::today();
echo $today;
echo '<br />';
echo $today->isSaturday() === true ? "It's saturday" : "It's not saturday";
echo '<br />';
$today->AddWeekDays(0);
echo $today;
echo '<br />';
```
output

```php
2018-08-25 00:00:00
It's saturday
2018-08-27 00:00:00
```

I would expect that the date doesn't change when adding zero weekdays.

I expected to get:
```
2018-08-27 00:00:00
It's saturday
2018-08-27 00:00:00
```

But I actually get:
```
2018-08-25 00:00:00
It's saturday
2018-08-27 00:00:00
```

It seems it jumps to the first weekday before adding days. Is this intended behaviour of AddWeekDays ?

**Comment by kylekatarnls** [comment]
Hello,

Yes, it's expected behavior, if you could be on a week-end day after calling `addWeekDays` it could cause more problems. For consistency reason, week-end days are always skipped even for 0 value.

It's up to you to check if value = 0 before adding week-days if you want explicitly to do nothing in this case.
