### ISSUE TITLE
Converting DateTime

### ISSUE THREAD

**Issue by Smoke1987** [briannesbitt/Carbon#1426]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromFormat(DateTime::ISO8601, '2018-04-04 16:00:00');
```
Carbon version: ** * 1.22.1**
PHP version: ** 7.2.0RC2 **

I expected to get:
```
formatted date-time
```

But I actually get:
```
error... in this function $format argument have value "Y-m-d\\TH:i:sO" (double escaped)
```

Thanks!

**Comment by kylekatarnls** [comment]
Yes, because `'2018-04-04 16:00:00'` does not match `DateTime::ISO8601`, this format expect a date like `'2018-04-04T16:00:00Z'` with `T` between date and time and with a timezone (or `Z` for UTC).

For the date you have you can just do:
```php
echo Carbon::parse('2018-04-04 16:00:00');
```

**Comment by Smoke1987** [comment]
that is, do you want to say that both parameters are identical in structure to this function? then why this function, if it does not convert the date from one format to another?

**Comment by kylekatarnls** [comment]
`createFromFormat` is not at all a converter, it's a constructor, and it's inherited from `DateTime`.
As you can see in the doc of the original method (http://php.net/manual/en/datetime.createfromformat.php), the mandatory parameters are a format and a time that matches that format, then you get an instance. If you want to get a format again, you should call format, then:
```php
echo Carbon::createFromFormat($inputFormat, '2018-04-04 16:00:00')->format($outputFormat);
```
If you see a string, it's because you added `echo` so the object is casted to string by the default format.
