### ISSUE TITLE
diffInSeconds giving wrong result

### ISSUE THREAD

**Issue by flaushi** [briannesbitt/Carbon#1494]
Hello,
I am still on version 1.34 (can't update because of symfony/translation 4 dependency, I am using 3.4).

I encountered an issue with the following code:
```php
echo Carbon::createMidnightDate(2018,7,1)->startOfYear()->diffInSeconds(Carbon::createMidnightDate(2018,7,1))
                + Carbon::createMidnightDate(2018,7,1)->endOfYear()->diffInSeconds(Carbon::createMidnightDate(2018,7,1))

    -
                Carbon::create(2018,1,1)->endOfYear()->diffInSeconds( Carbon::createMidnightDate(2018,1,1),true);
```
Carbon version: 1.34
PHP version: 7.1

This code splits a year in two parts (at July 1st) and checks if the sum of seconds is tha same as the number of seconds in the year. 

The result is 86400 seconds, one day!!! In herokuapp, the difference is zero, I expect this bug was solved in V2 sometime.

Is there any chance for me to keep on using carbon, I cannot update to symfony 4.

Thanks in advance!

**Comment by kylekatarnls** [comment]
Hi,

You may be experiencing a DST bug (winter time versus summer time). That would explain why I get 0 with any version and why you do not get the bug with Herokuapp.

Can you try with the UTC timezone:
```php
echo Carbon::createMidnightDate(2018,7,1,'UTC')->startOfYear()->diffInSeconds(Carbon::createMidnightDate(2018,7,1,'UTC'))
  + Carbon::createMidnightDate(2018,7,1,'UTC')->endOfYear()->diffInSeconds(Carbon::createMidnightDate(2018,7,1,'UTC'))
  - Carbon::createMidnightDate(2018,1,1,'UTC')->endOfYear()->diffInSeconds( Carbon::createMidnightDate(2018,1,1,'UTC'),true);
```

**Comment by flaushi** [comment]
Wow, quick answer. Thanks!

Now I am getting an error:

```

InvalidArgumentException: Unexpected data found.
Data missing

/var/www/symfony/vendor/nesbot/carbon/src/Carbon/Carbon.php:909
/var/www/symfony/vendor/nesbot/carbon/src/Carbon/Carbon.php:729
```

Note, I have one whole day or error (86400 seconds)!

**Comment by kylekatarnls** [comment]
PHP native DateTime class has quit a ton of bugs with DST (that'w why you always should set UTC as the default timezone, do every operations with UTC dates, then only when you want to display dates to the user, convert them).

On of those bugs is that DST change is not handled the same way on beginning and end.

In your case the beginning of the year contains only the ending of winter hour, for this change no difference between a DST timezone (let say Europe/Paris) and UTC.

For the full year as there is a beginning and an end, PHP automatically cancel the difference, but for the end of the year, Europe/Paris gives you 15811199, and UTC 15897599, this is your 86400 gap. because the 23-hours day cause a bad rounding, PHP mix "days" a fixed property of DateInterval and "d" the flexible equivalent that should not be touched in this case as we compare midnight dates, see the following example in raw PHP:

```php
$date = new DateTime('2018-07-01 00:00:00', new DateTimeZone('Europe/Paris'));
var_dump($date->diff(new DateTime('2019-01-01 00:00:00', new DateTimeZone('Europe/Paris'))));
$date = new DateTime('2018-07-01 00:00:00', new DateTimeZone('UTC'));
var_dump($date->diff(new DateTime('2019-01-01 00:00:00', new DateTimeZone('UTC'))));
```

Output:
```
object(DateInterval)#7 (16) {
  ["y"]=>
  int(0)
  ["m"]=>
  int(6)
  ["d"]=>
  int(1)
  ["h"]=>
  int(0)
  ["i"]=>
  int(0)
  ["s"]=>
  int(0)
  ["f"]=>
  float(0)
  ["weekday"]=>
  int(0)
  ["weekday_behavior"]=>
  int(0)
  ["first_last_day_of"]=>
  int(0)
  ["invert"]=>
  int(0)
  ["days"]=>
  int(184)
  ["special_type"]=>
  int(0)
  ["special_amount"]=>
  int(0)
  ["have_weekday_relative"]=>
  int(0)
  ["have_special_relative"]=>
  int(0)
}
object(DateInterval)#4 (16) {
  ["y"]=>
  int(0)
  ["m"]=>
  int(6)
  ["d"]=>
  int(0)
  ["h"]=>
  int(0)
  ["i"]=>
  int(0)
  ["s"]=>
  int(0)
  ["f"]=>
  float(0)
  ["weekday"]=>
  int(0)
  ["weekday_behavior"]=>
  int(0)
  ["first_last_day_of"]=>
  int(0)
  ["invert"]=>
  int(0)
  ["days"]=>
  int(184)
  ["special_type"]=>
  int(0)
  ["special_amount"]=>
  int(0)
  ["have_weekday_relative"]=>
  int(0)
  ["have_special_relative"]=>
  int(0)
}
```
It should be the same interval produced or in the worst case 1 hour difference due to DST but as you can see, the Europe/Paris diff has a buggy `->d = 1` on its interval. And this happens the most simple PHP code to do so.

So to be short: always use UTC for operations in PHP (no matter you use Carbon or not).

**Comment by flaushi** [comment]
Hey, thanks for your great explanation! They should work on that!

Is there a switch to make Carbon use UTC by default? I mean without touching the system time zone.

**Comment by kylekatarnls** [comment]
On any PHP application boostrap I run:
```php
date_default_timezone_set('UTC');
```
This will apply UTC to DateTime and so Carbon inherit from it.

If you are a Laravel user, set **config/app.php** with `'timezone' => 'UTC',`.

**Comment by flaushi** [comment]
But this will affect the whole php system, right?
Logs will have wrong timestamps,...? 
Sorry for asking so "basic" questions, but it's the first time I am confronted with this problem.

**Comment by kylekatarnls** [comment]
UTC is also the good timezone to use for logs. For exemple DST, will make the hour 02:30 happen twice in the winter time beginning, If you set your server to Europe/Paris and have a log at 02:30 for such day, you will not now if this is 02:30 GMT+1 or 02:30 GMT+2 because both will happen the same day. If you set it to UTC, you will never have such ambiguity, then converting a date from UTC to GMT+X is just adding X, if you send your log file to someone he can convert it in any timezone without having to know where was the server. It allows you to switch your server location easily, have multiple server across the world all sharing UTC dates, etc.

You can even never convert UTC dates-time, then let a front-side library (such as moment.js) take care of converting it using the real timezone of the user, it also means the server no longer even needs to know the user timezone.

That's the way I work with my apps. I don't care where the app is deployed and how is configured the server, I force the UTC timezone in PHP, in the database, node.js or any other server language I use. Then if I need to format a date to display it to the user, I simply call `->tz($userTimeZone)` on the Carbon instance before the format call.

Then about timestamp, Wikipedia says `Unix time, the number of seconds since 00:00:00 UTC on January 1, 1970`, important word is *UTC*. It means only timestamps calculated based on UTC are right, so right now if you record timestamps using any timezone, your logs timestamps are wrongs. If you want your timestamps to be right, use UTC.

**Comment by flaushi** [comment]
Thanks man,
if we knew each other personally, I'd like to buy you a beer right now. Thanks for your help!
