### ISSUE TITLE
Possible wrong behaviour when not all units in result become negative while adding an inverted interval

### ISSUE THREAD

**Issue by Fitzi** [briannesbitt/Carbon#1537]
Hello,

I encountered an issue with the following code:
```php
$interval1 = CarbonInterval::hours(2)->minutes(30);
$interval2 = CarbonInterval::hours(5)->invert();
			
$interval3 = $interval1->add($interval2); // Note: adding ->cascade() leads to the same result
			
$this->assertEquals( 1, $interval3->invert ); // actually is 0
$this->assertEquals( 2.5, $interval3->total('hours')); // actually is -2.5 hours
```

Calculation:
2 hours | 30 minutes
\+ (- 5 hours | 0 minutes)
= -2 hours | +30 minutes  // minutes remain positive

Carbon version: 2.6.1
PHP version: 7.2.12

I expected to get:
A positive number of hours and an inverted flag set to 1.

But I actually get:
Negative hours and no inverted flag set.

The problem is, that in CarbonInterval::add it is checked if **all** units are zero or negative, which may not always be the case, like seen above.
I think it should be checked if the added interval is inverted and is bigger than the current interval, this will lead to an inverted result. The units itself should always be positive imho. I'm not sure about the implications though. 

Just for the post to be complete, the test where all units become negative, which is passing:

```php
$interval1 = CarbonInterval::hours(2)->minutes(30);
$interval2 = CarbonInterval::hours(5)->minutes(45)->invert();

$interval3 = $interval1->add($interval2);

$this->assertEquals( 1, $interval3->invert ); // passes
$this->assertEquals( 3.25, $interval3->total('hours')); // passes
```

Calculation:
2 hours | 30 minutes
\+ (- 5 hours | 45 minutes)
= -2 hours | -15 minutes // both units are negative

Thanks!

**Comment by kylekatarnls** [comment]
In fact this behavior is expected despite the semantic expectation.

What you need to understand is PHP handle each unit separately in DateInterval.

First `add` is a modifier (it modify the current instance and returns it), in your example `$interval3 === $interval1`, `$interval1` is just modified, no new interval are created.

The `add` method will negate the result if every unit is <= 0, but in your first example you get negative hour and positive minute. Remember PHP does not do any guessing about unit cascading, so at this point hours and minutes are just potatoes and carrots. So we will not guess neither what `->invert` should be if we have mixed signs. The fact is there is no constraints, the `minutes` property can be 59, 75, 19982, etc. so we cannot assume hours part is bigger than minutes part. I become even more complicated with variable units (day can be 23, 24 or 25 hours due to DST), months can be 28, 29, 30 or 31 days, years can be 365 or 366 days, etc.

So the right way to do unit is working with a base unit (in you example minute seems the most relevant but it can be second or even microseconds):

```php
$minutes1 = CarbonInterval::hours(2)->minutes(30)->total('minutes');
$minutes2 = -CarbonInterval::hours(5)->total('minutes');
$minutes3 = $minutes1 + $minutes2;

$interval3 = CarbonInterval::minutes(abs($minutes3));
if ($minutes3 < 0) {
    $interval3->invert();
}
$interval3->cascade();

// $interval3->invert = 1
// $interval3->total('hours') = 2.5
```

**Comment by Fitzi** [comment]
I do understand that DateInterval handles units separately, I just thought since the add method is not a native method it would work a bit smarter.

>[...] It becomes even more complicated with variable units [...]

Okay, I see the problems with it and why its hard to make the add method smarter.

But working in minutes is not really a good solution either, imho. I would still assume that at least calling cascade would bring the DateInterval to the expected values. Since cascade already handles overflowing units, I can't find any argument against handling negative units as well.

What are your thoughts on handling negative values in cascade?

**Comment by kylekatarnls** [comment]
It would be possible, if it does not break existing unit tests. If I remember, `cascade` simply ignore `invert` but I have to check.

**Comment by Fitzi** [comment]
Have you been able to check whether it would break unit tests yet?

**Comment by Fitzi** [comment]
Sounds great. Do you plan on adding it yourself or would you accept it as a pull request only?

**Comment by kylekatarnls** [comment]
Here is my plan for it:
https://github.com/briannesbitt/Carbon/pull/1540

Feel free to comment or submit an other proposal.
