### ISSUE TITLE
Using setTestNow with multiple timezones returns wrong time

### ISSUE THREAD

**Issue by RikSomers** [briannesbitt/Carbon#1542]
Hello,

I encountered an issue with the following code:
```php
$date = Carbon::create(2017, 2, 14, 12, 0, 0, 'Europe/Amsterdam');
Carbon::setTestNow($date);

$dateTimestring = $date->copy()->setTimezone('UTC')->format('Y-m-d H:i:s.v');

$date2 = Carbon::createFromFormat(str_replace('.v', '.u', 'Y-m-d H:i:s.u'), $dateTimestring);

var_dump($date, $date2);
```
[See example](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=%24date%20%3D%20Carbon%3A%3Acreate(2017%2C%202%2C%2014%2C%2012%2C%200%2C%200%2C%20%27Europe%2FAmsterdam%27)%3B%0ACarbon%3A%3AsetTestNow(%24date)%3B%0A%0A%24dateTimestring%20%3D%20%24date->copy()->setTimezone(%27UTC%27)->format(%27Y-m-d%20H%3Ai%3As.v%27)%3B%0A%0A%24date2%20%3D%20Carbon%3A%3AcreateFromFormat(str_replace(%27.v%27%2C%20%27.u%27%2C%20%27Y-m-d%20H%3Ai%3As.u%27)%2C%20%24dateTimestring)%3B%0A%0Avar_dump(%24date%2C%20%24date2)%3B#)

Carbon version: 1.36.1
PHP version: 7.1.11

I expected to get:
```
object(Carbon\Carbon)#2 (3) {
  ["date"]=>
  string(26) "2017-02-14 12:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(16) "Europe/Amsterdam"
}
object(Carbon\Carbon)#4 (3) {
  ["date"]=>
  string(26) "2017-02-14 11:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
```

But I actually get:
```
object(Carbon\Carbon)#4 (13) {
  // ...
  ["date"]=>
  string(26) "2017-02-14 12:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(16) "Europe/Amsterdam"
}
object(Carbon\Carbon)#3 (13) {
  // ...
  ["date"]=>
  string(26) "2017-02-14 11:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(16) "Europe/Amsterdam"
}
```

I believe this is due to how mocks in different timezones are handled since https://github.com/briannesbitt/Carbon/pull/1281 was merged.

In the project I'm working on, we are using Laravel with two seperate (external) databases we cannot change configuration for. One of them is configured to use `Europe/Amsterdam`, while the other is configured to use `UTC`.

Because we started the project on the first database, we have set the application's / servers configuration to use `Europe/Amsterdam` timezone. However, for the models that save to the other database, we use the following code:

```php
// Convert a DateTime to a storable string
    public function fromDateTime($value)
    {
        // From our Europe/Amsterdam timezone, convert it to UTC before saving
        return is_null($value) ? $value : parent::asDateTime($value)->setTimezone('UTC')->format('Y-m-d H:i:s.v');
    }

// Convert a stored string to a DateTime
    protected function asDateTime($value)
    {
        // From our UTC timezone, convert it to the timezone in our config
        $value = parent::asDateTime($value)->setTimezone(config('app.timezone'));
    }
```

As you can see, we transform our `Europe/Amsterdam` value to a `UTC` one. Then, when converting it back, we get a Carbon instance from the UTC value and transform it back to a `UTC` one.

This has worked in the past, both in production as in tests, however, since we updated to Laravel 5.7 (and therefore, a higher version of Carbon), we have seen tests fail. Tests that had worked previously will now report the returned date to be different.

As you can see in the expectations / results, when using `setTestNow`, the time gets set correctly, but the wrong timezone is used. It therefore reports back a different and wrong time. 

If you use the same code without using `setTestNow`, the correct timezones are used. So this will only fail when in a test scenario.

If you try the provided example on both version 1.25.0 and 1.35.0 on [See example](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=%24date%20%3D%20Carbon%3A%3Acreate(2017%2C%202%2C%2014%2C%2012%2C%200%2C%200%2C%20%27Europe%2FAmsterdam%27)%3B%0ACarbon%3A%3AsetTestNow(%24date)%3B%0A%0A%24dateTimestring%20%3D%20%24date->copy()->setTimezone(%27UTC%27)->format(%27Y-m-d%20H%3Ai%3As.v%27)%3B%0A%0A%24date2%20%3D%20Carbon%3A%3AcreateFromFormat(str_replace(%27.v%27%2C%20%27.u%27%2C%20%27Y-m-d%20H%3Ai%3As.u%27)%2C%20%24dateTimestring)%3B%0A%0Avar_dump(%24date%2C%20%24date2)%3B#), you will see the discrepency between versions.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

It is the expected behavior, #1281 is the right way to do it with a mocked "now" because there is no reason to take a date as reference without its timezone, when I say "today 00:00" in unit tests if now is a date in Amsterdam, then 00:00 should be midnight in Amsterdam, not midnight in UTC. Then when you create `$dateTimestring = $date->copy()->setTimezone('UTC')->format('Y-m-d H:i:s.v');` you just dump a string with date and time digits, and when you pass it to `createFromFormat`, there is nothing allowing Carbon to know you created this string from a UTC date, so assuming it has the same timezone as the mocked now is the right thing to do because it reflect more correctly what would happen with a *real now* instance.

Then what you consider as "right" in 1.25.0 is not. Here is an example of the non-sense of the previous behavior using other timezones:
```php
date_default_timezone_set('America/Toronto');

$date = Carbon::create(2017, 2, 14, 12, 0, 0, 'Europe/Amsterdam');
Carbon::setTestNow($date);

$dateTimestring = $date->copy()->setTimezone('Australia/Perth')->format('Y-m-d H:i:s');

echo Carbon::createFromFormat('Y-m-d H:i:s', $dateTimestring)->format('e');
```

It outputs: America/Toronto. It uses none of the timezones you used in your code, it's the PHP default timezone (often = the operating system timezone).

And this timezone can be anything as, as in your case, a server can move, can be split into clustering, etc. so the PHP default timezone should never be used, there is only one valid timezone to store dates and share them between systems: **UTC**. (For example in Laravel, the **config/app.php** should always have `'timezone' => 'UTC',`, there is no valid reason to use anything else here).

In your case I recommend first a migration to convert all the non-UTC dates you have in your databases, then you can work with consistent dates all in UTC.

Note: remember timezones conversion are not lossless: 28 oct 2018 02:30 in Amsterdam can be 2 different moments in UTC. DST is a sufficient reason to not use such timezones internally.

**Comment by RikSomers** [comment]
Migration to UTC for both databases is unfortunately not possible as both databases are used by other external applications that rely on the Europe/Amsterdam and UTC formats respectively to be in place, and would cause lots of problems if changed. This is the sole reason we use this workaround in the first place. So I disagree that there is no valid reason to use anything other than UTC. If there was no reason, there wouldn't be a config value to change in the first place. I do agree however that being able to use UTC would have solved most of the problems I'm currently having.

**Comment by kylekatarnls** [comment]
Why not using the third parameter of `createFromFormat`?
`Carbon::createFromFormat('Y-m-d H:i:s.u', $dateTimestring, 'UTC')`

This will explicitly say what is the timezone of the given string.

**Comment by RikSomers** [comment]
Yeah, That's what I ended up doing aswell. I copied the code from the Laravel ` toDateTime` function and changed the code to explicitly set the timezone to UTC. It might not be the prettiest of solutions, but it works for our use case.

Thanks!

**Comment by kylekatarnls** [comment]
Hi, night helped me to think:

In real life (not in unit tests), `Carbon::now()` will have the timezone specified with `date_default_timezone_set` (or with the Laravel setting). So you can't have what you wrote:

```php
date_default_timezone_set('UTC');
$date = Carbon::create(2017, 2, 14, 12, 0, 0, 'Europe/Amsterdam');
Carbon::setTestNow($date);
```

In real cases (supposing you don't change default timezone during runtime), then "now" will never returns an Amsterdam time if you set the default timezone on UTC. So to be relevant, your test should start with:

```php
date_default_timezone_set('UTC');
// Pick the equivalent hour in UTC
$date = Carbon::create(2017, 2, 14, 11, 0, 0, date_default_timezone_get()); // date_default_timezone_get is not even needed as it should be the default via DateTime constructor
Carbon::setTestNow($date);
```

Then, the problem is gone (same behavior with all Carbon versions) and you don't have to worry about divergent timezone between now and createFromFormat default timezone, as in production it won't happen.

PS: To not calculate manually the equivalent hour in UTC, you can use `->shiftTimezone('UTC')`, it set the timezone of a given Carbon object then shift the hour according to the timezone offset.
