### ISSUE TITLE
diffForHumans() incompatible between PHP 7.1 and 7.2 

### ISSUE THREAD

**Issue by mheki** [briannesbitt/Carbon#1544]
Hello,

I encountered an issue with the following code:
```php
$deadline = Carbon::instance(new DateTime('+2 days'));
echo (new Carbon())->diffForHumans($deadline, true);
```
Carbon version: **1.36.1**
PHP version: **PHP7.2**

I expected to get:
```
2 days
```

But I actually get:
```
1 day
```

This code worked fine on PHP7.1 but when I updated to 7.2 I have to add an extra 1 second to make it work: `new DateTime('+2 days 1 second')` works as expected.
It looks like there is incompatibility between these 2 PHP versions.
Thanks!

**Comment by kylekatarnls** [comment]
PHP DateTime API has logic changes between versions (minor version and even patches) we try our best to provide a consistent behavior between many versions (https://travis-ci.org/briannesbitt/Carbon) but we avoid as often as possible to hack the native behavior, then what you expect is only approximately right  because:

```php
$deadline = Carbon::instance(new DateTime('+2 days')); // Let assume now is 12:00:00.000000
echo (new Carbon())->diffForHumans($deadline, true); // It's not instant so now is here 12:00:00.123456 (a few more microseconds than the previous new DateTime())
```

So the difference is 2 days less a few microseconds (time elapsed between the 2 lines).

Before, you would benefit of a random approximation giving you ~99.9% of the time 2 days, and ~0.1% 1 day. Now with the *better* precision you always get 1 day.

Adding 1 second could not be enough if you have a server freeze/overload that would make more than 1 second elapsed. So the right thing to do is to take a time as reference for the calculation:

```php
$now = Carbon::now();
$deadline = $now->copy()->addDays(2); // ->addDays(2) is equivalent to ->modify('+2 days')
echo $now->diffForHumans($deadline, true); // Here you get an exact result as $now is a common datetime
```

I know this behavior could seem les easy to handle but as it's more strict it will lead to less potential bugs in the end and will give you the same result on every PHP versions.

**Comment by mheki** [comment]
Thanks for explanation, using `addDays(2)` seems to be better approach than adding 2 days and 1 second 👍

**Comment by mheki** [comment]
Hmmm actually `(new Carbon())->addDays(2)` fails with php7.2 as well 🤔

**Comment by kylekatarnls** [comment]
No read the whole explanation, the solution is not `addDays`, the solution is using a common `$now` reference.

**Comment by kylekatarnls** [comment]
https://try-carbon.herokuapp.com/?input=%24now%20%3D%20Carbon%3A%3Anow()%3B%0D%0A%24deadline%20%3D%20%24now-%3Ecopy()-%3EaddDays(2)%3B%0D%0Aecho%20%24now-%3EdiffForHumans(%24deadline%2C%20true)%3B%0D%0Aecho%20%22%5Cn%22%20.%20PHP_VERSION%3B

**Comment by mheki** [comment]
you're right, it works as expected. Cheers 👍
