### ISSUE TITLE
wrong week number for 2018-12-31

### ISSUE THREAD

**Issue by sumanbhola** [briannesbitt/Carbon#1560]
Hello,

I encountered an issue with the weeks code:

 $date_ft = Carbon::parse( "2018-12-31" );

               echo $date_ft->weekOfYear;

it gives 1st week of 2019

thanks

**Comment by kylekatarnls** [comment]
Hello,
According to the ISO norm, 2018-12-31 belongs to the 1st week of 2019:
https://en.wikipedia.org/wiki/ISO_week_date

Most people on the planet use this norm.

It's the expected behavior. You can customize the calculation, for example if you want weeks starting on monday and first week of the year to be at least 7 days (full):

```php
echo Carbon::parse('2018-12-31')->week(null, Carbon::MONDAY, 7);
```

So this way, the last day of a year can never be 1.
