### ISSUE TITLE
How to get the correct year

### ISSUE THREAD

**Issue by kondonator** [briannesbitt/Carbon#1562]
Hello,

I got the output with the following code:
```php
Carbon::parse('2018-12-31')->format('Y-\WW');
```
Carbon version: **1.36.1**
PHP version: **7.1.19**

I expected to get:
```
"2019-W01"
```
or
```
"2018-W53"
```
But I actually get:
```
"2018-W01"
```

Please advise me how to specify the format code to get the result that I expect?

Thanks in advance!

**Comment by kylekatarnls** [comment]
Hello,

According to the ISO norm, 2018-12-31 belongs to the 1st week of 2019:
https://en.wikipedia.org/wiki/ISO_week_date

It's the expected behavior (`format` is the native method from `DateTime` PHP class, so `W` is the exact result of the norm). You can customize the calculation, for example if you want weeks starting on monday and first week of the year to be at least 7 days (full) in only one year:

```php
echo Carbon::parse('2018-12-31')->week(null, Carbon::MONDAY, 7);
```

So this way, the last day of a year can never be 1.

Related to #1560

Please precise the formula you expect.

**Comment by albertborsos** [comment]
FYI: http://php.net/manual/fr/datetime.format.php#123447
