### ISSUE TITLE
utcOffset(0) should set the timezone to UTC or +00:00

### ISSUE THREAD

**Issue by wangchj** [briannesbitt/Carbon#1564]
The following assertion fails

```php
public function testUtcOffset() {
    $carbon = Carbon::createFromTimestampUTC(0)->utcOffset(0);
    $this->assertSame(1970, $carbon->year);
}
```

```
Test  tests/unit/dependencies/CarbonTest.php:testUtcOffset
Failed asserting that 1969 is identical to 1970.
```

Carbon version: 2.9.1
PHP version: 7.1.16

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

The right way to do this is:

```php
$carbon = Carbon::createFromTimestampUTC(0)->tz('UTC');
```

Depending on the DST (winter/summer time have different offsets in some timezones) of your default timezone, you can get a 1-hour shift.

I will check I'm not sure but I guess we faced here some of the DST weirdness of the native API.

**Comment by kylekatarnls** [comment]
The first thing we could do is not to change the timezone if the current offset matches the asked offset.

**Comment by wangchj** [comment]
I see. That's a bit counterintuitive because I want to explicitly set the minute offset. If I want Carbon to figure out the proper offset, couldn't I use `Carbon::tz()`?

**Comment by kylekatarnls** [comment]
As I said in my first answer, you should use: `$carbon = Carbon::createFromTimestampUTC(0)->tz('UTC');`

Can I ask why you wanted to modify the offset rather than the timezone?

**Comment by wangchj** [comment]
Our app stores events happened in the past and using offset precisely represent the point in time in the past. As you said, the offset of a timezone shifts depends on the time of the year. We want to know exactly which day an event happened.

**Comment by kylekatarnls** [comment]
The user's perspective can change (I can travel) but the event moment does not change, that's why moments should be saved in an agnostic way (UTC date-time) and the user timezone to use to display this date should be stored in a dedicated place (not with dates themselves but with users/contexts) it will also avoid duplicate data (saving a timezone/offset for 99+ dates related to a user, instead of 1 time for the user only).

We can imagine to fix timezone to get a more accurate offset but internally PHP will handle a timezone (not an offset) and so if you change the date and fall in a different DST time, the offset will be lost again.

So instead of working around PHP internal system. I recommend to store all dates in UTC, and set a named timezone on display, it's the right thing to do. Handling offset or saving dates in anything else than UTC is a weak pattern that always lead to issues as soon as the user travel. You may think you're on a particular case that would require to handle things differently, but believe me, you're more likely in this very common situation: wanting to store precise moments and display them to the user in its own timezone, and this situation does not require to modify/save offset for each date.

**Comment by kylekatarnls** [comment]
Here is our very recommended approach: https://carbon.nesbot.com/docs/#user-settings

**Comment by wangchj** [comment]
Hi Kyle, thank you for the recommendation.  We do store all dates in UTC and the offset of the event so that when the event is displayed back to the user, it will display the same date as when the event was made regardless of the current location of the user.

For example, the user created an event in London on `2018-01-01 23:00:00+00:00` and travels to Japan (+09:00). When we looks this particular event in Japan, he should still see that this event on `2018-01-01` not `2018-01-02`.

**Comment by wangchj** [comment]
I've tested release `2.10` and all my test cases are passing. Thank you so much for the quick fix @kylekatarnls!

For completeness, the following are my quick and dirty test cases:

```php
public function testUtcOffset() {
    $timestamp = 0;
    $offset = 0;
    $carbon = Carbon::createFromTimestampUTC($timestamp);
    $carbon->offset = $offset * 60;
    $this->assertSame(1970, $carbon->year);
    $this->assertSame(1, $carbon->month);
    $this->assertSame(1, $carbon->day);
    $this->assertSame(0, $carbon->hour);
    $this->assertSame(0, $carbon->minute);
    $this->assertSame(0, $carbon->second);
    $this->assertSame(0, $carbon->utcOffset());

    $timestamp = 0;
    $offset = 60;
    $carbon = Carbon::createFromTimestampUTC($timestamp);
    $carbon->offset = $offset * 60;
    $this->assertSame(1970, $carbon->year);
    $this->assertSame(1, $carbon->month);
    $this->assertSame(1, $carbon->day);
    $this->assertSame(0, $carbon->hour);
    $this->assertSame(0, $carbon->minute);
    $this->assertSame(0, $carbon->second);
    $this->assertSame(60, $carbon->utcOffset());

    $timestamp = 1546297200; //2018-12-31 23:00:00
    $offset = 120;
    $carbon = Carbon::createFromTimestampUTC($timestamp);
    $carbon->offset = $offset * 60;
    $this->assertSame(2019, $carbon->year);
    $this->assertSame(1, $carbon->month);
    $this->assertSame(1, $carbon->day);
    $this->assertSame(1, $carbon->hour);
    $this->assertSame(0, $carbon->minute);
    $this->assertSame(0, $carbon->second);
    $this->assertSame(120, $carbon->utcOffset());
}
```
