### ISSUE TITLE
Difference in months does not match months subtracted

### ISSUE THREAD

**Issue by garret-gunter** [briannesbitt/Carbon#1568]
Hello,

I encountered an issue with the following code:
```php
// Create date and subtract 6 months.
$a = new Carbon('2018-12-31');
$b = clone $a;
$b->subMonths(6);

// Display dates for clarity.
echo "Dates:" . PHP_EOL;
echo "\$a: $a" . PHP_EOL;
echo "\$b: $b" . PHP_EOL . PHP_EOL;

// Calculate difference in months.
echo "Check difference in months:" . PHP_EOL;
echo "Difference in months \$a to \$b is " . $b->diffInMonths($a) . PHP_EOL;
echo "Difference in months \$b to \$a is " . $a->diffInMonths($b) . PHP_EOL;
```
[try-carbon.herokuapp.com example](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=%24a%20%3D%20new%20Carbon(%272018-12-31%27)%3B%0A%24b%20%3D%20clone%20%24a%3B%0A%24b-%3EsubMonths(6)%3B%0A%0A%0Aecho%20%22Dates%3A%22%20.%20PHP_EOL%3B%0Aecho%20%22%5C%24a%3A%20%24a%22%20.%20PHP_EOL%3B%0Aecho%20%22%5C%24b%3A%20%24b%22%20.%20PHP_EOL%20.%20PHP_EOL%3B%0A%0A%0Aecho%20%22Check%20difference%20in%20months%3A%22%20.%20PHP_EOL%3B%0Aecho%20%22Difference%20in%20months%20%5C%24a%20to%20%5C%24b%20is%20%22%20.%20%24b-%3EdiffInMonths(%24a)%20.%20PHP_EOL%3B%0Aecho%20%22Difference%20in%20months%20%5C%24b%20to%20%5C%24a%20is%20%22%20.%20%24a-%3EdiffInMonths(%24b)%20.%20PHP_EOL%3B)

Carbon version: **2.8.0 and 1.36.2**
PHP version: **7.2.13**

I expected to get:

A difference matching the number of months I subtracted: 6.

```
Dates:
$a: 2018-12-31 00:00:00
$b: 2018-07-01 00:00:00

Check difference in months:
Difference in months $a to $b is 6
Difference in months $b to $a is 6
```

But I actually get:

A different number: 5.

```
Dates:
$a: 2018-12-31 00:00:00
$b: 2018-07-01 00:00:00

Check difference in months:
Difference in months $a to $b is 5
Difference in months $b to $a is 5
```

Thanks!

**Comment by garret-gunter** [comment]
After looking through more issues, this may be an issue with not using UTC.

**Comment by kylekatarnls** [comment]
Hello, using UTC is always a good idea (I compiled reasons here : https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164)

But it's not the problem you get here: you should use `subMonthsNoOverflow`, this way you will get 6 months as diff.

`subMonth` call the native method `modify` oh PHP DateTime, it will try to go to 2018-06-31, as this date does not exist, it go to the next valid date: 2018-07-01, there you get 5 months and 30 days of difference.

`subMonthsNoOverflow` will take the last day of month instead of the next valid date so 2018-06-30.

**Comment by garret-gunter** [comment]
I see.  That makes sense.  Thanks for answering.
