### ISSUE TITLE
Upcoming Hour 

### ISSUE THREAD

**Issue by dillingham** [briannesbitt/Carbon#1571]
In attempting to get the upcoming 7am timstamp

now()->tomorrow()->addHours(7)

This works up until midnight where tomorrow becomes the next day. 

Looking for a way to say now()->upcoming(‘7am’)

https://twitter.com/im_brian_d/status/1080639290500153344?s=21

**Comment by kylekatarnls** [comment]
You should better use the dedicated library to opening hours:
https://github.com/kylekatarnls/business-time

There, you can use `isOpen` and `nextOpen` to get a readable and intuitive code and mostly easy to configure day-by-day precisely.

**Comment by dillingham** [comment]
While that package looks create, was looking for a one liner and thought it might be useful to have a function like that, thanks anyways :)

**Comment by kylekatarnls** [comment]
Macro are here to turn your own business logic into a reusable method. Carbon is not responsible to handle specific business logic. We provide date/time tools to 

I'm sorry but your expectation is not clear (sounds different in your twitter link and your description, now between 7 and 20 is not "upcoming 7am"), please follow the issue pattern, with concrete examples and results.

7-20 is a specific (and easy) situation, many users would say "lunch break", week-ends, holidays, etc. that's why I made [cmixin/business-time](https://github.com/kylekatarnls/business-time) that can easily give you the upcoming 7am or now if open. So we have no reason to implement this in Carbon as it's already in cmixin/business-time that handle that precise role while Carbon doesn't.

**Comment by dillingham** [comment]
No Im not looking for handling of between 7-20. between() handles that nicely.

Im saying carbon could assess and realize the next 7am timestamp or next Monday, or next month

Similar to nextClose & nextOpen in your package except that currently:

- at 11:59 `now()->tomorrow()->hour(7)` is tomorrow at 7am
- at 12:00 `now()->tomorrow()->hour(7)` is two days from now at 7am in essence 

Would be awesome if:

- at 11:59 `now()->nextHour('7')` is tomorrow 7am
- at 12:00 `now()->nextHour('7')` is tomorrow at 7am

**Comment by kylekatarnls** [comment]
Hi, that is exactly what Carbon outputs yet:
https://try-carbon.herokuapp.com/?input=echo%20Carbon%3A%3Aparse(%272018-01-01%2011%3A59%27)-%3Etomorrow()-%3Ehour(7)%20.%20%22%5Cn%22%3B%0Aecho%20Carbon%3A%3Aparse(%272018-01-01%2012%3A00%27)-%3Etomorrow()-%3Ehour(7)%20.%20%22%5Cn%22%3B

I get tomorrow 7am no matter what time is for now.

Please provide a reproductible code chunk giving the result you describe and using the raw Carbon library `now()` is a Laravel function we do not handle, It aliases `Carbon::now()` by default.

**Comment by kylekatarnls** [comment]
OK, just understood. We have a semantic problem here, midnight is not 12:00, it's 00:00, it's already the next day, so `tomorrow()->hour(7)` is perfectly right, it's not tow days from now, it's 1 day from now.

And it's one line of code:
```php
(Carbon::now()->hour < 7 ? Carbon::now() : Carbon::tomorrow())->hour(7)
```

So you can easily do your own macro:
```php
Carbon::macro('nextHour', function ($hour) {
  $date = isset($this) ? $this : Carbon::now();

  return ($date->hour < 7 ? $date : $date->tomorrow())->hour(7)
});

Carbon::nextHour(7); // static way
now()->nextHour(7); // on a given Carbon instance

**Comment by dillingham** [comment]
@kylekatarnls thank you! Much appreciated. Sorry for the confusion 😅
