### ISSUE TITLE
IDE warning: duplicate definition in CarbonInterface

### ISSUE THREAD

**Issue by successgdc** [briannesbitt/Carbon#1573]
Hello,

I encountered an issue with the following code:

```php
Carbon::now()->year();
```

My PHPStorm auto-completion does not work well, and when I dig into the `CartonInterface.php` file, the IDE claims that:

> Another definition with the same name exists in this file.

Carbon version: **v2.5**
PHP version: **v7.1.23**

The list:

- [ ] isUtc
- [ ] shortAbsoluteDiffForHumans
- [ ] longAbsoluteDiffForHumans
- [ ] shortRelativeDiffForHumans
- [ ] longRelativeDiffForHumans
- [ ] shortRelativeToNowDiffForHumans
- [ ] shortRelativeToOtherDiffForHumans
- [ ] longRelativeToOtherDiffForHumans

Thanks!

**Comment by kylekatarnls** [comment]
Thanks.

About xxDiffForHumans methods, the problem is that you can swap parameters:
```php
shortAbsoluteDiffForHumans(\DateTimeInterface $other = null, int $parts = 1)
shortAbsoluteDiffForHumans(int $parts = 1, \DateTimeInterface $other = null)
```

So you get 2 definitions, but it would be very less precise to write: `shortAbsoluteDiffForHumans(int|\DateTimeInterface $partsOrOther1 = null, int|\DateTimeInterface $partsOrOther2 = null)`, we lose the meaning, it allows 2 int or 2 dates, then we lose the `= 1` default value.

So I did not want to do this and I have o better solution to write multiple method prototypes without making PHPStorm cry.

About `isUtc`, it because of the alias `isUTC`. As PHP is now case-sensitive, it should be detected as 2 different methods, so it's more likely a bug of the analyser.

If you have any idea to improve this, feel free to comment.

**Comment by kylekatarnls** [comment]
Those documentation will be replaced by comments in the method descriptions:
`(Both isUtc and isUTC cases are valid.)`
`($other and $parts parameters can be swapped.)`
