### ISSUE TITLE
Logical issue for day after month

### ISSUE THREAD

**Issue by ayman-elmalah** [briannesbitt/Carbon#1589]
Hello,

I encountered an issue with the following code:
```php
    echo $day1 = \Carbon\Carbon::create('2019', '1', '28', 0, 0, 0)->addMonths(1) . "\n";

    echo $day2 = \Carbon\Carbon::create('2019', '1', '29', 0, 0, 0)->addMonths(1) . "\n";
    
    echo $day3 = \Carbon\Carbon::create('2019', '1', '30', 0, 0, 0)->addMonths(1) . "\n";
    
    echo $day4 = \Carbon\Carbon::create('2019', '1', '31', 0, 0, 0)->addMonths(1) . "\n";
    
    echo $day5 = \Carbon\Carbon::create('2019', '2', '1', 0, 0, 0)->addMonths(1);
```
Carbon version: **2.11**
PHP version: **7.3**

I have subscription system, with feb month that's 28 day, when i need the day after month at 31-1 it give me 3-3
but the day after 31-1 that's 1-2 and i need also the day after month it give me 1-3
If user subscribe at 31-1 he will get 2 days more than the user that will subscribe at 1-2

Thanks!
![121212124242523542](https://user-images.githubusercontent.com/22693197/52718982-55646000-2fad-11e9-8fc8-3d5cdd3f3daa.PNG)

**Comment by kylekatarnls** [comment]
Some informations we ask in our issue template are missing, to get support please ensure to give at least:

- [ ] the output you expect for the given code chunk.

Thanks.

**Comment by ayman-elmalah** [comment]
I just sent an issue, i have no idea what is the expect output,

**Comment by kylekatarnls** [comment]
The behavior you describe is the expected behavior for `addMonths` (normal overflow as when you do `(new DateTime())->modify('+1 month')` in raw PHP), with `addMonthsNoOverflow` you prevent overflow on next month. There is no bug because we obviously cannot return the date `2019-02-31`.

We provide tools to handle dates. We cannot guess your business subscription rules. `addMonths` add months, we're not responsible to decide when ends a subscription in your application. You may need a macro/function to return the end of a subscription from a start date and months count.

But if you don't specify the expected output of this macro. I can't do anything more.

**Comment by imbrish** [comment]
Hey @kylekatarnls how have you been? Great job keeping Carbon in shape! :)

Regarding the issue, it seems in fact illogical that `1-02 + 1 month` gives a date 2 days earlier than `31-01 + 1 month`. That is until you realize how it works. Adding 1 month doesn't mean adding 30 (or however many) days, but keeping days figure the same and adding 1 to the months figure. Which gives in the latter case `31-02` which is invalid and thus overflows to `3-03`.

Changing the behavior to anything else wouldn't make it any more logical, because our calendar is not very logical itself. It would also confuse everyone who knows the quirks of PHP's DateTime, with which Carbon's behavior is now consistent.

**Comment by kylekatarnls** [comment]
> Regarding the issue, it seems in fact illogical that `1-02 + 1 month` gives a date 2 days earlier than `31-01 + 1 month`

You can look at it differently. If you are in a 31-days month (January) add 1 month = add 31 days, if you're in a 28-days month (February), add 1 month = 28 days.

As I already mention here, you can simply prevent the overflow:

```php
echo $day4 = \Carbon\Carbon::create('2019', '1', '31', 0, 0, 0)->addMonthsNoOverflow(1) . "\n";
```

This obviously means you get the same end for 28, 29, 30 and 31 January. But the only alternative you would have for that would be to offer extra days giving always at least 31 days (can use `maximum` method for taht).

And as we already mention in other issues, you can also limit the overflow:
```php
$startDay = 31;

$day4 = \Carbon\Carbon::create('2019', '1', $startDay, 0, 0, 0)->addMonths(1);

if ($startDay !== $day4->day) {
  $day4 = $day4->startOfMonth();
}

echo $day4 . "\n";
```
