### ISSUE TITLE
[Translation tool] es_GT

### ISSUE THREAD

**Issue by JoseLoarca** [briannesbitt/Carbon#1612]
|English|es_GT|comments|
|--|--|--|
|2 years||2 años|
|2yrs||2 años|
|1 year||1 año|
|a year||un año|
|2 months||2 meses|
|2mos||2 meses|
|1 month||1 mes|
|a month||un mes|
|2 weeks||2 semanas|
|2w||2 semanas|
|1 week||1 semana|
|a week||una semana|
|2 days||2 días|
|2d||2 días|
|1 day||1 día|
|a day||un día|
|2 hours||2 horas|
|2h||2 horas|
|1 hour||1 hora|
|an hour||una hora|
|2 minutes||2 minutos|
|2m||2 minutos|
|1 minute||1 minuto|
|a minute||un minuto|
|2 seconds||2 segundos|
|2s||2 segundos|
|1 second||1 segundo|
|a few seconds||unos segundos|
|Monday||Lunes|
|Mon||Lun|
|Mo||Lu|
|Tuesday||Martes|
|Tue||Mar|
|Tu||Ma|
|Wednesday||Miércoles|
|Wed||Mié|
|We||Mi|
|Thursday||Jueves|
|Thu||Jue|
|Th||Ju|
|Friday||Viernes|
|Fri||Vie|
|Fr||Vi|
|Saturday||Sábado|
|Sat||Sáb|
|Sa||Sá|
|Sunday||Domingo|
|Sun||Dom|
|Su||Do|
|January||Enero|
|Jan||Ene|
|February||Febrero|
|Feb||Feb|
|March||Marzo|
|Mar||Mar|
|April||Abril|
|Apr||Abr|
|May||Mayo|
|May||May|
|June||Junio|
|Jun||Jun|
|July||Julio|
|Jul||Jul|
|August||Agosto|
|Aug||Ago|
|September||Septiembre|
|Sep||Sep|
|October||Octubre|
|Oct||Oct|
|November||Noviembre|
|Nov||Nov|
|December||Diciembre|
|Dec||Dic|
|2 hours ago||Hace 2 horas|
|2 hours from now||En 2 horas|
|2 hours before||2 horas antes|
|2 hours after||2 horas después|

**Comment by kylekatarnls** [comment]
Thanks a lot @JoseLoarca, es_GT is coming in next release.

We compiled it from glibc and rails-i18n. As it seems, it's es with only week definition different (Sunday as start instead of Monday in Spain and First week of year contains January 1st instead of January 4th).

Can you confirm this?

es base:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/es.php
es_GT (as planned for 2.14):
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/es_GT.php

Can you also confirm than months and day names does not start with an uppercase if they're not the first word of the sentence. For example "Monday" is uppercase because it's always `M` even in the middle on a sentence: `See you Monday` but French for "Monday" is "lundi" because by default the word is lowercase `Rendez-vous lundi`. ans so it should be `domingo` unless there is an exception for Guatemala.

**Comment by JoseLoarca** [comment]
Hi @kylekatarnls, I can confirm both observations.

>
> We compiled it from glibc and rails-i18n. As it seems, it's es with only week definition different (Sunday as start instead of Monday in Spain and First week of year contains January 1st instead of January 4th).
> 
> Can you confirm this?
> 

This is correct, **es_GT** is basically the same as **es**, just with different week definition.

>
>Can you also confirm than months and day names does not start with an uppercase if they're not the first word of the sentence.
>

This is also correct. In Spanish, months and day names start with an uppercase only if its the first word of a sentence or if its after a period. `Rendez-vous lundi` = `Nos vemos el lunes`, there's no exception for Guatemala.

**Comment by kylekatarnls** [comment]
[2.14.0 released](https://github.com/briannesbitt/Carbon/releases/tag/2.14.0)
