### ISSUE TITLE
[Translation tool] ru_RU

### ISSUE THREAD

**Issue by andrey-helldar** [briannesbitt/Carbon#1623]
|English|ru_RU|correct|comments|
|--|--|--|--|
|Jan|янв.|Янв|(no dot: no dot in the abbreviation)|
|Feb|февр.|Фев|(According to the rules of the Russian language, the word is reduced to three letters, not four),  (no dot: no dot in the abbreviation)|
|Apr|апр.|Апр|(no dot: no dot in the abbreviation)|
|Aug|авг.|Авг|(no dot: no dot in the abbreviation)|
|Sep|сент.|Сен|(no dot: no dot in the abbreviation)|
|Oct|окт.|Окт|(no dot: no dot in the abbreviation)|
|Nov|нояб.|Ноя|(According to the rules of the Russian language, the word is reduced to three letters, not four),  (no dot: no dot in the abbreviation)|
|Dec|дек.|Дек|(no dot: no dot in the abbreviation)|

**Comment by kylekatarnls** [comment]
glic has also 3-letters with no dot. So I consider this is correct. But it has lowercase, are you sure for the uppercase?

English has uppercase because months are always uppercase no matter there at the beginning of the sentence or not, but if months are lowercase in a normal context (in the middle of a sentence), we should keep it lowercase and user can use `ucfirst()` if it's a title, sentence start, etc.

**Comment by andrey-helldar** [comment]
26 фев 2019 - is correct
26 Фев 2019 - is correct
26 февр 2019 - is incorrect
26 фев. 2019 - is incorrect

Today is February 26, 2019:
Сегодня 26 февраля 2019 - is correct.
Сегодня 26 фев. 2019 - is incorrect.
Сегодня 26 февр. 2019 - is incorrect.

**Comment by kylekatarnls** [comment]
Thanks, so I will keep the lowercase.

**Comment by andrey-helldar** [comment]
@kylekatarnls, I updated the first post.
