### ISSUE TITLE
Docs suggest Carbon::serializeUsing and Carbon::setToStringFormat to migrate but those are deprecated

### ISSUE THREAD

**Issue by emiliopedrollo** [briannesbitt/Carbon#1659]
Hello,

I encountered an issue with the following code:
```php
Carbon::serializeUsing(function ($carbon) {  $carbon->format('Y-m-d H:i:sO'); });
Carbon::setToStringFormat('Y-m-d H:i:sO');
```
Carbon version: 2.16.0
PHP version: 7.2.11

I expected to get no warnings at all.
But I actually get a deprecated warning on both lines.

My problem is that I'm trying to update from a Laravel 5.7 installation to 5.8 that uses PostgreSQL as database and all our timestamps are with timezone thus the need for [correct serialization](https://laravel.com/docs/5.8/eloquent-serialization#date-serialization). Also the framework itself does such serialization in places where we do not have control so we cannot apply a transform beforehand.

Furthermore the [Carbon Documentation](https://carbon.nesbot.com/docs/#api-carbon-2) itself suggest to use such deprecated methods. 

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

Our deprecations are just a PHPDoc comment like this:
```php
/**
 * @deprecated
```

If they cause blocking warnings, it mean you have some nazi error handling. Deprecated method are safe to use has long as you don't upgrade to the next major version (and 3.0.0 is not started, it's not even sure we will actually develop it, and there is no risk Laravel upgrade for a next major version of Carbon during the 5.8 life).

That means, Laravel can call those methods and it's completely safe. Laravel will take care of the compatibility if we actually remove those methods.

We deprecated them because we plan to remove all global setters because they have side-effects (you change it for every usages in the application including some third-party libraries that may not expect this setting). So if you can use `->settings()`, it's a nice-to-have but optional.

Please check your error/exception handling (Monolog, HoneyBadger, etc.) are correctly configured, meaning, deprecation notices should be optionally logged in a file, in a bottom bar during dev, but they should be completely ignored in production and should certainly not block the execution in any environment.

Thanks,

**Comment by kylekatarnls** [comment]
Note about the doc: the given code allow to keep the old behavior. So it's a backward-compatibility trick.

For the JSON case in fact the right thing to do would be to keep the default toString and toJSON behavior, then change the format explicitly when you need it, And you should need it very rarely because the UTC ISO format provided by default is the standard way to exchange dates, and following this standard is a good practice. If you need to pass a timezone information you can do it in a separated field. But most often, a date is most helpful for the user if it's displayed in his own timezone and that would be the responsibility of the consumer of the API (the browser for example) to transform the UTC date-time string into a local Date object.

Here are some explanations about why you should use UTC:
https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164

**Comment by kylekatarnls** [comment]
Feel free to ask if you have any trouble and I will re-open the issue if needed.
