### ISSUE TITLE
[doc] subMonth, subDay, etc no longer accept parameter in PHPDoc but not mentioned in breaking change from Carbon 1 to 2

### ISSUE THREAD

**Issue by miklcct** [briannesbitt/Carbon#1662]
When my Carbon upgraded from 1 to 2 along with my Laravel, the `subDay(5)`, `subSecond(3)` etc calls show warning in my IDE because the PHPdoc shows it accept zero parameters, but in Carbon 1 it accepted a parameter.

Is this a breaking change or is the PHPDoc wrong?

**Comment by kylekatarnls** [comment]
Hello,

You still can do `subDay(5)` to subtract 5 days, but we recommend to use the plural form `subDays(5)` and singular only without parameters to implicitly subtract 1 day `subDay()`, this will help next developers working with your code (including you) to find them easily with no ambiguity.

So no, it's not a breaking change, and all the calls you have are safe. But when you find some of those warnings in your code, just add an `s` to grant the plural that matches the parameter.

**Comment by miklcct** [comment]
So why are there both `subDay()` and `subDays()` methods in this class? It seems so confusing by having methods of nearly-identical name which did identical things in the past (therefore I just picked either one from the IDE completion prompt), yet suddenly warning appears when the library was upgraded.

Can you deprecate one of these two methods so it is easier to use the API? The names `subDay()` and `subDays()` mean the same!

**Comment by kylekatarnls** [comment]
No it does not mean the same, `s` means plural.

And I will not add a deprecation because `subDay()` is not deprecated, but using `subDay()` with an argument is, because it's semantically incorrect.

The logical usage is:
```php
$date->subDay(); // Subtract 1 day
$date->subDays($x); // Subtract $x days
```

The easy warning muting is replacing all singular methods by the plural ones because they still have `1` as default value.

But if you want it clean, replace singular methods with argument by the plural methods.

This has changed in the 2.0.0 release, this is a major version, this is perfectly fair for a major release to introduce new best practices, the actual behavior did not even change (yous still can do `$date->subDay(7)`, it's just not recommended as grammatically incorrect, so the warning).

If those warnings bother you but you don't want to fix them, mute them from your IDE settings.
