### ISSUE TITLE
Czech LLL bug

### ISSUE THREAD

**Issue by waclaw66** [briannesbitt/Carbon#1663]
Hello,

there is a wrong mask within the Czech (cs.php) file...
`'LLL' => 'D. M. HH:mm'`
a year is missing, it should be...
`'LLL' => 'D. M. YYYY HH:mm'`

There are some other minor differences comparing to momentjs, but this one above is crucial.

Thanks for fix!

**Comment by kylekatarnls** [comment]
Will be fixed in the next release. We do not necessarily want perfect match with momentjs as long as equivalent features exist and the language is correct and understandable.

But if you see wrong output, please list them here, for exemple I'm not sure about the declensions of units with X nazpět, za X, X později, X předtím.

**Comment by waclaw66** [comment]
Thanks for fast fix again!
I have checked those and they sound good. Only `after` could be improved...
`'after' => 'o :time později',`
it's similar to Slovak language.

**Comment by kylekatarnls** [comment]
Thanks, changed for next version.
