### ISSUE TITLE
PDT and PST both are same

### ISSUE THREAD

**Issue by munir131** [briannesbitt/Carbon#1676]
Hello,

I encountered an issue with PST & PDT timezones:
```php
Carbon::now()->timezone('PST')
Carbon::now()->timezone('PDT')
```
Carbon version: 1.26.3
PHP version: 7.2

I expected to get:
```
Illuminate\Support\Carbon @1553694455 {#3004
     date: 2019-03-27 05:47:35.239112 -08:00,
   }
Illuminate\Support\Carbon @1553694455 {#3004
     date: 2019-03-27 06:47:35.239112 -07:00,
   }
```

But I actually get:
```
Illuminate\Support\Carbon @1553694455 {#3004
     date: 2019-03-27 05:47:35.239112 -08:00,
   }
Illuminate\Support\Carbon @1553694455 {#3004
     date: 2019-03-27 05:47:35.239112 -08:00,
   }
```

**Comment by kylekatarnls** [comment]
It relies on internal PHP timezone handling.

And PHP gives the same output:
```php
echo (new DateTime('now', new DateTimeZone('PDT')))->format('e O');
echo "\n";
echo (new DateTime('now', new DateTimeZone('PST')))->format('e O');
```

Outputs:
```
PDT -0800
PST -0800
```

I'm not sure why it's like this but it seems to be on purpose, maybe related to the warning here: https://www.timeanddate.com/time/zones/pst

> No locations currently on PST. Would you like to see PDT?
North America: PST is currently not observed because locations are on summer time / daylight saving time and are observing PDT.
>
> Please use the search field on the right to find the correct local time in any city.

If you're sure it's a bug, it should be reported to PHP itself.

It could be interesting to compare this to the behavior in some other languages/timezone handlers.

**Comment by munir131** [comment]
I compared with Moment (Like Carbon for JS) - https://momentjs.com/timezone/
```
var jun = moment("2014-06-01T12:00:00Z");
var dec = moment("2014-12-01T12:00:00Z");

jun.tz('America/Los_Angeles').format('ha z');  // 5am PDT
dec.tz('America/Los_Angeles').format('ha z');  // 4am PST
```

```
>>> Carbon::parse("2014-06-01T12:00:00Z")->timezone('America/Los_Angeles')
=> Illuminate\Support\Carbon @1401624000 {#2988
     date: 2014-06-01 05:00:00.0 America/Los_Angeles (-07:00),
   }
>>> Carbon::parse("2014-12-01T12:00:00Z")->timezone('America/Los_Angeles')
=> Illuminate\Support\Carbon @1417435200 {#2993
     date: 2014-12-01 04:00:00.0 America/Los_Angeles (-08:00),
   }
```
I think, I got the answer. We should use location on timezone. Closing it as it is working with location.
