### ISSUE TITLE
Diff in days excluding leap year?

### ISSUE THREAD

**Issue by josevavia** [briannesbitt/Carbon#1689]
Hello,

I want to know if it is possible to calculate diffInDays but excluding the additional days of leap years.

Today, `Carbon::parse('2019-03-03')->diffInDays(Carbon::parse('2020-03-03'))` returns 366. I wonder if there is an option or parameter to exclude this days. I am working on a system depending on apportionment and we want that all years "have" 365 days.

Thanks!

**Comment by kylekatarnls** [comment]
The easy way would be `diffInDaysFiltered`:
```php
echo Carbon::parse('2019-03-03')->diffInDaysFiltered(function (Carbon $date) {
  return $date->format('m-d') !== '02-29';
}, Carbon::parse('2020-03-03'));
```

Note that this is way slower than `diffInDays` because it will run the test of each day in a loop. If you have a long period, you would need a more performant way. Maybe finding all included "last day of February" for each year, then decrement your count for each of them that is a day 29 and included in the range.

**Comment by drewgallagher** [comment]
Could the implementer of `diffInDays` just add the condition for leap years, would that fix this?

**Comment by kylekatarnls** [comment]
Frankly why would it be the responsibility of the Carbon library to arbitrary exclude a given day? What about an option to exclude May 4th?

February 29th is a day, 2028-02-29 will happen and last 24 hours, 2025-02-28 won't. `diffInDays` count the days that actually happen between 2 dates. That's clearly what is expected to happen 99% of the cases.

If February 29th is special to your business, it's an edge-case to handle explicitly, you can detect if it's in a given interval (using `->between()`) then you do whatever you want with this information.

We will not add option to fake the calendar and even less make it the default behavior.

**Comment by drewgallagher** [comment]
Because users of the library depend on functions like `diffInDays` to work in all scenarios. So if leap years are not covered, that is an edge case that all users of the library will have to write custom code for. Custom code may result in bugs in individual systems. If the library handled it, then everyone could benefit and the library would be covering more edge cases, which it should do.

**Comment by kylekatarnls** [comment]
> if leap years are not covered

That's the point, they are covered and they are covered the right way, i.e. counting the days that actually exists not faking it.

That's definitely not a bug nor the library fault if this day exist on the Gregorian calendar.

**Comment by kylekatarnls** [comment]
See pure PHP result:
```php
$feb28 = new \DateTimeImmutable('2024-02-28');
$march1 = new \DateTimeImmutable('2024-03-01');

var_dump($feb28->diff($march1)->days); // 2

$a = new \DateTimeImmutable('2019-03-03');
$b = new \DateTimeImmutable('2020-03-03');

var_dump($a->diff($b)->days); // 366
```

If the above feels wrong to you, open an issue on https://github.com/php/php-src

But me and thousands devs rely on this behavior, and changing it would definitely not be a fix but blow up businesses such as  shifting by 1 a yearly subscription date, make events of the 29th fall in the void and many other catastrophes would happen out of trying to make a day artificially disappear. So I wouldn't expect them to actually consider it.

**Comment by josevavia** [comment]
@kylekatarnls I completely understand your reasoning, and in fact when I opened this issue almost 5 years ago, it was simply a question about whether there was an option, not a bug request.

The point is that 5 years later, with dozens of applications implemented using Carbon, I am still missing something to be able to do an annual proration ignoring leap years.

The problem is that although it is a small percentage of users, it is something that is common in certain sectors. And Carbon is an incredibly efficient library with many functions and helpers. If with a single line I could tell Carbon to have this behavior in all its operations, it would be much better than implementing an ad-hoc solution in each particular place where I want to do calculations ignoring February 29.

It doesn't seem like such a strange request, take a look at the Google results for the search "date diff ignoring leap year". You will see multiple solutions in multiple languages, some more efficient than others.

If Carbon had an option to enable this (like `useMonthsOverflow`), just as efficient as the rest of its features, it would be great.

But again, I understand your reasoning :)

**Comment by drewgallagher** [comment]
If it's unit tested I'm sure the fix would be fine.

**Comment by kylekatarnls** [comment]
I'm out of ideas to rephrase it politely, this is not a bug, so there is no "fix", some want to calculate diff excluding Mondays, some would want to exclude a particular set of holidays. Those are all business cases, relevantly handled in specific packages. We won't add an option for each need and certainly change the default behavior, it's an obvious breaking change.

For instance you can already do that easily with https://github.com/kylekatarnls/business-time

> it is something that is common in certain sectors

Carbon is 12 years old, you're only 2 people ever asked for such a thing, which tends to show it's a very specific need, not common enough to justify being shipped globally.

> take a look at the Google results for the search "date diff ignoring leap year"

It's not because something exists and is vaguely related to date that Carbon should have a method/option for it. Each added thing is adding maintenance to the project and can create confusion to users about what they should use. It's part of the maintainer job not to let everything going in and filter out what is not fitting the scope of the library.

And it's not just a benefit for library, as application developers you should care about owning the code that is actually specific to your application, it's fine to delegate standard things to third-party libraries but it's not a good idea to want your own rules to lie in a black box, that's the kind of things that you'd benefit to be and in control of. If you are considering 2024 has 365 days, you're taking an unreal assertion, so devs in your team working on such system should be made aware of this specificity and it should be made super explicit in your code what are all the results for all the operation that you expect out of this assertion.

**Comment by josevavia** [comment]
Thanks @kylekatarnls for your response.

For me this was never a bug to be fixed!. As I said, I was only asking if is there an option to do this using the Library. There are no options to do this? It's ok for me, I will keep using Carbon and be happy with that.

Also I am aware of the complexity that something like this can add to maintenance and use, that's why I asked if the option already exists, but I didn't ask for it to be implemented ;)

**Comment by drewgallagher** [comment]
How many applications use a calendar with leap years being considered? I'm guessing anything that is used at least in the US which has leap years included in the calendar. That is a lot of applications not able to use something very simple that could be added to the library. And it makes code not work on those days during a leap year. Unit tests can fail with date discrepancies and code can fail. I don't believe this is difficult to implement.

**Comment by kylekatarnls** [comment]
Are you trolling? 🤔

**Comment by josevavia** [comment]
@drewgallagher I think @kylekatarnls has given enough reasons to not implement this.

Also I strongly disagree that this is something simple to implement, you can see the first answer to this issue 5 years ago and its performance implications.

**Comment by drewgallagher** [comment]
We implemented our own function yesterday within an hour and tested it. I don't think it's that difficult to implement. 

We can agree to disagree. 

`    /**
     * numberDaysBetweenDates: Number of days between two dates
     *
     * If the from date is greater than the to date the result will be negative
     * Else if the from date is less than the to date the result will be positive
     * Else if the from date is equal to the to date the result will be 0
     *
     * @param string from
     * @param string to
     * @return int - number of days
     */

    public static function numberDaysBetweenDates(string $from, string $to)
    {
        $from_date_obj = date_create($from);
        $to_date_obj = date_create($to);
        // %r%a returns the difference in days with the sign (+ or -) and we cast it to a number
        return (int)date_diff($from_date_obj, $to_date_obj)->format("%r%a");
    }`

**Comment by kylekatarnls** [comment]
> I don't think it's that difficult to implement.

I never say it's difficult, I said it's not the library responsibility and I gave a solution 5 years ago: https://github.com/briannesbitt/Carbon/issues/1689#issuecomment-480157281 🤷

**Comment by drewgallagher** [comment]
Why not just put the solution I just pasted into the diffInDays function? I feel like that would be pretty simple. You can just adjust it to use Carbon instances.

**Comment by kylekatarnls** [comment]
What is the case where `diffInDays` is giving different result than your function `numberDaysBetweenDates`?

**Comment by drewgallagher** [comment]
It's when the argument to the diff in days function is a date that is in a leap year in February. It returns a 1 day difference. But if you flip the arguments it works.

**Comment by drewgallagher** [comment]
date_diff supports leap years, diffInDays does not

**Comment by kylekatarnls** [comment]
I'm sorry but `diffInDays` actually supports leap years:
```php
var_dump(Carbon::parse('2024-02-28')->diffInDays('2024-03-01'));
var_dump(Carbon::parse('2024-03-01')->diffInDays('2024-02-28'));
```
It gives 2 and -2, which is the expected behavior for February 29th leap day to actually be supported. And `->format("%r%a")`  gives the same result.

**Comment by drewgallagher** [comment]
Yesterday when I ran this in our app using Carbon version `^2.53.1` it would return 1 day difference instead of 2 for one of the combinations of argument calls. However I tried running this on this php sandbox and it works with Carbon v3. I wonder if it's version specific. https://play.phpsandbox.io/embed/nesbot/carbon 

```
    $currentDate = new Carbon('2024-02-28');
    echo $currentDate;
    echo "\n";
    $marchDate = new Carbon('2024-03-01');
    echo $marchDate;
    echo "\n";
    echo $currentDate->diffInDays($marchDate);
    echo "\n";
    echo $marchDate->diffInDays($currentDate);
```

**Comment by drewgallagher** [comment]
Maybe it's php version specific? I am not sure at this point. It seems like some applications have the issue but others do not.

**Comment by drewgallagher** [comment]
Not sure if this is something different, but it says that CarbonIntervals don't support leap years. 
<img width="1792" alt="Screenshot 2024-02-29 at 12 09 31 PM" src="https://github.com/briannesbitt/Carbon/assets/131900008/a2916068-dcfc-4e74-8519-ede9f7e3f231">
