### ISSUE TITLE
Creator::createFromFormat() should not throw Exceptions (like the native function)

### ISSUE THREAD

**Issue by pflueg** [briannesbitt/Carbon#1693]
Hi!

I have an issue regarding the function ```Carbon\Traits\Creator::createFromFormat();```.

The function is overwriting the native function ```DateTime::createFromFormat();``` and is actually changing the behaviour of it. The native function **does not** throw any Exceptions but simply returns ```false``` if any problem occurs (like an invalid format).

The function in the Creator-Trait is throwing the Exception ```InvalidArgumentException``` through ```rawCreateFromFormat()```.

Behaviour of Carbon:
```
php > \Carbon\Carbon::createFromFormat('aaaa', 'bbbb');
PHP Warning:  Uncaught InvalidArgumentException: Trailing data in /home/[.....]/Carbon/src/Carbon/Traits/Creator.php:537
Stack trace:
#0 /home/[.....]/Carbon/src/Carbon/Traits/Creator.php(559): Carbon\Carbon::rawCreateFromFormat('aaaa', 'bbbb', NULL)
#1 php shell code(1): Carbon\Carbon::createFromFormat('aaaa', 'bbbb')
#2 {main}
  thrown in /home/[.....]/Carbon/src/Carbon/Traits/Creator.php on line 537
PHP Stack trace:
PHP   1. {main}() php shell code:0
```

Expected behaviour:
```
php > var_dump(\DateTime::createFromFormat('aaaa', 'bbbb'));
php shell code:1:
bool(false)
php > 
```

Is there any known reason for this? Any functions that overwrite native PHP functions must behave exactly the same.

Thanks!

**Comment by kylekatarnls** [comment]
From the documentation:

> createFromFormat() is mostly a wrapper for the base php function DateTime::createFromFormat. The difference being again the $tz argument can be a DateTimeZone instance or a string timezone value. Also, if there are errors with the format this function will call the DateTime::getLastErrors() method and then throw a InvalidArgumentException with the errors as the message.

It's what we call strict mode:

```php
Carbon::useStrictMode(false);
```

Can disable this behavior. But we discourage to do so as muting creation errors with invalid inputs is very unsafe. Throwing an error when you pass invalid input is a much better approach.

Example:

```php
Carbon::createFromFormat('aaaa', 'bbbb')->year;
```
Wihout strict mode: You'll get "Year on boolean error" > unclear
With strict mode: Trailing data in bbbb > you get the root cause

The principle here is as simple as: "do not continue driving with a flat tire".

Note than you also can check that a string has an expected format with `hasFormat('1975-05-01', 'Y-m-d')`.
