### ISSUE TITLE
Annoying API reference side panel in documentation

### ISSUE THREAD

**Issue by bjornarhagen** [briannesbitt/Carbon#1695]
Hey, I just wanted to point out some weird behavior with the documentation.

If I double click to select text inside the code examples, a fullscreen popup shows up after a couple of seconds, and it's incredibly slow to close.

See video: https://streamable.com/xti70

This is quite annoying. Could this be improved/removed? A button to turn it on/off would be nice.

**Comment by kylekatarnls** [comment]
Hi,

You have a window size too narrow to display both documentation and API reference side by side. You could cheat it by zoom out (Ctrl + `-` in most browsers). This will emulate a higher resolution and so it will no longer be full-screen on your device.

The documentation is on the `gh-pages` if you want to propose some toggle-button to enable/disable the opening on double-click on a method name.

**Comment by kylekatarnls** [comment]
Now, you need one more click to open the API reference, so you can now:
- double click without the side panel to open automatically
- then you can choose when a method is available on different classes Carbon::add / CarbonInterval::add or Carbon::toString / CarbonPeriod::toString

**Comment by ralphjesy12** [comment]
Yes. Page performance has been compromised. A bit laggy when I search/skim thru the documentation. I prefer the old doc. or if we can improve the page in terms of performance. or like @bjornarhagen suggested, a turn off button. This is for both the API Side Panel and the Live Editor.

**Comment by kylekatarnls** [comment]
Hi @ralphjesy12 I tried to remove the API reference pannel, and it does not solve the laggy scroll. This will not help. And what asked @bjornarhagen was to not open the pannel on double-click, this has been done, that's why this issue is closed.

Then live editors are now lazy-loaded, the live editor is only loaded on click on them.

From one hand the page became too big to still being a one page documentation.

From an other hand, the laggy scroll disappear if we remove all code `<pre>` they could be to heavy to render it might be a twisted analyse, because removing them all make the page way smaller.

So API Side Panel and the Live Editor as laggy scroll are not the root cause.

The documentation is open-source too (branch gh-pages, and see https://carbon.nesbot.com/contribute/docs/) you may propose a pull-request if you think you can improve the performances.

**Comment by ralphjesy12** [comment]
Okay, @kylekatarnls . Will have a look at it. As of now, i think it has something to do with the scroll event and `scrollCheck()` function. This executes around 70+ times every scroll event.

**Comment by kylekatarnls** [comment]
I just try to void it with running `scrollCheck = function () {};` it's almost the same. But indeed there is scroll detection and we may debounce it.

**Comment by kylekatarnls** [comment]
Scroll events have been denounced it should make it smoother.
