### ISSUE TITLE
[Translation] Greek

### ISSUE THREAD

**Issue by LegendProjects** [briannesbitt/Carbon#1718]
Hey, i noticed that Carbon is using el for Greek Lang instead of gr, Laravel is using gr for set the locale Lang, is possible the carbon to make both ways to work for Greek Lang? el and gr, because with el i can't put in Laravel when i'm setting the locale to gr to use the function:

        $locale = App::getLocale();

        CarbonInterval::setLocale($locale);

I have to write instead this check:

        if ($locale == 'gr') {
            $locale = 'el';
        }

before set the locale.

So far i noticed this in Greek translations, i'm not sure if is happening to other languages too.

Thank you!

**Comment by kylekatarnls** [comment]
Hi,

We follow the ISO 639-1 standard:
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

Please note than languages have their own code lists and it differs from countries list:
https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

That mean: Greece country is GR, Greek language is EL. This matches locales you get from the browser so this would be very dangerous to change it. Right now you can safely take the locale from the browser and just pass it to Carbon as we use the same standard.

So in fact if you have `$locale` being `gr`, it probably means that you have a wrong input (non standard) or you take a country code and use it as language code (very dangerous too since there is languages spoken in different countries and countries with multiple languages).
