### ISSUE TITLE
[Translation tool] ar

### ISSUE THREAD

**Issue by atefBB** [briannesbitt/Carbon#1723]
|English|ar|comments|
|--|--|--|
|2 hours from now|ساعتين من الآن|ساعتين بدءا من الآن|

Should I convert this issue to a PR?

**Comment by kylekatarnls** [comment]
Hi @atefBB, "2 hours from now" is ساعتين من الآن in Google Translate and `بدءا` is translated as "starting". This has not to be literally "from now", the meaning is similar to "in 2 hours", it should be the most common way to speak about a date in the future.

Is `بدءا` really needed and is it something specific to `من الآن`?

**Comment by atefBB** [comment]
Hi @kylekatarnls, it's seem more clear to me with `بدءا`, google translate is just an automated tool and I notice many mistakes in arabic translation.

**Comment by kylekatarnls** [comment]
No I'm not, but yes it will be reviewed by arabic native speakers.

My question was: is it for all units ("from now" related) or for "hours" only?

Language accuracy comes first, but when there are equivalent forms available, I try to keep it short (so it can be displayed in small places) and pragmatic (better if it can be the same form for all units rather than handling special cases). And change it after understanding what exactly is the before/after situation to avoid reverting later and so prevent words to change too often when developers update Carbon.

**Comment by atefBB** [comment]
If I understood you, the form `بدءا من` not related only to `hours` ! You can say `دقيقتين بدءا من الآن` `Two minutes from now` !

**Comment by kylekatarnls** [comment]
I asked to an arabic colleague, he explained:

> Google translation is correct:
>
>    - ساعتين من الأن
>
> Second form ساعتين بدءًا من الأن  is also correct.
>
> Both are word-by-word translations correct and understandable.
>
> I would add a third: في ظرف ساعتين
>
> Hour as a variable:
>
> Number of hours | Arabe | Anglais
> -- | -- | --
> 1 | في ظرف ساعة | ساعة  بدءًا من الأن | ساعة من الأن | 1 hour from now
> 2 | في ظرف ساعتين | ساعتين بدءًا من الأن | ساعتين من الأن | 2 hour from now
> x>2 |   | ساعة  بدءًا من الأن x | ساعة من الأن x | X hours from now

Considering this, I would say the benefit do not worth the change and I would keep the current (and shorter) value.

**Comment by atefBB** [comment]
Thanks. I need to review this issue for more info !
