### ISSUE TITLE
Unexpected diffInSeconds/Microseconds output

### ISSUE THREAD

**Issue by jxlwqq** [briannesbitt/Carbon#1790]
Hello,

I encountered an issue with the following code:

```php
$d1 = Carbon::parse('2019-06-15 12:34:56.123456');
$d2 = Carbon::parse('2019-06-16 12:34:56.123455');

echo $d2->diffInSeconds($d1);
```

Carbon version: **2.20.0**

Laravel version: **5.8.28**

PHP version: **7.3.1**

I expected to get:

```
86399
```

But I actually get:

```
172799
```
(1 day added)

Thanks!

**Comment by kylekatarnls** [comment]
What we expect in the input code of the issue template is your code, not our code. And here we don't know what date is `$created_at` and what is `now()`

And expected and actual output should be results of Carbon methods you call so `diffInSeconds` mostly here because `->days` is a property of `DateInterval` we inherit.

Please re-write the code/expected/actual sections of your issue, so I can see your exact expectation at public API level.

**Comment by kylekatarnls** [comment]
I found a case a permit myself to update your issue accordingly.
