### ISSUE TITLE
[laravel 4.2] Carbon 1 is deprecated, see how to migrate to Carbon 2.

### ISSUE THREAD

**Issue by camry** [briannesbitt/Carbon#1813]
Laravel 4.2.22
PHP 7.0.33

```
composer update
```

Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run ".\vendor\bin\upgrade-carbon" to get help in updating carbon and other frameworks and libraries that depend on it.

I can't update Laravel , How can I solve it?

**Comment by kylekatarnls** [comment]
Upgrade PHP first. Laravel 5.8 and Carbon 2 both require PHP 7.1.

**Comment by camry** [comment]
> Upgrade PHP first. Laravel 5.8 and Carbon 2 both require PHP 7.1.

I can't upgrade PHP. How can I solve it?

**Comment by camry** [comment]
> Upgrade PHP first. Laravel 5.8 and Carbon 2 both require PHP 7.1.

Because the laravel 4.2 project has been online for a long time, it cannot be upgraded.

**Comment by kylekatarnls** [comment]
> Because the laravel 4.2 project has been online for a long time, it cannot be upgraded.
I don't get the point, Facebook live for 15 years, and I'm pretty sure they are no longer in PHP 5.2.

I would either encourage at least 7.2 as 7.1 is no longer actively supported:
https://www.php.net/supported-versions.php

And Laravel 4.2 is very old. It might be a difficult upgrade, but you would really benefit of tons of features and improvements from Laravel.

To be honest, right now, upgrading Carbon is the less of your problem since both PHP 7.0 and Laravel 4.2 no longer receive any support/bugfixes/security fixes and they are more sensitive to bugs/security than Carbon.

So if you can live with PHP 7.0 and Laravel 4.2, you probably don't care about running Carbon 1.
