### ISSUE TITLE
Use alternative numbers (Persian, Arabic) in translated duration strings

### ISSUE THREAD

**Issue by kylekatarnls** [briannesbitt/Carbon#1817]
Issue with codes like:
```php
echo CarbonInterval::years(2)->locale('fa')->forHumans(['altNumbers' => true]);
```

Carbon version: **2.22.0-beta.1**

PHP version: **7.3**

Expected:

```
۲ سال
```

Current output:

```
2 سال
```

**Comment by danvim** [comment]
I do not know how this would be handled for Chinese. But this is a suggestion. The current: `2週` is fine for now. However, the numbering system of Chinese is different than Arabic Numbers and simple dictionary approach on converting Arabic Numbers to Chinese Numbers isn't possible.

Chinese Numbers is basically in this format: `digit + unit + digit + unit ... + digit`.

A google search yielded this PHP package: https://github.com/banqhsia/chinese-number

However, on top of that, when counting, the character `兩`(same for Traditional and Simplified Chinese) is used instead of `二`. So for `2週`, the correct translation would be `兩週`.
