### ISSUE TITLE
Using isToday() with timezones.

### ISSUE THREAD

**Issue by Livijn** [briannesbitt/Carbon#1821]
Hello,

I encountered an issue with the following code:
```php
$date = Carbon::parse('2019-07-30T23:59:59.000000Z')->setTimezone('UTC');
echo $date->isToday() . ' & ';
$date->timezone('Europe/Stockholm');
echo $date->isToday();
```

Carbon version: **2.21.3**

PHP version: **7.3**

I expected to get:

```
1 & 0
```

But I actually get:

```
1 & 1
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

It's as expected. When you execute `$date->timezone('Europe/Stockholm')` you are asking for the same moment in an other timezone. So you get a date containing `2019-07-31 01:59:59 Europe/Stockholm` and you posted this message at 2019-07-31 00:43 (Stockholm), it's today for you.

Maybe you're just working too late and did not expect the 30th would be over. :)

Else you also can shift the timezone, this way you get `2019-07-30 23:59:59 Europe/Stockholm` instead of `2019-07-31 01:59:59 Europe/Stockholm`:
```php
Carbon::setTestNow(Carbon::parse('2019-07-31 00:43', 'Europe/Stockholm'));

$date = Carbon::parse('2019-07-30T23:59:59.000000Z')->setTimezone('UTC');
$date->isToday(); // true
$date->shiftTimezone('Europe/Stockholm');
$date->isToday(); // false
```

Thanks.

**Comment by Livijn** [comment]
Thank you  @kylekatarnls 🤗
