### ISSUE TITLE
[Translation tool] pl

### ISSUE THREAD

**Issue by Qrzysio** [briannesbitt/Carbon#1822]
|English|pl|comments|
|--|--|--|
|2yrs|2l|2 l|
|2mos|2mies|2 mies.|
|2w|2tyg|2 tyg.|
|2d|2d|2 d|
|2h|2g|2 godz.|
|2m|2m|2 min.|
|2s|2s|2 sek.|
|Mon|pon|pon.|
|Mo|Pn|pon.|
|Tue|wt|wt.|
|Tu|Wt|wt.|
|Wed|śr|śr.|
|We|Śr|śr.|
|Thu|czw|czw.|
|Th|Cz|czw.|
|Fri|pt|pt.|
|Fr|Pt|pt.|
|Sat|sob|sob.|
|Sa|So|sob.|
|Sun|ndz|niedz.|
|Su|Nd|niedz.|

Fixed meanwhile by 2.22.0:

|English|pl|comments|
|--|--|--|
|a year|1 rok|rok|
|a month|1 miesiąc|miesiąc|
|a week|1 tydzień|tydzień|
|a day|1 dzień|dzień|
|an hour|1 godzina|godzina|
|a minute|1 minuta|minuta|

**Comment by kylekatarnls** [comment]
Hi @Qrzysio, thanks for your help. As 2.22.0 was released meanwhile the "a unit" translations are now fixed.

About short units we get the of @aso824 for this with the PR #1291. And so I would be glad to have his feedback on this proposal.

So question to @Qrzysio, @aso824 and Polish speakers, could you qualify those changes? Could you tell me for each (2g and 2 godz. for example) understandable/correct/commonly used?

**Comment by Qrzysio** [comment]
The main difference in my translation is we do not put "1" before the word if we speak about single stuff. So we skip the number when it's "1".
It is worth discussing the abbreviations "godz." etc. It will be much simpler if we present some specific examples with use.

**Comment by kylekatarnls** [comment]
> The main difference in my translation is we do not put "1" before the word if we speak about single stuff. So we skip the number when it's "1".

This is already fixed by the 2.22.0 release. When you filled the form, it will in beta so the fix was not yet available in the tool. But this point is assumed to be fixed, and my remaining question is only about abbreviation.

Here are some examples of probable uses of those translations:

For example we can use `echo CarbonInterval::fromString('2 days 5 hours 30 minutes')->forHumans(['short' => true]);` to get logged work:

```
Log work: 2d 5h 30m
```

And we can use very short days to display a calendar:
|Su|Mo|Tu|We|Th|Fr|Sa|
|-|-|-|-|-|-|-|
||||||1|2|
|3|4|5|6|7|8|9|
|10|11|12|13|14|15|16|
|17|18|19|20|21|22|23|
|24|25|26|27|28|||

Finally short days will be use in short dates:
```
Sat, Aug 3, 2019 3:21 PM
```

**Comment by aso824** [comment]
> Could you tell if those short and very short variants (2g and 2 godz. for example) are understandable/correct/commonly used?

Both is used. Little longer variant like `2 godz.` is used more frequently, but for very short form like `2h 30m`, we also use `2g 30m` or `2 godz. 30 min.`. 

I agree that my fix could be a little wrong, because translation of, for example, `2mos` should be `2 mies.` instead of `2mies` (as I added in previous PR).

**Comment by Qrzysio** [comment]
As @aso824 said:
1. The most common use is: `2 godz. 30 min.`.
2. Understandable for programmers, but less for the average user: `2g 30m` .

**Comment by kylekatarnls** [comment]
2.23.0 will be released with `2 godz. 30 min.`

Thanks for your help!
