### ISSUE TITLE
Add PHPStan extension for macros

### ISSUE THREAD

**Issue by spawnia** [briannesbitt/Carbon#1846]
I am trying to statically analyse my code with PhpStan and found no mechanism to discover Macros that are registered with Carbon.

```php
Carbon::macro('foo', function() {}));

$now = new Carbon();
$now->foo();
```

When running PhpStan on that code, i get an error message like this:

`'#Call to an undefined method Carbon\\Carbon::foo\(\).#'`

PhpStan allows configuring extension points that extend the analysis capabilities in such a way that Macros can be detected, for example https://github.com/nunomaduro/larastan/blob/master/src/Methods/Pipes/Macros.php

I can champion this feature. Are you willing to add it to Carbon?

**Comment by kylekatarnls** [comment]
Hi @spawnia, glad to see you back there. In https://carbon.nesbot.com/docs/#api-macro you may notice the link to: https://github.com/kylekatarnls/carbon-cli

With this, you can generate files that allows IDEs to find the methods on Carbon. It uses standard PHPDoc, so PHPStan is supposed to detect them. Please let me know if not.

If not, I have to mesure this feature. I would not have dedicated methods to maintain to support a particular analyzer. Then it would implies to support other analyzers after that.

**Comment by spawnia** [comment]
Hey, i tried the CLI - pretty cool!

I am not sure how i can get PHPStan to pick up the definitions in there while still preserving the definitions of the actual class. As far as i know, that is not possible.

A PhpStan extension does not require changes to the actual application code. You can check out https://github.com/BenSampo/laravel-enum/pull/56 as an example of how it can be added to a package.

**Comment by kylekatarnls** [comment]
> The developer experience is greatly enhanced by IDE definition files and static analysis. I think that supporting them should be a first-class concern of great open-source packages.

My point is: IDEs already handle macros using the CLI. PHPStorm read pretty well the generated files with standard PHPDoc. It's cool that PHPStan have an extension system. But it would be nice if they would allow us to specify a file to merge for definition. I will try to find if such way exist, else I might proposing something to them to handle that. I would prefer standard PHPDoc (other static analyzers may use too) rather than PHPStan-specific.

I would also avoid requesting the user to add settings if possible. This may be the solution to adopt but I would like some times to check the existing options.

Last thing: Carbon macros could be static, instantiated or both. As the PHPStan `isStatic` method should return a boolean, it may have trouble for the "both" case.

**Comment by kylekatarnls** [comment]
Hi @spawnia I started with an adding of Carbon in larastan: https://github.com/nunomaduro/larastan/pull/301

As it's change-free for Carbon (nothing to add on our side) and seems legit as larastan aims to provide PHPStan support for all stuffs Laravel provide and include.

I gave you the write access on my larastan fork if you want to help.

Of course it would still be great to support PHPStan with a dedicated integration since Carbon can be used anywhere outside of Laravel.

**Comment by kylekatarnls** [comment]
Asking for type class definitions support:
https://github.com/phpstan/phpstan/issues/2393

Considering to be phpstan/extension-installer compatible:
https://github.com/phpstan/extension-installer/issues/13

I'm still interested by a PHPStan support that would neither rely on Laravel nor on the carbon-cli if possible. It would be awesome to have it by default without extra installation step if you use both Carbon and PHPStan. And I would prefer that the classes needed to support it to not being the the `src` (to not being autoloaded in production environments).

@spawnia Are you still interested. Do you think it's possible?

**Comment by kylekatarnls** [comment]
Carbon is supported by [larastan v0.4.0](https://github.com/nunomaduro/larastan) and I recommend it to all Laravel users.

Carbon itself uses [phpmd](http://phpmd.org), [phpstan](http://phpstan.org) and [php-cs-fixer](https://cs.symfony.com) to detect code smells.

**Comment by kylekatarnls** [comment]
Hi @spawnia do you still want to take care of this? PHPStan extension can now be embedded directly inside the Carbon package thanks to https://github.com/phpstan/extension-installer/pull/16 and I'm still interested in providing PHPStan-compliance out of the box (without having to require larastan and simply to provide it to non-Laravel users).

**Comment by spawnia** [comment]
You paved the way towards enabling this change quite nicely, thank you.

Most of my time spent on Open Source goes towards Lighthouse, but i will see what i can do.
