### ISSUE TITLE
CarbonImmutable + Laravel, locale not used

### ISSUE THREAD

**Issue by OrestHk** [briannesbitt/Carbon#1851]
Hello,

We are using CarbonImmutable on a project with Laravel 5.8.32, we recently updated our Carbon version to 2.23.0 and the locale doesn't seem to be taken into account anymore, the fallback seems to be used. 
Playing with Carbon versions, it looks like it's working with 2.23.0-beta.2 but not since 2.23.0-beta.3
I encountered an issue with the following code:
```php
        $this->assertSame('fr', \App::getLocale());
        $this->assertSame('fr', \Carbon\Carbon::getLocale());
        $this->assertSame('fr', \Carbon\CarbonImmutable::getLocale());
```

Carbon version: 2.23.0

PHP version: 7.3.4

I expected to get:

```
true
true
true
```

But I actually get:

```
true
true
false
```

Sorry if i'm missing something.
Thanks!
Have a nice day !

**Comment by kylekatarnls** [comment]
Thanks a lot for this precise analyse. The version numbers will help a lot.

**Comment by kylekatarnls** [comment]
Previously Carbon and CarbonImmutable shared a translator cache. So locales was synchronized "by accident" because the Laravel service provider was supposed to change only the locale of the class used by default in Laravel.

After re-thinking none of the previous and current behavior are correct as you may want to use both Carbon and CarbonImmutable and more likely want both to be synchronized to the locale. And you can also set to an other class that can handle locale support or not. But even in this case, unless you explicitly disable the Carbon Laravel service (or its auto-discovery), it would be relevant to use the locale for Carbon/CarbonImmutable.

So I propose to change the service provider to update explicitly all classes:
https://github.com/briannesbitt/Carbon/pull/1852

Regarding the actual regression, this will be releases in a patch 2.23.1.

**Comment by kylekatarnls** [comment]
Patch 2.23.1 released.

**Comment by OrestHk** [comment]
That was fast, thanks à lot !
