### ISSUE TITLE
isToday() vs isCurrentDay()

### ISSUE THREAD

**Issue by garethnic** [briannesbitt/Carbon#1882]
I'm struggling to find out if there's a difference between isToday() and isCurrentDay().

Are there implementation differences between the two methods?

**Comment by kylekatarnls** [comment]
There are strictly equivalent, in fine, they will compare the date formatted as `'Y-m-d'` with now (in the same timezone).

`isToday()` is faster, because it does it in one line of code, while `isCurrentXyz` is a generic magic method (Xyz can be any unit) and so it will first map to the unit to get the right format for comparison.
