### ISSUE TITLE
Method not found in static

### ISSUE THREAD

**Issue by spaceemotion** [briannesbitt/Carbon#1914]
Hello,

I encountered an issue with the following code:

```php
Carbon::createFromFormat('d.m.Y', $date)->setTime(0, 0, 0);
```

Carbon version: 2.25.2

PHP version: 7.3.7

While the code executes just fine, I am getting the following error in PHPStorm:
![image](https://user-images.githubusercontent.com/429147/67163519-3efa7980-f370-11e9-903a-76474c1a9efb.png)

It looks like the PHPDoc blocks are incorrect as they state the following:

```php
/**
 * @method        static static createFromFormat(string $format, string $time, string|\DateTimeZone $timezone = null)
```

Which I guess indicates that the createFromFormat() returns a static instance (if that's even a thing). Changing it to return `CarbonInterface` instead seems to resolve this issue.

Thanks!

(I guess I could have made a PR, but I wanted to allow some discussion beforehand).

**Comment by kylekatarnls** [comment]
Hi,

First `static` (meaning `static::class`) is a valid return type, so first static stands for "the method is static", the second stands for Carbon/CarbonImmutable.

It's a pity but we have to use redundant typing so PHPStorm can understand them rather than the shortcuts.

We already made this move recently for dynamic methods, so it's fine to do the same for static methods.

This PHPDoc is auto-generated:
https://github.com/briannesbitt/Carbon/blob/master/phpdoc.php#L30

And the following yet allow to replace automatically `self` with Carbon, CarbonImmutable or CarbonInterface depending on the file:
https://github.com/briannesbitt/Carbon/blob/master/phpdoc.php#L459

Once `phpdoc.php` modified, it can be ran using `composer phpdoc`, if you feel you can do this improvement for the 3 static methods, please feel free to send a pull-request.

Thanks,

**Comment by kylekatarnls** [comment]
This will be reverted as this is no longer an issue in `PhpStorm 2022.3`.
