### ISSUE TITLE
->add('1 month') ignores monthOverflow

### ISSUE THREAD

**Issue by cosarara** [briannesbitt/Carbon#1926]
Hello,

I encountered an issue with the following code:
```php
$a = CarbonImmutable::create("2019-01-31");
$a->settings(['monthOverflow' => false]);
var_dump($a->add('1 month') == $a->addMonth()); // false
```

Carbon version: 2.25.3

PHP version: 7.3.11

I expected to get:

```
bool(true)
```

But I actually get:

```
bool(false)
```

While this might not be a bug, it is certainly a big gotcha and should be noted in the documentation.

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

`'monthOverflow'` change the behavior of `addMonths` and `subMonths` while `add()` call the native method `modify` of the native PHP `DateTime` class and can handle any interval including composite intervals. So we will more likely not be able to make `'monthOverflow'` work for add/sub.

**Comment by cosarara** [comment]
I see. Even if it can't be made to work, since it violates the principle of least astonishment, I think it deserves a warning in the docs.

**Comment by kylekatarnls** [comment]
I confirm we can't implement this as it would force us to parsing it instead of passing it to `DateTime` that pass it to `timelib` library. And it will make very unclear behavior when it comes to composite interval like: `1 month 6 weeks` but note that it's still fine with:

```php
$a->add(1, 'month')
```

So it's not about the `add` method, it's about using interval strings in add/sub/modify/change or any interval/interval string manipulation:

```php
$a->add(CarbonInterval::month())
```
It also ignores the `'monthOverflow'`

As for as DateInterval/CarbonInterval are concerned, we could split it and add year using yearOverflow, then month using monthOverflow, then other units. But I feel like it could be a lot of maintenance troubles and still it does not help with strings like `"next month"` or even more tricky `"sunday next month"` that cannot be represented as an interval but depends on the start point.

So I pass this issue as a documentation issue.
