### ISSUE TITLE
Language PHP files using incompatible format for some SCM systems

### ISSUE THREAD

**Issue by Harti** [briannesbitt/Carbon#1934]
Hello,

I encountered an issue with the following code:
```sh
p4 add -d -f -c 43854647 /home/.../.../.../vendor/nesbot/carbon/src/Carbon/Lang/aa_ER@saaho.php
```
... using Perforce source code management.

Carbon version: **2.26.0**

PHP version: **7.2.12**

I expected to get:

```
1 file opened for add
```

But I actually get:

```
The file named '/home/.../.../.../vendor/nesbot/carbon/src/Carbon/Lang/aa_ER@saaho.php' contains wildcards [@#%*].
    Can't add filenames with wildcards [@#%*] in them.
```

Would it hurt to rename those files to use "safe" names?
(Not checking in the files into Perforce is not an option in this case, unfortunately)

**Comment by kylekatarnls** [comment]
Hello,

According to https://www.perforce.com/manuals/v15.1/p4guide/chapter.usingp4.html you can use `%40` instead of `@`

I'm reluctant to renames files to support random programs that may give custom meaning to some characters. It's a good thing for Carbon users to easily find the file that matches the locale `"aa_ER@saaho"` they may use as is.

When using a particular syntax it's the responsibility of the program that choose this syntax (here it's p4) to provide escaping support and up to the user to escape his strings accordingly.

Thanks for your understanding.

**Comment by Harti** [comment]
Makes sense - thank you for the very swift and elaborate response.

For anyone else possibly stumbling across this issue in the future:
Using `p4 reconcile -f -m` will mark those files for addition/removal without any issues. :)
