### ISSUE TITLE
Wrong output for 2-digit year inputs

### ISSUE THREAD

**Issue by simioluwatomi** [briannesbitt/Carbon#1991]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('05-Jan-66')->format('Y-m-d');
```

Carbon version: **2.28.0**

PHP version: **7.2.22**

I expected to get:

```
1966-01-05
```

But I actually get:

```
2066-01-05
```

The argument passed to the parse function is gotten from an external API which I have no control over and won't be changed.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

[From PHP doc](https://www.php.net/manual/en/datetime.createfromformat.php)

> A two digit representation of a year (which is assumed to be in the range 1970-2069, inclusive)

That's means formatting the date as the external API you use do is a very very bad idea. It's ambiguous as you can see, but even worst, PHP will always assume 70 to 99 to be 19xx and 00 to 69 to be 20xx even when we'll be in 2070+ (unless a breaking change in PHP).

Saying that 66 is 1966 rather than 2066 is completely arbitrary. It's only a matter of context depending you're talking about future or past, close or farthest.

But if you're sure your API only return past dates, an easy fix can be:
```php
$date = Carbon::parse('05-Jan-66');

if ($date->isFuture()) {
    $date->subCentury();
}

echo $date->format('Y-m-d');
```

Thanks,

**Comment by kylekatarnls** [comment]
Still a big question, how to determine then if `19` is `2019` or `1919`.

Obviously `05-Jan-66` poor date format for an API. The norm widely used is [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601)

IMO, every API worthy of the name should use this norm.
