### ISSUE TITLE
Carbon timezone input/output for DST timezones inconsistent

### ISSUE THREAD

**Issue by Logiar** [briannesbitt/Carbon#2024]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::now('CEST')->format('P T') . PHP_EOL;
```

Carbon version: 2.30.0

PHP version: 7.4.3

I expected to get:

```
+02:00 CEST
```

But I actually get:

```
+01:00 CEST
```

Similarly with:
```php
echo Carbon::parse('2019-07-01 01:00:00 CEST')->format('Y-m-d H:i:s P T') . PHP_EOL;
echo Carbon::parse('2019-07-01 01:00:00', 'CEST')->format('Y-m-d H:i:s P T') . PHP_EOL;
```

I expected to get:
```
2019-07-01 01:00:00 +02:00 CEST
2019-07-01 01:00:00 +02:00 CEST
```

But I actually get
```
2019-07-01 01:00:00 +02:00 CEST
2019-07-01 01:00:00 +01:00 CEST
```

Thanks!

**Comment by kylekatarnls** [comment]
This is actually a PHP "bug":
```php
$date = new DateTime('now CEST');
echo $date->format('P T');
echo "\n";
$date = new DateTime('now', new DateTimeZone('CEST'));
echo $date->format('P T');
```
Output:
```
+02:00 CEST
+01:00 CEST
```
I put "bug" in quotes because now (February 28) actually does not exist as a valid date in CEST, as Europe is in CET during winter.

We can think about a way to better support it, but you should rather work with offset ("+01:00", "+02:00" or concrete timezones: "Europe/Paris", "Europe/London", etc.) rather than "CET" or "CEST".

Please have a look to:
https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164

And:
https://medium.com/@kylekatarnls/handle-dates-the-right-way-in-php-c215650fc4fa

It may help you working with timezones in a better way.

**Comment by Logiar** [comment]
The "now" in CEST was just code I wrote for testing. Was more concerned with the trap of the second example which would have been a valid date/time. I'm happy writing it off as php problem as working with dates that way is a bad idea. Just figured it's be good to fix if possible and if not at least for the issue to be known.
