### ISSUE TITLE
Incorrect assumption that any timezone with a zero offset is UTC

### ISSUE THREAD

**Issue by Salmatron** [briannesbitt/Carbon#2053]
Hello,

I encountered an issue with the following code:
```php
var_dump(Carbon::now('Africa/Timbuktu')->utc);
```

Carbon version: 2.30.0

PHP version: 7.3.14

I expected to get:

```
bool(false)
```

But I actually get:

```
bool(true)
```

There are quite a few timezones with a zero offset and they should not be considered "UTC". Here's the offending code:

```php
// vendor/nesbot/carbon/src/Carbon/Traits/Date.php

trait Date
{
// [...]

    public function get($name)
    {
    // [...]
        // @property-read bool checks if the timezone is UTC, true if UTC, false otherwise
        case $name === 'utc':
            return $this->getOffset() === 0;
```

Suggested fix:
```php
// @property-read bool checks if the timezone is UTC, true if UTC, false otherwise
case $name === 'utc':
    return $this->getTimezone()->getName() === 'UTC';
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

Thanks for your report, it's an interesting point. `->utc` currently matches the following definition: "Is current timezone equal to UTC now?" which is true for London for instance in December but false in Jully. And actually `true` for Timbuktu anytime.

Many app may also rely on UTC = GMT. So your change would be a breaking change and may have heavy consequences.

This is a very tricky point, because strictly no timezone can be UTC as UTC is a system and not a timezone, but when used in the native `DateTimeZone` of PHP "UTC" is implicitly understood as the timezone UTC+0 (which would be the correct representation).

For now, be aware you can use `Carbon::now('Africa/Timbuktu')->tzName === "UTC"`.

This getter was also supposed to be similar to isUTC() in moment.js and actually moment.js would use the same rule:

```js
console.log(moment().tz('Africa/Timbuktu').isUTC()); // true
```

If you think there are other arguments I should consider, they are welcome.

**Comment by Salmatron** [comment]
@kylekatarnls Fair enough. Thanks for everything you do!

I ran into this when porting some code from Ruby on Rails. Which checks by matching the time zone's abbreviation.

```ruby
pry(main)> Time.zone = 'Africa/Timbuktu'
=> "Africa/Timbuktu"
pry(main)> t = Time.zone.now
=> Fri, 03 Apr 2020 04:16:43 GMT +00:00
pry(main)> t.utc?
=> false
pry(main)> Time.zone = 'UTC'
=> "UTC"
pry(main)> t = Time.zone.now
=> Fri, 03 Apr 2020 04:17:00 UTC +00:00
pry(main)> t.utc?
=> true
```

The Rails implementation code:
```ruby
# activesupport/lib/active_support/time_with_zone.rb
def utc?
    period.offset.abbreviation == :UTC || period.offset.abbreviation == :UCT
end
```

Perhaps as a middle ground and to avoid unexpected behavior with DST, in a future version with a BC break it can be considered that `->utc` is only true if the current time zone's offset is always zero and doesn't change based on DST.
