### ISSUE TITLE
Declaration of Carbon\Translator::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale)

### ISSUE THREAD

**Issue by marcinsdance** [briannesbitt/Carbon#2057]
Hello,

Carbon/Translator extends Translation\Translator which implements LocaleAwareInterface - thus the error.
In vendor/nesbot/carbon/composer.json the dependency is symfony/translation ^5.0 but it's not compatible with v5.0.7

Carbon version: 2.32.2

PHP version: 7.3.15

I expected to get:

```
no error
```

But I actually get:

```
Declaration of Carbon\Translator::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale)
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

This error only happen PHP 7.1, it's compatible according to PHP 7.2+ constraints as proven by our Travis build.

https://github.com/briannesbitt/Carbon/issues/2033#issuecomment-596185060

Thanks,

**Comment by marcinsdance** [comment]
Thanks for having a look @kylekatarnls 
I'm pretty sure the PHP version is 7.3.15
Please have a look at the screenshot attached.
![php-version](https://user-images.githubusercontent.com/1252171/78607240-fb80c280-785e-11ea-9189-91da2735483e.png)

**Comment by kylekatarnls** [comment]
Please tell me where you downloaded your PHP binary/source, so I can use the same and try to reproduce the bug. As both Carbon and Laravel are tested automatically with Travis on every version from 7.2 to 7.4 and they don't trigger this error. Then we're many to use it in production yet with no trouble.

As explained in the other topic, this declaration respect the covariance introduced in PHP 7.2: https://php.net/manual/en/language.oop5.variance.php

This is compatible regarding PHP specifications and on the majority of the environments.  That's why we need more clues to determine where this error comes from.

**Comment by marcinsdance** [comment]
Ah I found the source of this issue. This was in fact PHP 7.1 I was using and I started messing with the files in vendor directory - that's why there's error on the screenshot. Once I made sure I'm running PHP 7.3 again, removed the entire directory and "composer install" - all works well.
Thanks for your help @kylekatarnls !! I'm closing the issue...
