### ISSUE TITLE
Creating with Timezone

### ISSUE THREAD

**Issue by az-joss** [briannesbitt/Carbon#2071]
Hello,

I encountered an issue with the following code:
```php
ini_set('date.timezone', 'UTC');

$timezone = new DateTimeZone('US/Samoa');
// current date is 2020-04-24
echo Carbon::createFromTime(0, 0, 0, $timezone)->format(Carbon::W3C);
```

Carbon version: 1.39.1 | 2.31.0

PHP version: 7.1.33

I expected to get:

```
2020-04-24T00:00:00-11:00
```

But I actually get:

```
2020-04-23T00:00:00-11:00
```

Thanks!

**Comment by kylekatarnls** [comment]
I tested your code in https://try-carbon.herokuapp.com/ and my local machine, and I get `2020-04-24T00:00:00-11:00`

Side note: default timezone should be set with `date_default_timezone_set('UTC');`

Can you check with pure PHP your actual offset to check you're actually the date/time you think on the environment you run your code:

```php
$samoa = new DateTimeZone('US/Samoa');

echo (new DateTime('now'))->format('Y-m-d H:i:s e')."\n"; // default timezone
echo (new DateTime('now', $samoa))->format('Y-m-d H:i:s e')."\n"; // US/Samoa
```

**Comment by az-joss** [comment]
@kylekatarnls 
I tested your code proposed by you, and result is:

```
$samoa = new DateTimeZone('US/Samoa');

echo (new DateTime('now'))->format('Y-m-d H:i:sP'); // 2020-04-28 18:11:39+00:00
echo (new DateTime('now', $samoa))->format('Y-m-d H:i:sP'); // 2020-04-28 07:11:39-11:00
```
seems like it is default begavior for DateTime of PHP.

But, I found the way that might be strange but works well for me:

```
$now = Carbon::now('UTC'); // 2020-04-28 18:28:58+00:00
$samoaTimezone = new DateTimeZone('US/Samoa');

echo Carbon::createFromTimeString($now->toString(), $samoaTimezone)->format(Carbon::W3C);
// 2020-04-28 18:28:58-11:00
```

**Comment by kylekatarnls** [comment]
In fact I don't understand why you expect to get UTC date and time when specifying Samoa timezone.

"now" is now and use the computer clock with the timezone you give to `DateTime` or default timezone if you didn't pass timezone.

To me what you do with giving UTC string and Samoa timezone is not strange but rather wrong. It's like falsifying dates, because now it's 9 AM in Samoa, not 20 PM, and -11:00 offset make it clear you have to subtract 11 hours to UTC (GMT timezone) to get Samoa time.
