### ISSUE TITLE
Carbon giving different dates for same timezone

### ISSUE THREAD

**Issue by Adam-78** [briannesbitt/Carbon#2073]
Hello,

I encountered an issue with the following code:
```php
echo  Carbon::today('Europe/London');
echo  Carbon::today()->timezone('Europe/London')
```

Carbon version: 2.30.0
PHP version: 7.4

I expected to get:

```
the same datetime using either method since I'm passing the timezone
```

But I actually get:

```
2020-05-04 00:00:00
2020-05-04 01:00:00
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

You can use `Carbon::today()->shiftTimezone('Europe/London');` to get the result you want, but first, take a look at this:

```php
echo Carbon::now('Europe/London');
echo Carbon::now()->timezone('Europe/London');
```

Both gives the same output, because it's now and it's in London in both case, so it's consecutive events (few microseconds gap) represented with the same timezone.

But:
```php
Carbon::today('Europe/London');
Carbon::today(); // = Carbon::today('GMT');
```
Represent 2 different moments, it's today (start of day) in London and today (start of day) in GMT. And the day (in summer) start 1 hour later in London than in GMT timezone.

Now if you change the timezone of today in GMT, you change only the timezone, not the moment, so you're 1AM in London.

Thanks,

**Comment by kylekatarnls** [comment]
To better see the difference, take Pacific islands some use GMT-12 and other use GMT+14, "today" will never be the same date digits (in the same moment), when today is Monday in GMT-12, it's always Tuesday in GMT+12: `Carbon::parse('Monday', '-12:00')->timezone('+12:00')->dayName` is `"Tuesday"`

So it's exactly the same for your case with a 1-hour shift: `Carbon::parse('00:00:00', '+00:00')->timezone('+01:00')->format('H:i')` is `"01:00"` and today is the period from 00:00:00 to 23:59:59 in the current timezone, so the method `today()` use the start of this period as it's the logical and more convenient to operations/calculations.
