### ISSUE TITLE
Message: syntax error, unexpected '|', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by eduardovalenzuela** [briannesbitt/Carbon#2099]
Good day,

I have upgraded Carbon library on my local and it works fine, but did same on my server and I now get this error:

"An uncaught Exception was encountered
Type: ParseError

Message: syntax error, unexpected '|', expecting variable (T_VARIABLE)

Filename: /home1/quantaru/public_html/groupgyft/mylab/vendor/nesbot/carbon/src/Carbon/Traits/Date.php

Line Number: 1032"

I have checked the line and it is:

vendor/nesbot/carbon/src/Carbon/Traits/Date.php

```
public function __isset($name)
    {
        try {
            $this->__get($name);
        } catch (UnknownGetterException | ReflectionException $e) {
            return false;
        }

        return true;
    }
```

The error is when using the pipe operator.

PHP version on server:

PHP 7.2.31 (cli) (built: May 19 2020 20:03:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.

Any ideas?

**Comment by kylekatarnls** [comment]
Hello,

Piped exceptions are supported since PHP 7.1:
https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.mulit-catch-exception-handling

And what you show is a CLI version of PHP so it's likely not the one that is ran in the webserver (e.g. Apache, nginx, etc., which is different from the version of PHP CLI program).

**Comment by eduardovalenzuela** [comment]
Thanks buddy, the thing is that in cpanel said 7.2, but domain had custom version.
