### ISSUE TITLE
Carbon::CreateFromTimestamp() does not set TZ on date creation, it converts the time after creation

### ISSUE THREAD

**Issue by sandiproy876** [briannesbitt/Carbon#2134]
Hello,

I encountered an issue with the following code:
```php
        $timestamp = strtotime('11 August 2020 11:30am');
        $date = Carbon::createFromTimestamp($timestamp, 'Asia/Dhaka');
```

Carbon version: **2.16**

PHP version: **7.3**

I expected to get:

```
    2020-08-11 11:30:00.0 Asia/Dhaka (+06:00)
```

But I actually get:

```
    2020-08-11 17:30:00.0 Asia/Dhaka (+06:00)
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello @sandiproy876,

The timestamp is a number of second since January 1st 1970 midnight _GMT+00_, it's a fixed universal representation of the time that does not change with the timezone.

What you expect can be get with:
```php
$timestamp = strtotime('11 August 2020 11:30am');
$date = Carbon::createFromTimestamp($timestamp, 'UTC')->shiftTimezone('Asia/Dhaka');
```

But it's more likely a misconception. You should not use timestamps this way.

First note that you can simple pars the string:
```php
$date = Carbon::parse('11 August 2020 11:30am', 'Asia/Dhaka');
```

You should work with UTC (GMT) server-side and only use real timezones like Asia/Dhaka when you parse an external/user input or want to display a date to an end-user. [See more in this article](https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164)

Thanks.
