### ISSUE TITLE
PHPStan complains about Carbon::create suddenly returning false?

### ISSUE THREAD

**Issue by ruudk** [briannesbitt/Carbon#2135]
Hello,

I encountered an issue with the following code:
```php
        Carbon::setTestNow(Carbon::create(2017, 4, 4, 13, 58));
```

Carbon version: 2.36.1
PHP version: 7.4

PHPStan complains everywhere I use the code snippet above:
```
  24     Parameter #1 $testNow of static method Carbon\Carbon::setTestNow()
         expects Carbon\Carbon|Closure|string|null, Carbon\Carbon|false given.
```

This has been introduced in https://github.com/briannesbitt/Carbon/pull/1916.

I don't get why `create` can 1) return a date, 2) throw an exception or 3) return false? It's not in the interface, but only in the implementation.

**Comment by kylekatarnls** [comment]
Hello, first, you can write your date right in `setTestNow()`:
```php
Carbon::setTestNow('2017-04-04 13:58');
```
That's probably the more readable way to define it anyway.

> It's not in the interface, but only in the implementation

This should be in the interface too because `create()` can actually return `false`, for instance with:
```php
Carbon::useStrictMode(false);
var_dump(Carbon::create(2017, 914, 4, 13, 58));
```

With the strict mode, it would throw an exception. In the normal case, it return the date, that's for the answers to your 1/2/3.

And `setTestNow()` wouldn't handle `false` properly,

So PHPStan seems to do its job rather fairly. And while we obviously know `Carbon::create(2017, 4, 4, 13, 58)` is static and so will never return `false`, PHPStan can't guess it and we can't send this info to PHPStan neither.

Indeed this was not a problem before #1916 but only because PHPStan was completely unaware of the `false` possibility.

We don't have too many options to make things better.
- revert the typing => this actually would be a falsification (hidden what can happen in the reality just to make things to look more compatible than they actually are).
- handling false in `setTestNow()` => does not make sense and would imply to do the same in many other methods. But for this particular case it would just imply to replace `return static::getTestNow() !== null;` with `return !!static::getTestNow();` to handle `false` as an equivalent for `null` and that could be acceptable.

**Comment by ruudk** [comment]
Would be great if strict mode could be enabled by default (in a new major) and then get rid of the `false` returns.

**Comment by kylekatarnls** [comment]
strict mode **is** enabled by default. If you didn't change it, `create()` will throw exceptions and so will never return `false`, but PHPStan can't know if the strict mode had been disabled or not.

**Comment by ruudk** [comment]
Oké maybe disabling strict mode should not exist at all in future version then?

**Comment by kylekatarnls** [comment]
Interface and other PHPDoc for `create()` method has been fixed (added `|false` as it's the actual return type) and `setTestNow()` now accepts silently `false` (equivalent to `null` => removing the testNow reference).

IMO, this is the only thing we should do about that for the 2.x version.

**Comment by ruudk** [comment]
@kylekatarnls Thanks, could you tag a new release with this? 🙏

**Comment by kylekatarnls** [comment]
Release of 2.37 is planned for Tuesday.

Meanwhile you can set `"nesbot/carbon": "2.x-dev"` in your **composer.json** to test the next version.

**Comment by i-bajrai** [comment]
Maybe look to how Chronos uses the create function?

```    public static function create(
        ?int $year = null,
        ?int $month = null,
        ?int $day = null,
        ?int $hour = null,
        ?int $minute = null,
        ?int $second = null,
        ?int $microsecond = null,
        $tz = null
    ): ChronosInterface {
        $now = static::now();
        $year = $year ?? (int)$now->format('Y');
        $month = $month ?? $now->format('m');
        $day = $day ?? $now->format('d');

        if ($hour === null) {
            $hour = $now->format('H');
            $minute = $minute ?? $now->format('i');
            $second = $second ?? $now->format('s');
            $microsecond = $microsecond ?? $now->format('u');
        } else {
            $minute = $minute ?? 0;
            $second = $second ?? 0;
            $microsecond = $microsecond ?? 0;
        }

        $instance = static::createFromFormat(
            'Y-m-d H:i:s.u',
            sprintf('%s-%s-%s %s:%02s:%02s.%06s', 0, $month, $day, $hour, $minute, $second, $microsecond),
            $tz
        );

        return $instance->addYears($year);
    }
```

It is a really weird/annoying interface to have to check for false:

`(Carbon::create(...$date) ?: Carbon::now())->setTime(0, 0)`

Perhaps a `createStrict` and only return static would be a possible solution (or vice versa though it would probably not be as backwards compatible.)

**Comment by kylekatarnls** [comment]
Chronos chose to ignore error case. In the code you gave `$instance` can be `false` and so `$instance->addYears()` would produce an error (not very easy to debug) before the return so indeed you can only have `ChronosInterface` returned when there is no runtime error inside.

You'll get the same with `Carbon::useStrictMode(true);` but with a bit more detailed exception.

Sure we could easily remove `|false` from type hints and chill static analyzers like PHPStan. And while we know `|null` would have been a better fit, we just rely on PHP itself for that point: https://www.php.net/manual/en/datetime.createfromformat.php

So it won't change during 2.x version.

In 3.x strict-mode will be `true` by default which could allow to ignore `false` returns if every methods properly throw exception for all `falsy` cases.

Main point here is type-checking (done by PHPStan or any other tool) are here to help making you aware of precisely and exhaustively all the possible type of values you can have to handle to avoid you miss some edge-case. That's why hidding possible return would actually break the whole purpose of type-cheking.

**Comment by i-bajrai** [comment]
@kylekatarnls thanks for the detailed response, I believe the solution here then would be to create a wrapper in my own code for Carbon to return the correct type (and handle the exception).

If I understand Chronos, it handles and falsey value by throwing an invalid argument exception (which I would get my wrapper to emulate).

Was wondering if it was worth expanding the API but seeing as 3.x is coming then this is fine :)

**Comment by kylekatarnls** [comment]
I can't see any proper handling In the code you show:

```php
        $instance = static::createFromFormat(
            'Y-m-d H:i:s.u',
            sprintf('%s-%s-%s %s:%02s:%02s.%06s', 0, $month, $day, $hour, $minute, $second, $microsecond),
            $tz
        );

        return $instance->addYears($year);
```

If `createFromFormat` is the native PHP method, it can return `false` and `false->addYears()` would fail badly. So you would get an error but it would not be so clear, it would be "Cannot call addYears on false". Then I'm not really sure what's lie behind this hack of creating a date at year 0 and adding the years after.

So if there is any better error handling, it's in `createFromFormat` if it's overridden. Else it just assumes it receives always valid input.

**Comment by kylekatarnls** [comment]
I recommend:

```php
Carbon::macro('createStrict', static function ($year = 0, $month = 1, $day = 1, $hour = 0, $minute = 0, $second = 0, $tz = null) {
  $initialStrictMode = static::isStrictModeEnabled();
  static::useStrictMode(true);

  try {
    $date = static::create($year, $month, $day, $hour, $minute, $second, $tz);
  } catch (\Exception $exception) {
  }

  static::useStrictMode($initialStrictMode);

  if (isset($exception)) {
    throw $exception;
  }

  return $date;
});
```

The same is possible for all the method with strict-mode behavior variation.

**Comment by martinssipenko** [comment]
Perhaps using https://github.com/thecodingmachine/safe would help in this case? It extends native classes making sure exceptions are thrown instead of returning false.

**Comment by kylekatarnls** [comment]
Strict mode available in Carbon is exactly the same.

**Comment by martinssipenko** [comment]
If I understand correctly the `false` return type can't be removed because if strict mode is disabled it could actually return `false` right?

**Comment by kylekatarnls** [comment]
A generic problem well know by PHPStan team (but that apply to any PHP static analyzer) is that you can't have dynamic typing like in TypeScript for instance, example:

```php
function foo($bar)
{
   if (is_int($bar)) {
     return 'bar';
   }

  return 5;
}

$a = foo(7);
```

In this example, static analyzer could theoretically know that `$a` is a string because we passed an int. But we don't have currently any way to say if `@param` is int, then `@return` is string. That's a PHP parsing limitation.

So return type should be any possible types the function is allowed to return. So as long as the method can return `false` in some situation, we should not remove it from the return types.

But if you're using strict mode, you're sure you'll never get `false` and you can safely create a function with a simple `@return static` type:

```php
/**
 * Create a new Carbon instance from a specific date and time.
 *
 * If any of $year, $month or $day are set to null their now() values will
 * be used.
 *
 * If $hour is null it will be set to its now() value and the default
 * values for $minute and $second will be their now() values.
 *
 * If $hour is not null then the default values for $minute and $second
 * will be 0.
 *
 * @param int|null                 $year
 * @param int|null                 $month
 * @param int|null                 $day
 * @param int|null                 $hour
 * @param int|null                 $minute
 * @param int|null                 $second
 * @param DateTimeZone|string|null $tz
 *
 * @throws InvalidFormatException
 *
 * @return static
 */
public static function createDate($year = 0, $month = 1, $day = 1, $hour = 0, $minute = 0, $second = 0, $tz = null)
{
    return Carbon::create($year, $month, $day, $hour, $minute, $second, $tz);
}
```

**Comment by kylekatarnls** [comment]
You can also enforce type:
```php
/** @var Carbon */
$date = Carbon::create($year, $month, $day, $hour, $minute, $second, $tz);
```

**Comment by kylekatarnls** [comment]
@i-bajrai `createStrict()` will finally be implemented in 2.49.0

**Comment by kylekatarnls** [comment]
The thing is that is it actually can return `false` this legacy stuff is all many many methods/functions in PHP, it should return `null` or throw an exception, but this `false`-return will likely survive long for backward-compatibility.

**Comment by spawnia** [comment]
> it actually can return `false`

You said it can not - see https://github.com/briannesbitt/Carbon/issues/2135#issuecomment-662042417 (at least for `create()`, I am assuming the same is true for `createFromFormat()`) - given strict mode is enabled. I understand that the method signature will have to remain the same, as strict mode is set dynamically, but I think we can improve static analysis.

> PHPStan can't know if the strict mode had been disabled or not.

This is not necessarily true. For example, Larastan bootstraps the framework to have some level of dynamism in static analysis - see https://github.com/nunomaduro/larastan/issues/683#issuecomment-708332933. I reckon the `Carbon` extension could do the same - or expose custom config parameters.
