### ISSUE TITLE
How to properly format the date with format

### ISSUE THREAD

**Issue by MuhammadSaim** [briannesbitt/Carbon#2156]
Hello,

I encountered an issue with the following code:
My first line is works correctly with the format
```php
$age = \Carbon\Carbon::createFromFormat("Y-m-d h:i a", $birthday_string, $_POST['timezone'])->diff(\Carbon\Carbon::now())->format("%y years, %m months and %d days %h hours and %i minutes");
```

but this 2nd one format is not working as i expected
```php
$born_in = \Carbon\Carbon::createFromFormat("Y-m-d h:i a", $birthday_string, $_POST['timezone'])->format("%h:%i %A On %l %d %F %Y");
```

![image](https://user-images.githubusercontent.com/19898499/89814580-c4982180-db5c-11ea-938b-58a62d7e58dc.png)

This is the output which I get and I expect 2nd output same as the 1st one

Carbon version: **2.38**

PHP version: **7.3**

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

`->format()` is not the right tool for this output. `diffForHumans()` is way more appropriate and will handle for you names of the units, comma/and, and internationalisation if you need it:
https://carbon.nesbot.com/docs/#api-humandiff

Secondly, the `->format()` method is inherited from the native PHP method and while the `DateInterval::format` use `%` pattern as follow:
https://www.php.net/manual/fr/dateinterval.format.php

The `DateTime::format` method actually use 1-letter pattern:
https://www.php.net/manual/fr/datetime.format.php

(this is the one you use in your second example because it's called on the birthday date (not an an interval like the first example where you have the interval between your date and now)

I don't know why those methods work so differently between `DateTime` and `DateInterval` but as a sub-class, we must keep the compatibility so `Carbon` objects can be used in libraries expecting `DateTime`/`DateInterval`

So inherited methods are kept compatible, but that's clearly not the tool to use for your first example, and for the second, yes it does the job good enough for an English-only application, but for an I18N-compatible application, you should rather consider `->isoFormat()`:
https://carbon.nesbot.com/docs/#iso-format-available-replacements

Thanks.
