### ISSUE TITLE
CarbonImmutable::parse() accepts `int` but phpstan complains

### ISSUE THREAD

**Issue by mfn** [briannesbitt/Carbon#2158]
Hello,

Carbon version: 2.37.0
PHP version: 7.4.7

I encountered an issue with the following code:
```php
echo Carbon\CarbonImmutable::parse(1597218878)->__toString();
```

Code works ™️ but phpstan (0.12.34) complains:
```
         Parameter #1 $time of static method Carbon\CarbonImmutable::parse()
         expects DateTimeInterface|string|null, int|null given.
```
But passing `int` works.

My real use case is receiving a webhook with an `int` timestamp mapped in a DTO with the type correctly and then calling this to convert it to CarbonImmutable.

I found out that `Carbon\CarbonImmutable::make` documents it's parameter as `mixed` thus phpstan wouldn't complain.

But I re-read `parse` vs. `make` a few times and still don't _really_ understand which one to use when.

Would it not be correct to document `::parse` also accepting `int`? (as well as the constructor, as the docs mentioned "CarbonImmutable")

Any guidance here would be very welcome :)

**Comment by mfn** [comment]
> My real use case is receiving a webhook with an `int` timestamp mapped in a DTO with the type correctly and then calling this to convert it to CarbonImmutable.

Actually that's not quite correct. My use case is having DTO properties marked as being convertable to CarbonImmutable and they came in flavours of `null|int|string`.

So basically I throw whatever I got (to a certain degree) and hope for the best when I throw it over the fence to CarbonImmutable 😄 

That said, I already saw first-hand a difference between `::parse` and `::make`:
```
>>> \Carbon\CarbonImmutable::parse(null)
=> Carbon\CarbonImmutable @1597219631 {#4222
     date: 2020-08-12 08:07:11.048915 UTC (+00:00),
   }
>>> \Carbon\CarbonImmutable::make(null)
=> null
```
🤔

**Comment by mfn** [comment]
Haha, I give up. Just realized `make` does not "work" with `int`, i.e. it returns `null`:
```
vagrant@swatio-dev /vagrant/api.swat.io $ ./artisan tinker
Psy Shell v0.10.4 (PHP 7.4.7 — cli) by Justin Hileman
>>> Carbon\CarbonImmutable::make(1597218878);
=> null
```
🤷‍♀️

**Comment by mfn** [comment]
I think I finally understand, `:parse` being an alias for the constructor which is also used to "just return the current time".

For my use-case I decided to use `::parse` because it handles `int` the way I expect it but have to special case handling `null` in my code for those cases to _not_ pass it to parse.

Closing the issue as I know how to continue but if @kylekatarnls could share some insights to this, I'm happy to hear more!

**Comment by kylekatarnls** [comment]
As the next developer or the futur you reading the code, I would prefer to see an explicit call to `Carbon::createFromTimestamp(1597218878)` so I immediately identify what is this number and what the code it trying to do with it while "parse" intuitively make think we're extracting information chunks from a string (which also is the original purpose of the method), the current integer support is actually a convenient tool that assumes the `@` was omitted and so try give `@1597218878` to the native PHP `DateTime` constructor for parsing.

So I don't think it would be needed to add the `int` typing in `parse()` PHPDoc, as I don't think this usage should be encouraged.

For the particular case of the timestamp, be aware, there is a difference between of behavior in the handling of the timezone:
```php
echo Carbon::createFromTimestamp(0, 'UTC')."\n";
echo Carbon::createFromTimestamp(0, 'America/Toronto')."\n";
echo "\n";
echo Carbon::parse(0, 'UTC')."\n";
echo Carbon::parse(0, 'America/Toronto')."\n";
```
[Run code](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=echo%20Carbon%3A%3AcreateFromTimestamp(0%2C%20%27UTC%27).%22%5Cn%22%3B%0Aecho%20Carbon%3A%3AcreateFromTimestamp(0%2C%20%27America%2FToronto%27).%22%5Cn%22%3B%0Aecho%20Carbon%3A%3Aparse(0%2C%20%27UTC%27).%22%5Cn%22%3B%0Aecho%20Carbon%3A%3Aparse(0%2C%20%27America%2FToronto%27).%22%5Cn%22%3B)
```
1970-01-01 00:00:00
1969-12-31 19:00:00

1970-01-01 00:00:00
1970-01-01 00:00:00
```

While parse (native PHP DateTime __construct) consider 0 is the 1st January in the given timezone, createFromTimestamp respect the strict definition of timestamp where 0 is always the 1st January GMT+0.

It's generally way safer to use an universal fixed 0-reference, rather than using a variable reference (what happen with `parse()`).

**Comment by mfn** [comment]
Ok, so at this point, because I use `::parse`:
- I've special cased the `null` case (I don't want the current time in this case)
- I should add a special case for `int`

Now I wonder: at this point, why would I favour `::parse` over `::make`?

Since `int` handling should be separately, I won't be calking `::make` with `int`. And `::make` does handle `null` the way I need it (returning `null` and not the current time).

With `::parse()` I would need this:
```php
function makeCarbonImmutable(string|int|null $value): ?CarbonImmutable
{
    if (null === $value) {
        return null;
    }

    if (is_int($value)) {
        return CarbonImmutable::createFromTimestamp($value);
    }

    return CarbonImmutable::parse($value);
}
```

With `::make` I _could_ have this:
```php
function makeCarbonImmutable(string|int|null $value): ?CarbonImmutable
{
    if (is_int($value)) {
        return CarbonImmutable::createFromTimestamp($value);
    }

    return CarbonImmutable::make($value);
}
```

Remember my use case is that I receive `$value` from external and this is my line of "validation" (In case of strings I don't care about the actual format, I'm fine with whatever Carbon can at best parse out of it, that's intentional).

Thanks so far 😄

**Comment by kylekatarnls** [comment]
make() brings the following values:
- it relies to `parse()` only if the input is a string (which is actually what parse is intended to receive even if it supports more for convenience)
- return `null` as is (which is actually designed for conversion for nullable date/time database fields but external service is the same principle
- semantic: it's more obvious it supports various types of data (DateTimeInterface|string|null)

Handling int with createFromTimestamp in make sounds like a fair possible enhancement. But meanwhile, the `is_int($value)` if-statement is the right way to handle timestamps.

If you possibly can have to deal with non-GMT dates (as the timezone for Carbon instance to be created), then you will also have to care about string containing only digits if it can happen to redirect them to createFromTimestamp too.
