### ISSUE TITLE
Carbon::parse always takes default timezone, wont respect second argument

### ISSUE THREAD

**Issue by danielsetreus** [briannesbitt/Carbon#2163]
Hello,

I encountered an issue with the following code:
```php
$bookingDate = Carbon::parse('2020-08-17 15:00:00', 'Europe/London');
echo $bookingDate->getTimezone()->getName();
```

Carbon version: 2.38.0

PHP version: 7.3

I expected to get:

```
Europe/London
```

But I actually get the default timezone (set by Laravel):

```
Europe/Stockholm
```

The following code works as expected:
```php
$bookingDate = Carbon::createFromFormat('Y-m-d H:i:s, '2020-08-17 15:00:00', 'Europe/London');
$bookingDate->getTimezone()->getName(); // Europe/London
```

Thanks!

**Comment by kylekatarnls** [comment]
I can't reproduce this bug, when I try it in https://try-carbon.herokuapp.com/ or on my local machine, I get "Europe/London".

The Laravel timezone should not interfere when you explicitly call `parse`.

Is there a setTestNow() is use?

**Comment by kylekatarnls** [comment]
Side note:

Check https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164 and https://medium.com/@kylekatarnls/handle-dates-the-right-way-in-php-c215650fc4fa because having `"Europe/Stockholm"` as your default `'timezone'` in Laravel config is very likely a mistake.

A back-end meant to be scalable and/or accessed via users/external services across different timezones and/or reused in different contexts should use the standard agnostic `"UTC"` timezone on the back-end side and only use real-world timezone when formatting a date for a specific user.

**Comment by danielsetreus** [comment]
> Side note:
> 
> Check https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164 and https://medium.com/@kylekatarnls/handle-dates-the-right-way-in-php-c215650fc4fa because having `"Europe/Stockholm"` as your default `'timezone'` in Laravel config is very likely a mistake.

Could not agree more - this is a problem we are stuck with from previous developers. As a more powerful man would say; SAD! 

The problem itself seems to be very hard to reproduce outside of our somewhat strange Laravel setup - and without any obvious "gotchas" anyone might think of you are free to close this issue. I will have to dig deeper into it in our own code base.

**Comment by kylekatarnls** [comment]
The only thing I see is `setTestNow()` try to inspect `Carbon::getTestNow()` just before the `parse()` call, if it's set to a Stockolm timezone date, here is your problem. And more generally, testNow should be `null` anywhere else than in unit/e2e tests.

If it's null, then, this is likely not a Carbon issue.
