### ISSUE TITLE
Polyfill for DateTime/DateTimeImmutable::createFromInterface

### ISSUE THREAD

**Issue by Ayesh** [briannesbitt/Carbon#2171]
Carbon version: **2.3.9**

PHP version: **7.4.9**

---

PHP 8.0 adds two new methods [`DateTime::createFromInterface()` and `DateTimeImmutable::createFromInterface()`](https://php.watch/versions/8.0/datetime-immutable-createfrominterface). They accept any `DateTimeInterface` object (in contrast to `DateTime::createFromImmutable` and `DateTimeImmutable::createFromMutable`). 

Due to Carbon's wide usage, I'd like to suggest that we can try and implement these two new methods in Carbon, so those two new methods are available in all PHP versions Carbon supports (PHP `^7.1 || ^8.0` as of this moment). 

They can be trivially polyfilled (see below), and if maintainers agree, I'd be happy to send a PR. 

```php
trait DateTimeCreateFromInterfacePolyfill {
    public function createFromInterface(\DateTimeInterface $object): \DateTime {
        if ($object instanceof \DateTimeImmutable) {
            return \DateTime::createFromImmutable($object);
        }
        if ($object instanceof \DateTime) {
            return clone $object;
        }
        throw new \InvalidArgumentException('Unexpected type');
    }
}
```

```php
trait DateTimeImmutableCreateFromInterfacePolyfill {
    public function createFromInterface(\DateTimeInterface $object): \DateTimeImmutable {
        if ($object instanceof \DateTime) {
            return \DateTimeImmutable::createFromMutable($object);
        }
        if ($object instanceof \DateTimeImmutable) {
            return clone $object;
        }
        throw new \InvalidArgumentException('Unexpected type');
    }
}
```

The [post in PHP.Watch](https://php.watch/versions/8.0/datetime-immutable-createfrominterface) has a more complete example if it helps (disclaimer: I maintain this site).

```php
class Carbon extends DateTime implements CarbonInterface
{
    use Date;
    use DateTimeCreateFromInterfacePolyfill;
```

```php
class CarbonImmutable extends DateTimeImmutable implements CarbonInterface
{
    use Date;
    use DateTimeImmutableCreateFromInterfacePolyfill;
```

We can safely remove these polyfill traits when Carbon requires PHP 8.0 as the minimum version, and it wouldn't cause any BC breaks because PHP 8.0 has these two methods with exact same method signature. 

Thank you.

**Comment by kylekatarnls** [comment]
Hello,

Getting a `DateTimeImmutable` rather than a `CarbonImmutable` when calling a `CarbonImmutable` seems really unexpected to me. It's consistent with existing createFromMutable/createFromImmutable but I think it would have been more relevant for PHP to create `new static` instances and not `new self`. That's a inheritance breaking for me. It can lead to misunderstanding. I'm not sure we should promote this in PHP < 8.

That also means you can pass a `DateTime` as a parameter to get a `DateTimeImmutable`. In this situation, it sounds to me like using `Carbon` for this conversion is not the right tool. And if you have a Carbon instance, you can simply use `toDateTime()` / `toDateTimeImmutable()`.

If you want `Carbon` / `CarbonImmutable` instance (or any sub-class as it doesn't break inheritance) (which for me is more relevant in most situations), then it's yet fulfilled with `Carbon::instance()`. I would promote this one over `createFromInterface()`.

If we override the PHP methods, we'll have to maintain them (parameters can be added in PHP 8.1, 8.2... and change deeper in PHP 9). As the feature is not exactly missing, it's not worthy.

Last: the code you propose will output pure `DateTime` (first if) or `Carbon` (second if), this sounds not safe to use as is.

I would say the way to get this exact method is to upgrade to PHP 8. Do you see some other reason to add it specifically in Carbon that justify to use `createFromInterface` instead of other available methods?

**Comment by Ayesh** [comment]
Thanks a lot for the detailed and quick reply @kylekatarnls. I'm super grateful for this. 

You are right, I agree that there is a hidden maintenance burden with this, and it's probably not worth the effort because PHP 7.4 will be the only active PHP 7.x version in a few months, and Carbon may need to keep up with changes if Carbon were to polyfill/decorate these new methods. 

I use Carbon as a drop-in replacement on projects that don't use it, and I thought it would be nice if it could polyfill a feature that comes with PHP 8. But I now see from the other point of view, that it wouldn't be as complete, nor worth the effort to do it in Carbon. 

Thank you for your time and I appreciate your detailed response 🙏.
