### ISSUE TITLE
Carbon::createFromFormat('m/Y', '09/2020') can return a datetime for the incorrect month

### ISSUE THREAD

**Issue by rhys-steele** [briannesbitt/Carbon#2172]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromFormat('m/Y', '09/2020')
echo Carbon::createFromFormat('m/Y', '09/2020')->startOfMonth();
echo Carbon::createFromFormat('m/Y', '09/2020')->endOfMonth();
```
When the day that the code is executed is a higher day than the last day of the month being parsed.

Carbon version: **2.24.0**

PHP version: **7.4.5**

If today is the 31st of any month and I was to run the above commands I would expect to get the following output

```
>>> echo Carbon::createFromFormat('m/Y', '09/2020')
2020-09-30 13:49:48⏎
>>> echo Carbon::createFromFormat('m/Y', '09/2020')->startOfMonth()
2020-09-01 00:00:00⏎
>>> echo Carbon::createFromFormat('m/Y', '09/2020')->endOfMonth()
2020-09-30 23:59:59⏎
```

But the following is returned

```
>>> echo Carbon::createFromFormat('m/Y', '09/2020')
2020-10-01 13:49:48⏎
>>> echo Carbon::createFromFormat('m/Y', '09/2020')->startOfMonth()
2020-10-01 00:00:00⏎
>>> echo Carbon::createFromFormat('m/Y', '09/2020')->endOfMonth()
2020-10-31 23:59:59⏎
```
Similarly this is present in the three day period between January 28th and February 1st on a non-leap year.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

The [createFromFormat](https://www.php.net/manual/fr/datetime.createfromformat.php) method is actually a native PHP `DateTime` method. Carbon does not change anything about the behavior. And that's actually the expected behavior according to PHP developers. It create the date from Year 2020, Month 9, current day, current time so 2020-09-31. And as soon as a date does not exist in the calendar, PHP overflow the number to exceeding days to the next month =>2020-10-01. So you need to prefix your format with `!`, it will use minimum value (1 for day, 0 for hour, etc.) instead of the current value for units which are not in the format:
```php
echo Carbon::createFromFormat('!m/Y', '09/2020')
echo Carbon::createFromFormat('!m/Y', '09/2020')->startOfMonth();
echo Carbon::createFromFormat('!m/Y', '09/2020')->endOfMonth();
```

Thanks.

**Comment by iamaks1993** [comment]
> Hello,
> 
> The [createFromFormat](https://www.php.net/manual/fr/datetime.createfromformat.php) method is actually a native PHP `DateTime` method. Carbon does not change anything about the behavior. And that's actually the expected behavior according to PHP developers. It create the date from Year 2020, Month 9, current day, current time so 2020-09-31. And as soon as a date does not exist in the calendar, PHP overflow the number to exceeding days to the next month =>2020-10-01. So you need to prefix your format with `!`, it will use minimum value (1 for day, 0 for hour, etc.) instead of the current value for units which are not in the format:
> 
> ```
> echo Carbon::createFromFormat('!m/Y', '09/2020')
> echo Carbon::createFromFormat('!m/Y', '09/2020')->startOfMonth();
> echo Carbon::createFromFormat('!m/Y', '09/2020')->endOfMonth();
> ```
> 
> Thanks.
> 
> Solution provided originally by [#1003 (comment)](https://github.com/briannesbitt/Carbon/issues/1003#issuecomment-370336838)

Thanks
