### ISSUE TITLE
⭐ hasFormat with modifiers in format

### ISSUE THREAD

**Issue by Sharptsa** [briannesbitt/Carbon#2198]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::hasFormat('2017-01-23', 'Y-m-d|');
```

Carbon version: **2.40.1**

PHP version: **7.3.22**

I expected to get:

```
true
```

But I actually get:

```
false
```

This worked in Carbon version **2.39.0** 

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

It actually worked before 2.39.2 by accident because some RegExp characters were incorrectly ignored. The end-pipe was never checked as a format modifier.

And the same goes for other modifiers. For instance `!Y-m-d` format returned `false` for the same string before 2.39 already while it's actually a possible format.

Currently, hasFormat intent to check format using only the replacements of [format()](https://www.php.net/manual/fr/datetime.format.php).

I wonder if it would be a good idea to support all the characters and modifier of [createFromFormat()](https://www.php.net/manual/fr/datetime.createfromformat.php) too.

Meanwhile, if what you need is strictly to know is a string can properly create a date using the given format, the simple way is to use the native PHP method `DateTime::createFromFormat`:

```php
$date = '2017-01-23';

if (DateTime::createFromFormat('Y-m-d|', $date)) {
  // $date matches Y-m-d|
} else {
  // $date does no match Y-m-d|
}
```

Thanks,

**Comment by Sharptsa** [comment]
Hello,

Yes, I ended up using `DateTime::createFromFormat` alone for my use case.

I think the support of `createFromFormat` characters and modifiers would be a nice thing to have.

There is likely a use for it for more complex use cases. Like passing a date trough validation, conversion and other processing using only one format.

Thanks!

**Comment by kylekatarnls** [comment]
`hasFormat()` is right now useful as a strict test (such as checking trailing 0 are present while `createFromFormat` does not complain receiving 7 instead of 07 for `d` for instance).

But if we `hasFormat()` result is a perfect match of `createFromFormat() === false`, there is no added value.

Last thing is modifiers are actually shortcuts for some option specific to `createFromFormat`, they're not really part of the format of the string to be tested and can not be used in `format()`:

```php
Carbon::parse('2020-12-31')->format('Y-m-d|') // 2020-12-31|
```
Here the pipe is raw in the output. So matching `createFromFormat()` implies to no longer match `format()`.

**Comment by kylekatarnls** [comment]
`hasFormat()` will continue to match the `format()` and [a new method `hasFormatWithModifiers()`](https://github.com/briannesbitt/Carbon/pull/2207) will be added in 2.41.0 to include modifiers and match `createFromFormat()`
