### ISSUE TITLE
["FEATURE REQUEST"] Any plans to port Nesbot/Carbon to JS?

### ISSUE THREAD

**Issue by tarreislam** [briannesbitt/Carbon#2202]
Hello,

Do you guys have any plans to "carbon copy" Nesbot/Carbon to JS? I know there exists mainstream JS alternatives, but they are not very pleasant to work with, especially when you have to have separate packages to solve time zones for example.

Thanks in advance

**Comment by kylekatarnls** [comment]
Hello,

There no such thing like a magic tool to create a JS library from a PHP one unless you work with very low-level not language-specific component. `Carbon` extends the native `DateTime` PHP class. JS use a completely different `Date` class implementation.

So you're either talking about creating a whole new library from scratch in an other language, or completely refactor carbon in some agnostic way to be able to generate both the PHP and JS built from this agnostic code-base using specific transformers for each language.

This is nearly most work than the whole library. I don't have so much free time available for that.

**Comment by kylekatarnls** [comment]
I investigated a bit deeper but it would be a very heavy JS library to be compatible with some inherited methods of `DateTime` like the `modify()` or `parse()` methods which would need a parser.

Then JS itself (in most browsers and Node.js >= 14) has tools to handle languages and time zones:
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Intl/DateTimeFormat

This is highly recommended to use it instead of loading more libraries.

A more appropriate approach could be to write some documentation about common date and time operation handled in JS. We would be glad to recommend tutorials or JS libraries that can show some best-practices.

Thanks for your contribution.

**Comment by tarreislam** [comment]
Okay, thanks for the info.
