### ISSUE TITLE
📖 Carbon 2.x Upgrade Guide Missing Breaking Change

### ISSUE THREAD

**Issue by tyler-reed-tsico** [briannesbitt/Carbon#2223]
Hello,

This issue is more directed towards a breaking change from 1.x to 2.x that wasn't documented. Here was my scenario:

I encountered an issue with the following code:
```php
echo Carbon::parse('2020-01-01')->addDays(null)->toDateString();
```

Carbon version: 2.41.3 (source code suggests the issue is on all 2.x versions)

PHP version: 7.2.33 (not relevant for issue)

I expected to get: `2020-01-01`

But I actually get: `2020-01-02`

This happens due to the fact that Carbon 1 would cast the null as a integer, resulting in a 0, but Carbon 2.x null coalesces the first parameter to a 1.

I'm not saying that this needs to be fixed, but rather explained. The upgrade guide from Carbon 1.x to 2.x did not explain this change, which I could consider to be a breaking change.

It's assumed here that `null` isn't passed in literally, but rather the result of some function call. The fix to keep the original functionality would be `Carbon::parse('2020-01-01')->addDays($this->myMethodCall() ?: 0)`.

This seems like an easy one-line explanation on the list of bullet points for the Carbon 2 documentation.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I agree, the documentation is open to pull-request (branch is https://github.com/briannesbitt/Carbon/tree/gh-pages and some how-to of the doc is here https://carbon.nesbot.com/contribute/docs/).

Breaking changes are watched by unit tests which cover documented usages. As `addDays()` parameter is typed `int $value` (in PHPDoc) and not `int|null $value`, this actually asserts it receives only integers. So we do not test and guarantee the behavior for `string`, `array` or any other type.

This could happen in some other places.

As `null` can have many different meanings, my general advice is to always give it an explicit value before using it.

Thanks!

**Comment by jurchiks** [comment]
If this was fixed in code, what's left to do here?

**Comment by kylekatarnls** [comment]
A bullet point could eventually be added in this list: https://github.com/briannesbitt/Carbon/blob/gh-pages/docs/index.src.html#L4959

To explain `addDays(null)` adds 0 days in Carbon 1.x and 1 day in Carbon 2.x (and the same for  `addHours(null)`, `addMinutes(null)`, etc.)

**Comment by jurchiks** [comment]
So from 2.x forwards it is supposed to be `?? 1` then? Because the `array_pad($parameters, 1, 1)[0]` change does the exact same thing, but longer and less clearly.

**Comment by jurchiks** [comment]
Actually, now that I think about it, the change to `array_pad()` has enabled the possibility of `null` being passed through. `$parameters[0] ?? 1` would have ensured that `null` would be converted to an integer, but now, if `$parameters = [null]`, then it will go in unchanged, which is likely not the desired behavior.

**Comment by kylekatarnls** [comment]
We can discuss about changing the behavior on Carbon 3 (can't change in 2.x as it would be a breaking change), but that's an other issue, and "desired behavior" is obviously a matter of need and context.

Here the point is about documenting in https://carbon.nesbot.com/docs/#api-carbon-2 the output difference for the same given code between Carbon 1.x and 2.x.

So:
- `addDays(3)` works the same,
- `addDays()` was simply not possible in Carbon 1.x so not relevant to be mentioned here in the doc
- `addDays(null)` is the only case that can actually be considered as a breaking change from 1.x to 2.x as it produces a different output.

To propose a change of behavior in Carbon 3, we should open a new issue with a usage showcase, actual vs. whished output, so we can list pros and cons for each.

**Comment by jurchiks** [comment]
My question is - why isn't the code only accepting integer values for this parameter? The type hint only allows integers, so the code should do the exact same thing, and if you pass in NULL - throw a TypeError. This is how it would be handled at the language level (strict_types = 1 after all), and we shouldn't do magic behind the scenes, that only hides problems.
For the people using this API, it's easy to add the null-coalesce with their own desired default value, thus removing any guesswork on our part.

**Comment by kylekatarnls** [comment]
If you never met anywhere else any PHPDoc mismatch, you're a very lucky person. Carbon don't use `declare(strict_types=1)` in most of the files + `addDays` is a magic method (redirecting to `addUnit` with `day` unit) so it does not have its own real signature. And all those methods are migrated from Carbon 1 (a 2012 project I was not part of at this moment) compatible with PHP 5.3 so scalar type hint like `int` simply did not exist at this epoch.

When maintaining a library used by millions on decade time-frame you can't change method signature as you wish, you need to keep a minimum backward-compatibility between minor releases and even on major release you have to make limited choices as if the gap is too high, users won't upgrade and you'll just have to maintain 2 versions as 2 completely separated libraries. I can't afford that on my own.

So to be perfectly clear, we won't add any exception thrown there in any Carbon 2.x versions.

Code refactor will be gladly appreciated if indeed it makes things more clear AND keeps the same output for any params and units.

Breaking changes in 3.x (such as throwing an exception or coming back to 1.x behavior) will be considered wisely as worthy or not.

**Comment by kylekatarnls** [comment]
> user expectation says that if you pass a `null` to an `int` parameter, it will throw a TypeError.

According to which survey?

> This code: (function (int $foo) {})(null); will throw a TypeError even without strict_types=1.

Because, `int` here is a scalar type (introduced by PHP way after PHPDoc was, and way after Carbon start using it). You make me fill like a very old person. But here is our PHP legacy. It lacked those strict types so we made libraries without it and different teams interpreted differently what `@param int $foo` should be, it's like tells `$foo param type = int`, then depending on the project, `=` took different meaning: can safely be/should be/must be/will be cast as/etc. and we couldn't wait the years it took for PHP to finally introduce it and settle the debate. Now we have the tool, it can be way better on new projects/new major versions, but I don't believe it's worth to rework everything that exist to comply to the new definition.

> Also, I am not talking about changing this in 2.x, we are clearly discussing the change you made in the 3.x branch. Yes, the ticket is named "2.x upgrade ...", but that is irrelevant because the "fix" was introduced in 3.x.

You must be mistaken, this ticket is about 1 to 2 changes documentation. And indeed, `addDays(null)` differs from 1 to 2. 3.0 is not released it's a work in progress, and it should not be handled in this issue.

**Comment by jurchiks** [comment]
> According to which survey?
According to how PHP works.

> but I don't believe it's worth to rework everything that exist to comply to the new definition.
Well, this is where I disagree. It is the current trend to make things stricter and adhere to the types as much as possible.

Yes, I know 3.x is not released, that's why it can still be changed.

**Comment by kylekatarnls** [comment]
> According to how PHP works.

So it's not "user expectation", user expectation is a not one thing, it's diversity, people using `strict_types`, people not using it, people using PHP or Laravel for a long time, people all new to it, people with background from less/more typed languages. And user diversity is one beautiful thing to care about. What I can say, is implicit cast which would convert `null` to `0` is a behavior many people are used to, and guess what, php native functions still do it silently in many places. See:

```php
declare(strict_types=1);
var_dump(round(null));
```

=> `double(0)`

That is PHP native behavior, rounding `null` makes no sense but still PHP cast it silently, so when you say it's "how PHP works" I can't agree as there is many cases it's just not what actually happen.

Doing a whole revolution everywhere every time trends pop out could be a big sacrifice of the stability of a library which actually make things usable on the long terms, make thing last and avoid abandoning many users in impossible upgrade paths.

Frankly `Carbon` could be completely rethinked in different approach and architecture, like sets of pure functions handling native `DateTime` objects instead of extending it. That's actually something I would be interested in. But this would be so different it likely no one from Carbon 2 would migrate to this version, so would better be a new library, that would get many earlier-adopters and be abandoned 1/2 years later for the new top-fashion thing. But that's simply not the `Carbon` audience, there's plenty of users I don't want to left behind, like Laravel users. Carbon < 3 users are the ones I want to support in the first place. Honestly if it results that Laravel doesn't upgrade to Carbon 3 because it introduces too many breaking changes, for me it won't be worth it.

I won't hurry nor push changes with weighting it wisely. I'll keep the upgrade effort measured.

Changing behavior or introducing new feature may represent few minutes/hours for one person to do, but then it will live in the library coming with risks of bugs, users question, documentation, maintenance burden, all to be carried 90% by me as for as Carbon is concerned. So maintaining a library is also a question about being reasonable and realistic about the available time and resources, focus on the efforts that brings the most values.

**Comment by jurchiks** [comment]
https://3v4l.org/vbPMD

It seems that my point is not getting across so this is where I'm drawing the line.

**Comment by kylekatarnls** [comment]
Guy, yes, it changed on PHP 8 which is used in production by 1% https://blog.packagist.com/php-versions-stats-2020-2-edition/

And I use PHP 8 on my personal projects with strict types everywhere, and guess what, I mostly never use `null` and have exceptions everywhere instead. So you don't have to convince me it's good thing, that's obvious. But working on a freshly new app with enough of time is not the same as working on library used by many.

The main thing you need to understand is a good thing is pointless is used by no one: *the best is the enemy of good*.

**Comment by jurchiks** [comment]
The user-land type checks were introduced before PHP 8.
It is the future, there is no going back.
That is all.
