### ISSUE TITLE
Forcing returned timezone for toDateTimeString() method

### ISSUE THREAD

**Issue by mrcnpdlk** [briannesbitt/Carbon#2224]
Hello,

I encountered an issue with the following code:
```php
date_default_timezone_set('Europe/Warsaw');
$c = new \Carbon\Carbon('2020-10-14T10:00:00.000000Z');
echo($c->toDateTimeString(). "\n");
```

Carbon version: **2.41.3**

PHP version: **7.3.23**

I expected to get:

```
2020-10-14 12:00:00
```

But I actually get:

```
2020-10-14 10:00:00
```

Is any way for method `toDateTimeString()` & `__toString()` to force the specified php timezone?
Now, I have to fix this by forcing timezone, ie:
```php
echo($c->setTimezone('Europe/Warsaw')->toDateTimeString(). "\n"); //2020-10-14 12:00:00
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

`date_default_timezone_set` is not an override to enforce the timezone everywhere, it's a default for when it's not specified. And when you have "Z", it's a specification of the timezone, so it's perfectly correct not to use the default one.

But let's go one step further and check why you actually shouldn't use `Europe/Warsaw` timezone **<u>at all</u>**
https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164
https://medium.com/@kylekatarnls/handle-dates-the-right-way-in-php-c215650fc4fa

Timezone is actually a user thing, not a server thing is to use a macro as shown in the documentation:
https://carbon.nesbot.com/docs/#user-settings

```php
// Let assume you get user settings from the browser or preferences stored in a database
$userTimezone = 'Europe/Warsaw';
$userLanguage = 'pl_PL';

Carbon::macro('formatForUser', static function () use ($userTimezone, $userLanguage) {
    $date = self::this()->copy()->tz($userTimezone)->locale($userLanguage);

    return $date->calendar(); // or ->isoFormat($customFormat), ->diffForHumans(), etc.
});

// Then let assume you store all your dates/times in UTC (because you definitely should)
$dateString = '2010-01-23 10:00:00'; // Get this from your database or any input

// Then now you can easily display any date in a page/e-mail using those user settings and the chosen format
echo Carbon::parse($dateString, 'UTC')->formatForUser();   // 23/01/2010
echo "\n";
echo Carbon::tomorrow()->formatForUser();
echo "\n";
echo Carbon::now()->subDays(3)->formatForUser();
```
[Try it in the sandbox](https://try-carbon-lib.herokuapp.com/?hide-output-gutter&output-left-padding=10&theme=tomorrow_night&border=none&radius=4&v-padding=15&input=%2F%2F%20Let%20assume%20you%20get%20user%20settings%20from%20the%20browser%20or%20preferences%20stored%20in%20a%20database%0A%24userTimezone%20%3D%20%27Europe%2FParis%27%3B%0A%24userLanguage%20%3D%20%27fr_FR%27%3B%0A%0ACarbon%3A%3Amacro(%27formatForUser%27%2C%20static%20function%20()%20use%20(%24userTimezone%2C%20%24userLanguage)%20%7B%0A%20%20%20%20%24date%20%3D%20self%3A%3Athis()-%3Ecopy()-%3Etz(%24userTimezone)-%3Elocale(%24userLanguage)%3B%0A%0A%20%20%20%20return%20%24date-%3Ecalendar()%3B%20%2F%2F%20or%20-%3EisoFormat(%24customFormat)%2C%20-%3EdiffForHumans()%2C%20etc.%0A%7D)%3B%0A%0A%2F%2F%20Then%20let%20assume%20you%20store%20all%20your%20dates%2Ftimes%20in%20UTC%20(because%20you%20definitely%20should)%0A%24dateString%20%3D%20%272010-01-23%2010%3A00%3A00%27%3B%20%2F%2F%20Get%20this%20from%20your%20database%20or%20any%20input%0A%0A%2F%2F%20Then%20now%20you%20can%20easily%20display%20any%20date%20in%20a%20page%2Fe-mail%20using%20those%20user%20settings%20and%20the%20chosen%20format%0Aecho%20Carbon%3A%3Aparse(%24dateString%2C%20%27UTC%27)-%3EformatForUser()%3B%20%20%20%2F%2F%2023%2F01%2F2010%0Aecho%20%22%5Cn%22%3B%0Aecho%20Carbon%3A%3Atomorrow()-%3EformatForUser()%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Demain%20%C3%A0%2002%3A00%0Aecho%20%22%5Cn%22%3B%0Aecho%20Carbon%3A%3Anow()-%3EsubDays(3)-%3EformatForUser()%3B%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20mercredi%20dernier%20%C3%A0%2016%3A40%0A&token=live-editor-160)

This way you actually can link later `$userTimezone` to a dynamic value that actually take user settings (IP, cookie or any kind of location-guessing) into account and use `date_default_timezone_set('UTC');` on the server-side which gives you a universal and correct way to exchange and store dates with other systems, deploy your application anywhere in the world consistently scale to I18N, reuse the code, etc.

Thanks.

**Comment by kylekatarnls** [comment]
And if there is context, it's not your default timezone.

Either you have date with variable timezone (from the user for instance) so you have to store both datetime and user timezone alongside, or you represent moments and the proper way to store them in a DB is UTC.

Your system should be agnostic to the location where company is, where server run or any world location, it does not need it. For scalability sake, it should be able to be reused, chunked or moved within other locations, deployed elsewhere, interact with other systems. To achieve that we use the UTC as the standard way to exchanges dates machine-side.

**Comment by kylekatarnls** [comment]
Last you can go with any `->format('Y-m-d\TH:i:sP')` for instance which will output `+01:00` or `+02:00` in your case (because yes, it's not consistent, there is DST in Paris that will brings you many bugs by the way when using such timezone as the default).

And I'm 100% we won't change standard functions (they match the ISO8601 recommendations) and Zulu = UTC

Having a custom `->format()` is the right way because it will make everyone reading the code aware it's custom and actually not the standard purpose of the other functions above.
