### ISSUE TITLE
createFromTimestampUTC Not Throwing Exception

### ISSUE THREAD

**Issue by nickescobedo** [briannesbitt/Carbon#2230]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromTimestampUTC('2010-10-10 11:11:11')->startOfDay();
```

This used to throw exceptions in previous versions. Upgraded from `2.40.0` to `2.41.3` and noticed it was no longer throwing exceptions.

Carbon version: **2.41.3**

PHP version: **7.4**

I expected to get:

```
InvalidArgumentException
```

But I actually get:

```
1970-01-01 and no errors in getLastErrors

Carbon\Carbon Object &0000000040087f57000000002e4d839c (
    'constructedObjectId' => '0000000040087f57000000002e4d839c'
    'localMonthsOverflow' => null
    'localYearsOverflow' => null
    'localStrictModeEnabled' => null
    'localHumanDiffOptions' => null
    'localToStringFormat' => null
    'localSerializer' => null
    'localMacros' => null
    'localGenericMacros' => null
    'localFormatFunction' => null
    'localTranslator' => null
    'dumpProperties' => Array &0 (
        0 => 'date'
        1 => 'timezone_type'
        2 => 'timezone'
    )
    'dumpLocale' => null
    'date' => '1970-01-01 00:00:00.000000'
    'timezone_type' => 1
    'timezone' => '+00:00'
)
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

According to [our versioning policy](https://github.com/briannesbitt/Carbon/blob/master/contributing.md#versioning), exceptions may disappear in favor of new features introduced in minor versions.

Since 2.41.0, [createFromTimestampUTC() supports strings containing one or more numbers](https://github.com/briannesbitt/Carbon/pull/2205). It considers them as a composite string and sums up the numbers inside.

Input sanitization is the application responsibility.

You can do an equivalent check using `if (is_numeric($value))`

Thanks.
