### ISSUE TITLE
🌎 nl_NL format L output

### ISSUE THREAD

**Issue by twitnic** [briannesbitt/Carbon#2232]
Hello,

I encountered an issue with the following code:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/nl_NL.php

The first line prints: 10-10-1980
The second: 10-10-80

Why its a difference between 'nl' and 'nl_NL'?
In other language like German is no difference between short version de and de_DE.

```php
$birth = '1980-10-10';


$mutable = Carbon::createFromFormat('Y-m-d', $birth);
echo $mutable->locale('nl')->isoFormat('L');
echo $mutable->locale('nl_NL')->isoFormat('L');
```

Carbon version: **2.38 -> master**

PHP version: **7.3**

**Comment by kylekatarnls** [comment]
Hi,

The 822 different locale files was not created by a single person knowing all those languages and regions. Translations have been imported from different sources considered reliable to fulfill the lacks and are progressively fixed by the community.

Historically nl is from momentjs: https://github.com/moment/moment/blob/develop/locale/nl.js#L69 in which you can find YYYY
And nl_NL is from cldr http://cldr.unicode.org/ in which you can find YY

As language and region are different things (en_EN does not exist, you may have en_US, en_GB, etc. and "en" language is not an exact match of any of the regions, it's called international English). And while a given country may be the reference for a given language, this is not an absolute rule. Because an xx_XX locale exists with the same code as region and language is not enough to say xx locale is an exact match of xx_XX.

So we did not enforce every existing locale to change accordingly to locales imported from CLDR or else. This would have require to check official rules of each language where it happens to be sure the new translations are more correct than the existing one (and to be sure a short locale matches the region with the same code).

For this particular case, regarding nl regions (AW, BE, BQ, CW, NL, SR, SX) it makes sense that NL is the country of reference for the language. So we can align nl and nl_NL and ensure other regions are not affected by the change.

Still I don't know myself which one is the correct one according to Dutch official rules.

**Comment by twitnic** [comment]
Hey and thanks for your answer.

I know that language and locale are difference. That was the reason, that i used German with 'de' as an example an not 'en'.
I was just surprised, because up to now I was shown a 4-digit year in format L. And that was not the case with nl_NL.

And on Wikipedia there are also 4 digits:
https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_Netherlands

**Comment by kylekatarnls** [comment]
Indeed and it's consistent with other region and other neighboring countries, so let's use YYYY for nl_NL. It will be applied on the next version.

Thanks.
