### ISSUE TITLE
How to set start and end of the week globally after setWeekStartsAt, setWeekEndsAt are depracated?

### ISSUE THREAD

**Issue by MrEldin** [briannesbitt/Carbon#2234]
Hi, 

Thank you for this great library. 

In my application, I had a place in service provider where I set Start Of Week and End Of Week globally. Everything worked well before these two functions are deprecated (setWeekStartsAt, setWeekEndsAt), can anyone help me, how to do this again without these two functions?

I tried:
```
CarbonImmutable::now()->startOfWeek(Carbon::TUESDAY);
CarbonImmutable::now()->endOfWeek(Carbon::MONDAY);
```

Also:
```
$en = CarbonImmutable::now()->locale('en_US');

$start = $en->startOfWeek(Carbon::TUESDAY);
$end = $en->endOfWeek(Carbon::MONDAY); 
```

And it's not working actually. The object is changed but I need a global solution. Where after I set it once, every time after that when I am using `Carbon::now()->startOfWeek()` anywhere in the project I want to get Carbon::TUESDAY.

Is that even possible now, or I have to change it all over the app?

Thanks in advance.

**Comment by kylekatarnls** [comment]
Hi,

It's not working because "not doing it globally" is actually the whole point of the deprecation as per the deprecation notice:

```
To avoid conflict between different third-party libraries, static setters should not be used.
Use $weekEndsAt optional parameter instead when using endOfWeek method. You can also use the
'first_day_of_week' locale setting to change the start of week according to current locale
selected and implicitly the end of week.
```

This will likely not disappear in Carbon 3.0, the removal will likely be postponed to the 4.0 version. But let's explain why setting globally the week start/end is dangerous.

First of all, the definition of a week should be bound the the localization. For instance, we can imagine creating custom locales en_US@Cinema having weeks from Friday to Thursday (and so the same for other countries fr_FR@Cinema from Wednesday to Tuesday, etc.).

```php
\Carbon\Translator::get('en_US@Cinema')->setTranslations([
  'first_day_of_week' => Carbon::FRIDAY,
]);

\Carbon\Translator::get('fr_FR@Cinema')->setTranslations([
  'first_day_of_week' => Carbon::WEDNESDAY,
]);

echo CarbonImmutable::now()->locale('fr_FR')->startOfWeek()->dayName . "\n";
echo CarbonImmutable::now()->locale('fr_FR@Cinema')->startOfWeek()->dayName . "\n";
echo CarbonImmutable::now()->locale('en_US')->startOfWeek()->dayName . "\n";
echo CarbonImmutable::now()->locale('en_US@Cinema')->startOfWeek()->dayName . "\n";
```
And so endOfWeek() is calculated automatically.

The same way a locale "en_US@MySpecificBusiness" can be added.

Then you can generate Carbon instances from a factory (as shown in https://carbon.nesbot.com/docs/#api-localization) so the instances from the factory will all be create with "en_US@MySpecificBusiness" as the default locale.

You can (but shouldn't) directly override "en_US" `first_day_of_week` key. You shouldn't simply because it would be a lie. The first day of week commonly used in en_US is Sunday. And that's what every services and libraries you may use/install in your app will expect to get when requesting "start of week" for en_US.

And the reason not to use `setWeekEndsAt` is the same. If you need a library "foo" relying `getWeekStartsAt()` to return Monday (which is the only "global" start of week following ISO 8601 standard), the library won't work properly with week start being customized. And customization should have a limited scope. For instance: application-level dates, when scoped to only dates you have control over, all sub-dependencies of your app/framework you may not be aware of are no longer impacted.

Last thing to consider is: if it's not commonly called "week" (start/end) neither in your organization nor in any country, then week start/end are just not the right tools, then if this case, you should consider give it a proper name and dedicated macro methods. For instance, imagine a development sprint is started every Wednesday:

```php
Carbon::macro('startOfSprint', static function () {
  return self::this()->startOfWeek(Carbon::WEDNESDAY);
});
Carbon::macro('endOfSprint', static function () {
  return self::this()->endOfWeek(Carbon::TUESDAY);
});
Carbon::parse('2020-11-09')->startOfSprint();
```
This gives you more explicit methods matching the actual meaning while letting start/end Of Week available for what is actually the week (and likely it can happen in a business where Tuesday is the default start of a certain period that the regional or ISO start of week may be needed later in an other feature).

Thanks.

**Comment by MrEldin** [comment]
Thank you for your response, I wanted to give a user total control of which day of the week will be end of the week, so that is the reason why I wanted it to be globally set in one place but I totally understand why this has had to happen.

I am going with the `macro` solution, it will do the job.

Thank you.

**Comment by beard7** [comment]
I love explanations that tell you why you shouldn't do something, even though it has worked perfectly up to now. Especially when the option to do it is being removed and not replaced with anything. 

Just because using setWeekStartsAt and setWeekEndsAt are a bad idea, why prevent me from using it when it does EXACTLY what I need and there is no alternative?
