### ISSUE TITLE
PHP8?

### ISSUE THREAD

**Issue by omexlu** [briannesbitt/Carbon#2253]
Hello,

I wanted to ask if the current version is compatible with PHP8 and if not for when that is expected to be the case?

Thanks in advance.

**Comment by kylekatarnls** [comment]
Hello, you can check the compatibility of any composer package using composer CLI or packagist:
https://packagist.org/packages/nesbot/carbon

It refers to our compsoer.json file:
https://github.com/briannesbitt/Carbon/blob/master/composer.json#L31

Which you also can annotate ("Blame" button) to check history of a given line and so can see which tags include the commit:
https://github.com/briannesbitt/Carbon/commit/fc74a02985613a66f80827a6afb8943f2a2f9d75

In this case [1.37.0](https://github.com/briannesbitt/Carbon/releases/tag/1.37.0) enabled PHP 8 at its very alpha stage 18 months ago.

And we run the full test suites on 8.0 and 8.1 to ensure 100% of our code properly on on PHP 8 since:
https://github.com/briannesbitt/Carbon/runs/1536765631

Thanks.
