### ISSUE TITLE
PHPDoc @property-write with @property-read on a same property causes IDE Warning (PhpStorm)

### ISSUE THREAD

**Issue by gaomd** [briannesbitt/Carbon#229]
This PHPDoc block ([#L47](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L47-L50)):
```
 * @property-read  DateTimeZone        $timezone the current timezone
 * @property-read  DateTimeZone        $tz alias of timezone
 * @property-write DateTimeZone|string $timezone the current timezone
 * @property-write DateTimeZone|string $tz alias of timezone
```
Causes error in PhpStorm 8.0.1 (`Field with same name already defined in this class`):

![screen shot 2014-12-01 at 17 45 25](https://cloud.githubusercontent.com/assets/113737/5243700/e28cf53c-7981-11e4-8176-3b261438c93e.png)

After checking the documentation of [`@property-read`](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/property-read.html) and [`@property-write`](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/property-write.html), there seems no restriction on whether it's ok to use both on the same class property.

What you guys think? Should we merge these two properties to `@property` (which is not optimal since they have different type) or report this "bug" to PhpStorm?

**Comment by MalikinSergey** [comment]
@briannesbitt @lucasmichot @gaomd
Hi, sorry about take attention in closed issue.

phpDocumentor says, that 
>The @property-read tag is used in the situation where a class contains the __get() magic method and allows for specific names that are not covered in a __set() magic method
and this rule is not respected in this doc block. It's reason, that IDE (storm) show error, and it's not is bug.

On other hand, I can't imagine, in what situation doc like

```php
 * @property DateTimeZone|string $timezone the current timezone
 * @property DateTimeZone|string $tz alias of timezone
```

can make any problems for IDE type-hint, or in any other case.

Maybe when you declare function with `@param string` doc block, then try to pass $carbon->timezone to it - IDE should show type error, if `* @property-read  DateTimeZone`? PhpStorm don't show, although I have not checked other IDE, but sure that same. It's because IDE suggets, that object can can be casted `__toString()`, as I mean. So, there is no proplem to merge to property (read, write) declaration in one.
