### ISSUE TITLE
Any date in the month 'is' the first day of the month

### ISSUE THREAD

**Issue by randyclassen** [briannesbitt/Carbon#2295]
Hello,

I encountered an issue with the following code:
```php
Carbon::parse('2021-03-02')->is('1 March 2021'); // true
Carbon::parse('2021-02-28')->is('February 1 2021'); // true
```

Looks like any day in a month `is` the first of that month.

Carbon version: 2.41.5

PHP version: 7.4

I expected to get:

```
false
```

But I actually get:

```
true
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

It's actually an edge-case that will only occur with the 1st of the month, because once created using `new DateTime("the string")` unless we reapply our own parsing on the initial string we won't know what was the expected precision so if time is 00:00:00 we assume it's day-precision, if it's the 1st of the month at midnight, we assume it's month-precision.

In this case: `Carbon::parse('2021-03-02')->is('3 March 2021')` is `false` while `Carbon::parse('2021-03-02')->is('2 March 2021')` is `true`, then `Carbon::parse('2021-03-02')->is('1 March 2021')` is understood as `Carbon::parse('2021-03-02')->is('March 2021')` and so it's also `true`.

To be honest, this feature was not designed to receive a free user input or a dynamic value (inside the `->is()` parameter), it's rather intended as a shortcut for static checking.

If you know in advance you always want day-precision, then `isSameDay` is a better fit:

```php
Carbon::parse('2021-03-02')->isSameDay('1 March 2021'); // true
Carbon::parse('2021-02-28')->isSameDay('February 1 2021'); // true
Carbon::parse('2021-03-02')->isSameDay('2 March 2021'); // true
Carbon::parse('2021-02-28')->isSameDay('February 28 2021'); // true
```

**Comment by randyclassen** [comment]
Thanks, we ended up on `isCurrentDay` for what we needed. There is an example for `is` in the docs that may benefit from this precision disclaimer, but there are definitely multiple options for doing what we needed to do. Thanks for the explanation!
