### ISSUE TITLE
Carbon::parse dumps an E_WARNING error when it fails

### ISSUE THREAD

**Issue by mithredate** [briannesbitt/Carbon#2297]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('dummy');
```

Carbon version: **2.41**

PHP version: **7.4.4*

I expected to get:

```
Carbon\Exceptions\InvalidFormatException with message 'Could not parse 'dummy': DateTime::__construct(): Failed to parse time string (dummy) at position 0 (d): The timezone could not be found in the database'
```

But I actually get:

```
<warning>PHP Warning:  DateTime::modify(): Failed to parse time string (dummy) at position 0 (d): The timezone could not be found in the database in /var/www/vendor/nesbot/carbon/src/Carbon/Traits/Modifiers.php on line 434</warning>
Carbon\Exceptions\InvalidFormatException with message 'Could not parse 'dummy': DateTime::__construct(): Failed to parse time string (dummy) at position 0 (d): The timezone could not be found in the database'
```

I've drilled down the problem and it's due to the `@` used in `\Carbon\Traits\Creator::rawParse`. Using error suppression by `@` can have unintentional side-effects, like the one discovered here. There's an alternative solution to use [set_error_handler](https://www.php.net/manual/en/function.set-error-handler.php) and throw an exception on failure.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

This is the known and expected behavior as it's how the `DateTime::modify()` method works and we can't know in advance if it will fails. You would get the same with pure PHP `new DateTime('dummy')`.

As we have no control over rather [the PHP native DateTime::modify() method](https://www.php.net/manual/en/datetime.modify.php) should fail with an exception or a warning, then using `set_error_handler` to throw an exception for any error is the way to work on those.

And this apply for all the errors of PHP, this is not a Carbon-specific issue. And actually it's like any invalid input `new DateTime([])`, you get a TypeError, not an exception. So I recommend you always turn error into exceptions using `set_error_handler`.

I always work with such settings and for Carbon feature/behavior, I'll assume either you have such setting to make PHP errors catchable or you validate input in order to not trigger such errors. But wrapping every possible errors PHP could raise to throw exceptions instead would not make much sense.

Thanks.

**Comment by kylekatarnls** [comment]
Last note: set_error_handler is a global override, so it's not up to libraries to call it, it needs to be at application-level.

**Comment by lptn** [comment]
@kylekatarnls 
@mithredate 

>Last note: set_error_handler is a global override, so it's not up to libraries to call it, it needs to be at application-level.


Let me explain the idea in details:
1. we set our custom error handler to throw exceptions on E_WARNING
2. we run dangerous code (`rawParse` in our case) inside try catch
3. we revert an original error handler using `restore_error_handler`

The same approach I used for this PR: https://github.com/egulias/EmailValidator/pull/286, where such dangerous code  was `dns_get_record()`


We can also replace `@` to this approach here: https://github.com/briannesbitt/Carbon/blob/5853493c508b5095486b335c7ced7450dc57affa/src/Carbon/Traits/Creator.php#L185 (it's more safe and probably even faster, see https://derickrethans.nl/five-reasons-why-the-shutop-operator-should-be-avoided.html)

**Comment by mithredate** [comment]
@kylekatarnls Can you please share your thoughts regarding what @lptn suggested above?

**Comment by kylekatarnls** [comment]
Adding `restore_error_handler` to `set_error_handler` is indeed a way to scope it and avoid the lib to break other handlers. Still dealing with upper settings (that does not belong to library responsibility) is risky: if you have multiple similar hack nested and anything goes wrong in the middle, you may have not have 1 successful `restore_error_handler` call for each `set_error_handler` while `@` is guaranteed to be self-contained.

Other points to be analyzed:
- Why `parse()` and not all other method that can trigger PHP errors with some invalid inputs (we extends `DateTime`, `DateInterval` etc. so we likely can have hundreds of similar situations)? What makes `parse()` relevant to be handled differently?
- If `parse()` is not a special case, it means we have a lot of place to update and deep test. It can also bloat a bit the code source and make it more difficult to read.
- "probably even faster", I don't take into consideration such intuitions but I would consider any proof of such performance improvement. If it improves significantly performance for both cases (the case you use default PHP error output and the case you turn errors into exceptions), and safety requirement above is also met, then, I would be glad to merge then apply to other relevant places. Note: the article is about `@` vs. nothing which is obviously slower, but it does not mean `restore_error_handler + set_error_handler` will be faster.
- Consider if it's worth the effort. Most frameworks convert error into exception by default and this is a widely common standard. Many other libraries assumes this state so the point is to check what other libraries do. Using `restore_error_handler` hack is clearly a pretty rare thing. And most just let PHP error happen for many invalid input handling. So it would not be too useful for Carbon to behave specifically if all other libraries around still let PHP errors as is and if it's only to support an edge-case app setting.

An other important thing:

This issue (your original message) is about wanting an exception over an error while you didn't turn errors into exception. This would not be relevant IMO. `InvalidFormatException` is here to wrap generic exception into a identified kind of exception. But if there is no exception (because settings raise standard error or because muted by the reporting level), I don't see any reason to create a Carbon exception.

About the specific case of validation (https://github.com/laravel/framework/issues/36138), you would get the same failure using `DateTime` so it's not a Carbon issue. If the validation is supposed to throw error if a PHP error happen, then it's clearly up to the validator to implement it as it can happen with many other kind of validations. If you want a `boolean` response, then you can get it using:
```php
try {
  $isValid = !!@Carbon::parse('anything');
} catch (\Carbon\Exceptions\InvalidFormatException $e) {
  $isValid = false;
}

var_dump($isValid);
```

Which would work with both error turned into exception or not.
