### ISSUE TITLE
Travis CI failing because of uncommitted changes

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [briannesbitt/Carbon#2303]
Hello,

I encountered an issue when deploying my app to Travis CI:

```
  [RuntimeException]                                                           
  Source directory /home/travis/build/vendor/nesbot/carbon has uncommitted changes.  
```

Carbon version: 2.46.0

PHP version: 7.3

I expected to get Travis CI to finish installation of my composer dependencies and move onto my PHPUnit tests. Instead it stopped saying carbon has "uncommitted changes"?

Why is this?

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I have plenty of projects having carbon installed in it running on different CI platform including Travis CI.

If it would be a problem from Carbon itself, we would surely have many reports, but this is the first one. So this is probably something happening only in a particular situation.

Here we miss a lot of information to investigate, first the code/command used (your .travis.yml, mostly the composer install/update commands).

Then since composer tells you have uncommitted changes, you should check what are those changes made so it might help you to guess what script made those change in the library.

So debug your travis script adding:
```
cd /home/travis/build/vendor/nesbot/carbon && git status
```

Thanks.

**Comment by kylekatarnls** [comment]
I will re-open the issue it needed details can be provided. For now I close it as not possible to investigate further.

**Comment by JohnnyWalkerDesign** [comment]
It was a caching issue in Travis CI. Clearing the caches fixed the problem.
