### ISSUE TITLE
Parse from format without day of month

### ISSUE THREAD

**Issue by vasichmen** [briannesbitt/Carbon#2310]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromFormat('m.Y', '02.2021')->month
```

Carbon version: 2.46.0

PHP version: 7.3.19

I expected to get:

```
2
```

But I actually get:

```
3
```
this is because if only the month and year are specified.
Today is March 30 then carbon takes a day from the current date, and February 2021 has only 28 days. Therefore, the extra days are added and I get March 2.

Thanks!

**Comment by kylekatarnls** [comment]
Hello, 👋 

`createFromFormat` actually completely rely on the native PHP behavior:
https://www.php.net/manual/en/datetime.createfromformat.php

You likely need the `!` (reset) operator:
```php
echo Carbon::createFromFormat('!m.Y', '02.2021')->month
```

`!` mean instead of getting current value for other not mentioned units (in your case getting day = 30 because now is 30th), you'll get minimum values (day = 1, hour = 0, etc.)
