### ISSUE TITLE
Missing translation for ordinal suffix

### ISSUE THREAD

**Issue by Naghal** [briannesbitt/Carbon#2320]
Hello,

I encountered an issue with the following code:
```php
Carbon::setLocale('fr');
\Carbon\Carbon::parse('2021-01-15')->format('dS')
\Carbon\Carbon::parse('2021-01-15')->format('jS')
```

Carbon version: **2.46.0**

PHP version: **7.4.3**

I expected to get:

```
15e
```

But I actually get:

```
15th
```

https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=Carbon%3A%3AsetLocale(%27fr%27)%3B%0A%24date%20%3D%20Carbon%3A%3Aparse(%272021-04-15%27)%3B%0Aecho%20%24date-%3Elocale().PHP_EOL%3B%0Aecho%20%24date-%3Eformat(%27jS%27)%3B

The `th` should be translated to french version `e`.

Thanks!

**Comment by kylekatarnls** [comment]
Hello, 👋 

Not with `format()`. As per [documentation](https://carbon.nesbot.com/docs/#api-localization) `format()` is not localized (it's all English for day name, month name, ordinal etc.) to be compatible with the inherited `DateTime::format` method.

You need `->translatedFormat('jS')` or `->isoFormat('Do')` to get translation for any of the date string format code.

Side note, there is no ordinal in french unless for `1` => `1er` for `premier`, `1re` for `première`, but there is ordinal for any other number as per official grammar.

The reason is we say : "Permier mai", but we don't say "Second mai", we say "Deux mai", ordinal disapears.

Thanks.
