### ISSUE TITLE
infinite loop in calculateEnd() if end is null

### ISSUE THREAD

**Issue by jonaslm** [briannesbitt/Carbon#2324]
Hello,

I encountered an issue with the following code:
```php
echo CarbonPeriod::create('2018-06-01', null)->calculateEnd();
```

Carbon version: 2.27.0

PHP version: 7.4.1

I expected to get:

```
null
```

But I actually get:

```
an infinite loop
```

Specifically, I encountered this issue when trying to make an `->overlaps()` check between periods where one period was missing an end (expecting to get a trivial `true` as a result).

Thanks!

**Comment by kylekatarnls** [comment]
Hello, 👋 

It sounds very dangerous to choose arbitrary `true` or `false` for `->overlaps()` result when one of the period has no end.

Expected behavior here shouldn't be `null` clearly, it should throw an exception anyway.

Basically `calculateEnd()` gives you `getEndDate()` or `start + recurrences * interval` (if recurrences is specified).

If neither end not recurrences is specified, this is not a period, it's an incomplete/broken object and nothing relevant would be good to be calculated with this.

We can have better response than infinite loop, but the correct response in this case will be some:
```php
throw new RuntimeException('Unable to calculate period end');
```
then it would be up to the business logic to decide what a period without end would mean, because from date and time perspective it does not make sense.

If you try to represent a "forever", just take a far date:
```php
$endOfTime = Carbon::parse('9999-12-31');
echo CarbonPeriod::create('2018-06-01', $endOfTime)->overlaps(...);
```

Thanks.

**Comment by jonaslm** [comment]
I understand your logic for implementing it this way. We just have some "periods" that *may* be open-ended, yet we still need to check overlap between them (despite what I said earlier, an open-ended period doesn't necessarily overlap with a close-ended period - the close-ended period may end before the open-ended one starts after all). We'll just handle that case manually, it's fine. 👍 

Thank you for your work!

**Comment by kylekatarnls** [comment]
The next version (2.48.0) will:
- contains special dates objects to represent start and end of time,
- allow to use `INF` as a number of recurrences for a period (see the examples in unit tests of the PR: https://github.com/briannesbitt/Carbon/pull/2325/files#diff-fdc87d7a7113ab770f3cb72bc0858973954dc61ec87e98e5f1f182f8abd69592R155)
- throw an exception if the end of a period is not found after 10000 loop turns
- optimize the way to find the end first:
  - throw an exception if both recurrences and end are `null`
  - use explicit end if specified (as before)
  - use start date if interval is empty (just for safety, period with empty interval are not intended to work properly)
  - use start of time if recurrences is `INF` and interval is negative
  - use end of time if recurrences is `INF` and interval is positive
  - use recurrences * interval if there is no custom filter
  - fallback to iterating the whole period for other cases

You can test it with `^2@dev` version.
