### ISSUE TITLE
Strict instantiation method with time

### ISSUE THREAD

**Issue by spawnia** [briannesbitt/Carbon#2329]
I am looking for a strict way to instantiate a Carbon instance for a statically known date. My current code looks like this:

```php
Carbon::create(1997, 12, 8, 8, 56, 20);
```

We have recently increased the level of strictness in our static validation tool. Using the result of the above call now gives me an error, because apparently `Carbon::create()` can return `false`: https://github.com/briannesbitt/Carbon/blob/d3c447f21072766cddec3522f9468a5849a76147/src/Carbon/Traits/Creator.php#L365-L367

I have switched to `Carbon::createFromDate()` in cases where the time is not relevant, but have not found an equivalent method that allows me instantiate a date with time. None of the other methods for instantiation do exactly what I want. I guess I could use the constructor, but that would invite possible format errors.

Could we add a strict specialization of `create`? Perhaps like this:

```php
    /**
     * @throws InvalidFormatException
     */
    public static function createStrict(int $year = null, int $month = null, int $day = null, int $hour = null, int $minute = null, int $second = null, $tz = null): static
    {
        return static::create($year, $month, $day, $hour, $minute, $second, $tz);
    }
```

**Comment by kylekatarnls** [comment]
Hello 👋 Can you check if solutions provided in #2135 (useStrictMode(), macro, or `@var` annotation) can help?

**Comment by spawnia** [comment]
Hey, it has been a while since we last talked 👋

Thanks for the swift response. Great discussion in that issue! I attempted to look for existing issues but apparently missed that one.

`useStrictMode()` definitely aligns with my preferences in regards to error handling (it looks like `settings()` should be used instead now). I will definitely look into enabling that in our project. However, while it does change the behaviour, it has no impact on static analysis. Perhaps a fancy PHPStan extension might solve that?

The `@var` type assertion is certainly a possible workaround and one that I considered as well. I view it as kind of a last resort though, as it can be quite harmful when refactoring. We tend to use them sparingly, and have a rule that they must be accompanied by a descriptive comment that justifies its use. Given we have hundreds of calls to `Carbon::create()` throughout our codebase, I am not too keen on converting them all to this.

I do like the macro solution. It seems that we have independently come up with `createStrict()`, that indicates to me that this method would be generically useful for many users. Would you be open towards a PR that adds it?

**Comment by kylekatarnls** [comment]
`useStrictMode()` is global, so the risk as all the global setters we have in Carbon is that it applies to all `Carbon` instances even the one a sub-dependency of your project you don't suspect may create. It's likely not to cause harm but if one of the package in your vendor does something like:
```php
$date = Carbon::parse('can contain broken string');

if ($date) {
  return $date->format('Y-m-d');
}

return 'default';
```
Then, `useStrictMode(true)` will make it throw an exception too while possibly this package expect the failed parsing to simply return `false`. It's the reason for `useStrictMode()` deprecated but actually when we'll remove it, strict mode will very likely be the only mode.

Sure there is a demand for this method. My hesitations comes from:
- Adding stuff (except comments) only to please static analyzer tools tends to bloat the lib without concrete benefit
- Hopefully one day (depends on available time and having some guarantees frameworks would upgrade to the next major version), `create()` itself and every possible methods will throw exception rather than returning false/null. But it also means all the "strict" methods would become pointless (as same as the default), so we'll likely deprecate then remove, meaning if you replace now create to createStrict you'll have to do the reverse at this point when upgrading to 3.0 or 4.0.
- returning `false` for errors is still actually the native PHP behavior for many functions in date field (`date_create()`, `DateTime::createFromFormat()`) and other fields (`strpos()`, `fopen()`, `scandir()`, etc.) so as we have many methods returning the result of such functions calls, I suspect we have several ones with the same pitfall and would have to add a `fooBarStrict()` for each of them to be consistent.

But else, I quite favorable to add it in the core library.

**Comment by spawnia** [comment]
I definitely see your concerns and think they are completely valid. Some considerations on your points:

1. In this case there is an actual behavioural change. Code that might fail silently with `create()` will now properly abort and report an actual error.

2. There is value in having both methods for a transition period. It allows users to gradually introduce usage of `createStrict()`. Given `create()` will default to the strict behavior in v3, deprecating `createStrict()` then and removing it in v4 seems sensible.

3. Even PHP core is slowly moving away from this behavior, and projects such as https://github.com/thecodingmachine/safe are reasonably popular. I would very much welcome having a strict version of currently unsafe methods.
