### ISSUE TITLE
diffInMonths return wrong result

### ISSUE THREAD

**Issue by mtctonyhkhk2010** [briannesbitt/Carbon#2394]
Hello,

I encountered an issue with the following code:
```php
echo Carbon\Carbon::parse('2021-01-01')->startOfMonth()->diffInMonths(Carbon\Carbon::parse('2021-07-01'));
```

Carbon version: 2.50.0

PHP version: 8.0.7

I expected to get:

```
6
```

But I actually get:

```
5
```

While floatDiffInMonths return 6.0 which is correct.

```php
echo Carbon\Carbon::parse('2021-01-01')->startOfMonth()->floatDiffInMonths(Carbon\Carbon::parse('2021-07-01'));
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

When trying your code in https://try-carbon.herokuapp.com/ I get 6. I guess you use a timezone having a DST transition in between (`Europe/Paris` for instance), which means you actually get 6 months - 1 hour (due to PHP bugs that should be fixed in PHP 8.1) and `diffInMonths` currently returns the integer rounded down.

You can simply get rid of it with:
```php
echo Carbon::parse('2021-01-01')->utc()->diffInMonths(Carbon::parse('2021-07-01')->utc());
```

But my very recommendation is to use UTC everywhere as the default in your back-end, DB, php.ini, Laravel config, etc.

As this will be fixed in PHP 8.1 and as Carbon 3.0 will return float right from `diffInMonths()` we won't change this behavior in Carbon 2.x.

Thanks.
