### ISSUE TITLE
CreateFromFormat unexpected parse

### ISSUE THREAD

**Issue by fiCeVitka** [briannesbitt/Carbon#2436]
Hello,

I encountered an issue with the following code:
```php
$date = Carbon::createFromFormat('Ym', 202102);
echo $date->month;
```

Carbon version: 2.52.0

PHP version: 7.4

I expected to get:

```
2
```

But I actually get:

```
3
```

Thanks!

**Comment by fiCeVitka** [comment]
I think the reason is that today is the 30th, and in February there are only 28 days

**Comment by kylekatarnls** [comment]
Hello,

`createFromFormat` does not belongs to `Carbon`, it's inherited from `DateTime` with the exact same behavior:
```php
echo DateTime::createFromFormat('Ym', 202102)->format('n'); // 3
```

As explained in the PHP doc: https://www.php.net/manual/en/datetime.createfromformat.php you need `!` to "Resets all fields" (use minimum value instead of current ones):
```php
echo DateTime::createFromFormat('!Ym', 202102)->format('n'); // 2
```

And so the same goes for Carbon:
```php
echo Carbon::createFromFormat('!Ym', 202102)->month;
```

Thanks.
