### ISSUE TITLE
Adding a DateInterval overflows the unit, regardless.

### ISSUE THREAD

**Issue by DarkGhostHunter** [briannesbitt/Carbon#2458]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::create(2021, 1, 31)
    ->settings(['monthOverflow' => false])
    ->add(CarbonInterval::create(0, 1), overflow: false);
```

Carbon version: 2.53.1

PHP version: 8.0.10

I expected to get:

```
2021-02-28 23:59:59.000
```
(as it should add a month with no overflows)

But I actually get:

```
2021-03-03 00:00:00.000
```
(adds a month **with** overflow)

**Comment by kylekatarnls** [comment]
Hello, 👋 

Indeed, it's not possible with intervals. The reason is that `monthOverflow = false` does not actually prevents overflow (because overflow already happened inside the inherited [DateTime::add](https://www.php.net/manual/en/datetime.add.php) and we fix it: return to last day of previous month.

We can't do it with intervals because they can be composite, e.g. 1 month + 15 days, so we don't have a way to apply overflow, unless we split the units and proceed in multiple steps. It would cost a lot for minimal benefit as we usually want the overflow fix only for differences that are an integer number of months.

You can do:
```php
echo Carbon::create(2021, 1, 31)
    ->add(1, 'month', overflow: false);
```
Or:
```php
echo Carbon::create(2021, 1, 31)
    ->settings(['monthOverflow' => false])
    ->add(1, 'month');
```

We could maybe detect that an interval is a pure-months interval and proceed the overflow, but then it would lead to inconsistencies between "X months" and "X months + Y days" results. So I don't think we should take this path.

Last point, in case of disabled overflow, you wont have `23:59:59` but `00:00:00`.

Thanks.

**Comment by kylekatarnls** [comment]
Here is what you could do following the principle above:

```php
Carbon::macro('addNoOverflow', static function (CarbonInterval $interval) {
  $date = self::this();
  $months = $interval->months;
  $interval->months = 0;

  if ($months) {
    $date = $date->addMonthsNoOverflow($months);
  }

  return $date->add($interval, overflow: false);
});

echo Carbon::create(2021, 1, 31)->addNoOverflow(CarbonInterval::create(0, 1));
echo Carbon::create(2021, 1, 31)->addNoOverflow(CarbonInterval::create(0, 1, 0, 4));
```
