### ISSUE TITLE
Using carbon parse on just a year behaves differently on years <2000 -- y2k bug ;-)

### ISSUE THREAD

**Issue by jimmypuckett** [briannesbitt/Carbon#2469]
Hello,

I encountered an issue with the following code:
```php
// Seems to ignore any year greater than or equal to 2000, and default's to 2021
echo Carbon\Carbon::parse("2000")->toString()
```

Carbon version: 2.53.1

PHP version: tried 8.0.9 & 8.0.10

I expected to get:

```
"Thu Sep 30 2000 20:00:00 GMT+0000"
```

But I actually get:

```
Thu Sep 30 2021 20:00:00 GMT+0000
```

I got the same error on `try-carbon`

NOTE: Years less than 2000 work

```php
// Works as expected
echo Carbon\Carbon::parse("1999")->toString()
"Thu Sep 30 1999 01:45:40 GMT+0000"
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello 👋 

This is the behavior from native PHP `DateTime`:
https://3v4l.org/9SMaS

We don't want to do anything fancy trying to smartly guess what a number alone in string means. So here we just inherit from parent constructor.

I'm not even sure we should qualify this as a bug even in PHP's scope, because it's actually quite ambiguous (it can be a timezone minutes shift, a timestamp etc.), and you can just use `1999-01-01` and `2000-01-01` to make it clear and explicit. But you can still try to report it on https://bugs.php.net/.

Thanks.
