### ISSUE TITLE
setTestNowAndTimezone not changing timezone when timezone type is UTC offset

### ISSUE THREAD

**Issue by josephlavin** [briannesbitt/Carbon#2500]
Hello,

I encountered an issue with the following code:
```php
$test_date = CarbonImmutable::parse('2020-01-01T12:01:01-08:00');
CarbonImmutable::setTestNowAndTimezone($test_date);
echo CarbonImmutable::now()->toIso8601String(); 
```

Carbon version: **2.54.0**

PHP version: **7.4.22**

I expected to get:

```
2020-01-01T12:01:01-08:00
```

But I actually get:

```
2020-01-01T12:01:01-06:00
```

This seems to be related to https://github.com/briannesbitt/Carbon/issues/2481#issuecomment-956645309.

`CarbonImmutable::setTestNowAndTimezone` executes `date_default_timezone_set($testNow->getTimezone()->getName())`;  `$testNow->getTimezone()->getName() === "-08:00"`.  But `date_default_timezone_set` requires a timezone id (like `America/Los_Angeles`).  This causes the timezone not to be changed and the server default to be used.

Manually executing `date_default_timezone_set('America/Los_Angeles');` does fix the issue:
```php
$test_date = CarbonImmutable::parse('2020-01-01T12:01:01-08:00');
CarbonImmutable::setTestNowAndTimezone($test_date);
date_default_timezone_set('America/Los_Angeles');
echo CarbonImmutable::now()->toIso8601String(); // '2020-01-01T12:01:01-06:00'
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello. :wave

This is what I meant in my comment when saying the assertion in test may never happen with real time. The test should represent a realistic situation to be relevant.

And having `-08:00` as default timezone for `now()` never happens in the real life, in the real life, you always have a valid timezone ID (a city or UTC, CET, CST, etc.) as default timezone. And that's a completely different meaning than an offset timezone such as `-08:00`

See this:
```php
echo CarbonImmutable::parse('2020-01-01T12:01:01-08:00')->addMonths(6)->format('Y-m-d H:i:s O');
echo "\n";
echo CarbonImmutable::parse('2020-01-01T12:01:01 America/Los_Angeles')->addMonths(6)->format('Y-m-d H:i:s O');
```
Output:
```
2020-07-01 12:01:01 -0800
2020-07-01 12:01:01 -0700
```

You have a different moment at the end because Los Angeles observes a daylight time change.

That's why using `-08:00` when you mean `America/Los_Angeles` is a bad idea and will make your test success while the same can actually fail in production. Because it's static, while for a given city, there is an history attached to it which can contain offset changes in the past and/or in the future.

Actually for the majority of projects the timezone for `Carbon::now()` is not even a variable. In 99.99% of the case the relevant default timezone for your application is UTC and so your test should just always use this. If your code handles user timezone, this should be an input of your test, it should not change the server default timezone. Because it's the same (normally) in real life, you don't change the default timezone for each request to match the timezone of the user (if you do, I recommend to reconsider wisely this choice).

That's why I don't think we should make any change for this and should simply use this instead:
```php
$test_date = CarbonImmutable::parse('2020-01-01 12:01:01 America/Los_Angeles');
CarbonImmutable::setTestNowAndTimezone($test_date);
echo CarbonImmutable::now()->toIso8601String();
```
But more likely a realistic test would be more something like this:
```php
date_default_timezone_set('UTC'); // Like in the prod
$test_date = CarbonImmutable::parse('2020-01-01 12:01:01 America/Los_Angeles');
CarbonImmutable::setTestNow($test_date); // Mock the time and don't change the timezone

$userTimezone = 'America/Los_Angeles';
echo CarbonImmutable::now()->tz($userTimezone)->toIso8601String();
```
And in a properly localized application (if relevant), then changing the $userTimezone (without changing the rest above) should still give coherent output as expected by a user being in such timezone.

Thanks.

**Comment by kylekatarnls** [comment]
I think we should actually raise an exception when receiving an timezone offset in `setTestNowAndTimezone()` so developers would be immediately made aware of the issue.

**Comment by josephlavin** [comment]
@kylekatarnls: Thank you for the detailed response!
