### ISSUE TITLE
Check if carbon instance has time

### ISSUE THREAD

**Issue by skywarth** [briannesbitt/Carbon#2522]
Hello,

Is there a way to check if given carbon instance has time data ? 
```
Carbon::now()->hasTime(); //true

Carbon::parse('2021-11-02 00:00:00')->hasTime(); //false
```
Condition for a carbon instance to have time: hour, minute, seconds are not 0 at the same time. In other words it is not "00:00:00"

Thank you.

Carbon version: 2.53.1
PHP version: 7.4

**Comment by kylekatarnls** [comment]
Hello,

Be careful because a Carbon or DateTime instance always "has" a time midnight is also a time and `Carbon::now()` will be 00:00:00 during 1 second each day.

If you ignore microseconds you can simply use `isMidnight()`:
```php
var_dump(!Carbon::now()->isMidnight()); // true
var_dump(!Carbon::parse('2021-11-02 00:00:00')->isMidnight()); // false
var_dump(!Carbon::parse('2021-11-02 00:00:00.000001')->isMidnight()); // false
```

Else I would recommend not to over complicate it and simply compare with formatted string which is exactly your specifications:
```php
var_dump(Carbon::now()->format('H:i:s.u') !== '00:00:00.000000'); // true
var_dump(Carbon::parse('2021-11-02 00:00:00')->format('H:i:s.u') !== '00:00:00.000000'); // false
var_dump(Carbon::parse('2021-11-02 00:00:00.000001')->format('H:i:s.u') !== '00:00:00.000000'); // true
```
