### ISSUE TITLE
[Semantical Error] "@mixin" in class Carbon\Carbon was never imported. 

### ISSUE THREAD

**Issue by N-M** [briannesbitt/Carbon#2525]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2018-06-01')->subDay()->month;
```

Carbon version: 2.54.0

PHP version: 8.0.7
Slim Framework

I expected to get:

```
formatted date
```

But I actually get:

![image](https://user-images.githubusercontent.com/781417/147347738-636df4cf-6091-443d-94aa-2abfc2d1c706.png)

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

formatted date is not the expected output from the `->month` getter, expected result here is `5` and it's actually what is returned in https://try-carbon.herokuapp.com or any clean install.

You possibly get an error from the debugger itself (running inspection on annotation apparently  but it probably should not. Carbon does not at least, so it's likely a static analyzer or Slim framework generating this warning.

Please provide minimum code chunk allowing me to reproduce your issue and I would re-open the issue.

Thanks.

**Comment by lamkimphu258** [comment]
Hi @kylekatarnls, I have the same error with this code:
`
     $thisYearStart = CarbonImmutable::createFromDate(  
              CarbonImmutable::now()->year,  
              1,  
              1                                                                                                                         
          )->setTime(0, 0, 0);                                                                                                          
          $thisYearEnd = CarbonImmutable::createFromDate(                                                                               
              CarbonImmutable::now()->year,                                                                                             
              12,                                                                                                                       
              31                                                                                                                        
        )->setTime(23, 59, 59);  
`

**Comment by yuuzora** [comment]
Hello,

I'm encountering the same error. Using symfony here

Carbon version: 2.57.0
PHP version: 7.4.22
Symfony version: 5.4.2

This happens when trying to deserialize JSON content into a DTO with a property type-hinted as Carbon or CarbonImmutable.
In the controller:
`        $command = $this->serializer->deserialize($request->getContent(), DuplicateCertificateTemplateCommand::class, 'json');
`

The DTO class: 
`class DuplicateCertificateTemplateCommand
{
    public ?Carbon $expirationDate = null;
}`

Tried to put:
 
`
AnnotationReader::addGlobalIgnoredName('mixin');
AnnotationReader::addGlobalIgnoredName('alias');
`

But then I get another error:
`Unknown setter '0'`

From what the previous reply linked ( https://github.com/webmozarts/assert/issues/228 ) it seems mixins breaks Doctrine, any plan to remove them?

Thanks!

**Comment by N-M** [comment]
If someone manually initializes AnnotationReader this is good way to fix it

```
$annotationReader = new AnnotationReader();
$annotationReader::addGlobalIgnoredName('mixin');
```
