### ISSUE TITLE
Strange difference in seconds behavior

### ISSUE THREAD

**Issue by greblov** [briannesbitt/Carbon#2546]
Hello,

I encountered an issue with the following code:
```php
var_dump(30 * 24 * 60 * 60);
var_dump(now()->addSeconds(30 * 24 * 60 * 60)->diffInSeconds(now()));
```

Carbon version: **2.56.0**

PHP version: **PHP 8.0.9 (cli) (built: Jul 30 2021 00:44:38) ( NTS )**

I expected to get:

```
int(2592000)
int(2592000)
```

But I actually get:

```
int(2592000)
int(2678399) // One day (24h) more than expected.
```

Looks like diff functionality thinks that current year is a leap year and adds one day for unexisted February 29.

Because 28 * 24 * 60 * 60 works as expected, but 29 * 24 * 60 * 60 already not (same one day extra difff). Now is 2022-02-01.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I can't reproduce this on https://try-carbon.herokuapp.com/

Can you test with `now('UTC')` instead to ensure there is nothing wrong with a timezone setting. And as "now" is changing it's difficult to be sure I do replicate the situation. Please try to use static dates instead with explicit timezone, so you can get a 100% reproductible situation testable in https://try-carbon.herokuapp.com/

Also, `2592000` is not the expected behavior here because the time is not frozen and the execution of the PHP code is not instantaneous. The whole code should still take less than a second but as it's floored to the lower integer, you'll get `2591999` in a normal situation.

Thanks.

**Comment by greblov** [comment]
> you'll get 2591999 in a normal situation.

Of course, but not the difference 2678399-2592000=86399 (1 day), yes?

> And as "now" is changing it's difficult to be sure I do replicate the situation.

It's laravel shortcut function. But you're right, I should try pure Carbon::now call, will do it at morning (somewhere after 10-12h from this moment).

> Can you test with now('UTC')

Beleive me please, I dumped timezones of both "now()->timezone" first, then started to experiment. But.

**Comment by kylekatarnls** [comment]
You misunderstood me, I'm not doubting you're saying the truth.

I completely believe you when you say you get this result, but if I can't find the reason if I can't reproduce in a reliable way.

If you can't reproduce in https://try-carbon.herokuapp.com/ it means the reason is not in that code or those specific methods in Carbon (addSeconds, diffInSeconds), it's somewhere else in your app, dependencies, config, context.

What I need to help now() vs Carbon::now() is not the point neither. I'm saying if you use `Carbon::parse('2022-02-01 23:46:12.123456', 'UTC')` I can be confident I use the exact same data in some unit test and can work on it.

About the try-carbon interface you can use the 2.x-dev, it's the same version as 2.56.0 currently.

You can see we're making a lot of tests for each PHP version to check methods return the expected values (addSeconds and diffInSeconds are in those) https://github.com/briannesbitt/Carbon/runs/4992040054?check_suite_focus=true this is why I suspect it's something outside the scope of Carbon and I can't rely guess it without more clues.

**Comment by greblov** [comment]
Same strange results with native carbon call.

        var_dump(30 * 24 * 60 * 60);
        var_dump(Carbon::now()->addSeconds(30 * 24 * 60 * 60)->diffInSeconds(Carbon::now()));
        
> If you can't reproduce in https://try-carbon.herokuapp.com/ it means the reason is not in that code
        
I can't reproduce because your test environment DOES NOT WORK for the version 2.56.0, SEE SCREENSHOT: http://joxi.ru/8Anz0QjUoBG1ZA

**Comment by kylekatarnls** [comment]
> About the try-carbon interface you can use the 2.x-dev, it's the same version as 2.56.0 currently.

**Comment by lonewolfffffff** [comment]
@greblov is it possible to add a variable to your code?

something like
`$now = Carbon::now();   // or, using Laravel helper, $now = now()`

this way, you will get your expected behavior
`var_dump($now->copy()->addSeconds(30 * 24 * 60 * 60)->diffInSeconds($now))    // int(2592000)`

I use `copy()` because `addSeconds()` modifies `$now` (`$now` is not immutable)

**Comment by kylekatarnls** [comment]
@greblov
If it were (at least only) a regression in 2.56.0, it would have trigger build failure as this case is tested in our unit tests. And I installed a fresh new Laravel app with 2.56.0 carbon version and I get the expected value, e.g. `2591999` (or `2592000` using the @lonewolfffffff code or using `CarbonImmutable`).

Seeing a different value now and months before and assume that difference comes from code change in the library is very likely a dead-end. You would find the real route cause by checking the other factors, the other debugging suggestions I already made: - 
 - Checking if it's calendar-related using `Carbon::parse()` and exact date (such as a date 2 months before, when it worked) instead of now and then provide set of dates that works/does not work
 - Checking with `now('UTC')` instead of `now()` to see if something is wrong with the current timezone in the machine where you run the code

And some new tests to make regarding your last point:
 - Explicitly download `composer require "nesbot/carbon:2.50.0"` for instance so you can easily confirm/refute your hypothesis about a regression in the library
 - Try to retire pieces: such as third-party in your app you added during the last 2 months (try to checkout a revision at the moment you say it worked) and add the same `var_dump(...)` I would recommend to search for code that can extend the Carbon class, add macros or mixins and so they actually can modify the behavior of the library in a way I have no control over

If you can provide those elements, I can investigate the issue, else I have just nowhere to search.
