### ISSUE TITLE
Calling startOfYear() before setting set('isoWeek') calls year to roll back one year

### ISSUE THREAD

**Issue by sandervankasteel** [briannesbitt/Carbon#2558]
Hello,

I encountered an issue with the following code:
```php
$now = Carbon::now();
$now
    ->startOfYear()
    ->set('isoWeek', 25)
    ->startOfWeek();

$now->format('Y-m-d'); 
```

Carbon version: **2.48.1**

PHP version: **8.0.13**

I expected to get:

```
"2022-06-20"
```

But I actually get:

```
"2021-06-21"
```

If I remove the call to `startOfYear()`, I get the expected result of 
```
"2022-06-20" 
```

I've also tried it in https://try-carbon.herokuapp.com/ with the latest stable version of Carbon (2.56.0), there it also happens. See attached screenshot

![image](https://user-images.githubusercontent.com/17492906/156998645-5dca3ea8-8a55-4a0b-ace0-73a2332b9ecf.png)

Thanks!

**Comment by kylekatarnls** [comment]
Hello 👋 

It is expected because `startOfYear()` shifts to 2022-01-01 which is in the ISO week-year 2021, ISO week-year starts on 2022-01-03 (as you can see if you do `->set('isoWeek', 1)->startOfWeek()` which is actually the way to go to the start of week-year).

You can see it with this:
```php
$now = Carbon::now();
$now->set('isoWeek', 1)->startOfWeek();

echo $now->isoWeekYear . "\n"; // 2022

$now = Carbon::now();
$now->startOfYear();

echo $now->isoWeekYear . "\n"; // 2021
```

By nature, you won't be able to mix calls relying on calendar year with ones on weekYear (use the current locale as reference) or isoWeekYear (use https://en.wikipedia.org/wiki/ISO_week_date).

You have to pick the right calendar system for your business use cas and stick to it to have consistent output.

Thanks.

**Comment by sandervankasteel** [comment]
@kylekatarnls Thanks for the reply! 

That actually makes a lot of sense 😅
