### ISSUE TITLE
performance issue when calling toArray on CarbonPeriod

### ISSUE THREAD

**Issue by pjadanowski** [briannesbitt/Carbon#2618]
Hello,

I encountered an issue with the following code:
```php

$start = Carbon::now();
$week = CarbonInterval::days(1)->toPeriod($start, $start->copy()->addWeek());
$end = $start->copy()->addHours(10);

foreach ($week as $day) {
    $period = CarbonInterval::minutes(rand(10,20))
                             ->toPeriod($start, $end);
    $count = $period->count();   // let's say we need this number                       
}

```

i takes over a second to do this

I found out that `toArray()` method takes ca. 0.15sec each time (0.16 * 7 = ~1.12 sec)

Carbon version: **2.58.0**

PHP version: **8.1.6**

Thanks!

**Comment by kylekatarnls** [comment]
Hello, `CarbonPeriod` is clearly not meant for that. When you need a count, you always have a possible mathematic operation:

```php
$minutesInterval = rand(10, 20);
$count = floor($start->diffInMinutes($end) / $minutesInterval);
```

Because periods can contains filters, or DST changes, count performs a complete iteration to give the exact count. Also the iteration creates a Carbon object for each moment iterated because the main use case of periods is to actually iterate on it and execute an action for each step. This part may be optimized such as creating a `DateTimeImmutable` instead of a `Carbon` when it's called via `count()` but we would still have a complete iteration so if the interval is short proportionally to the period, it would still be suboptimal.

And obviously putting a work inside an other 7-rounds-loop multiplies the time by 7. It's not really Carbon-specific and so the `foreach ($week as $day) {` is out of scope here as it belongs to your application logic.

For the record I also have way better performances when I test similar stuff with PHP 8.1:

```php
$t = microtime(true);

for ($i = 0; $i < 100; $i++) {
    $period = CarbonInterval::minutes(rand(10, 20))
        ->toPeriod('today', 'tomorrow');
    $count = $period->count();
}

echo microtime(true) - $t;
```
0.079 seconds for the whole 100 iterations of a [10; 20] interval in a whole day. And only +2.4 MB Ram usage. Maybe CPU available on the machine for the given script is low, or you have a debugger (like XDebug) that is significantly reducing performances. Or simply you have something else executed in your benchmark not mentioned in the code above.

Anyway, even if the iteration matters, I would simply not take this path. Even with a `DatePeriod` here you would have a slow execution compared to timestamp operations for instance:
```php
$minutesInterval = rand(10, 20);
$endTimestamp = $end->getTimestamp();

for ($time = $start->getTimestamp(); $time < $endTimestamp; $time +=$minutesInterval) {
  $count++;
}
```
If your really need performance and ensured you don't have something else more significant to solve, this is the way to improve. Of course it can also help to have cronjob to periodically prepare the counts in cache and so you serve cached values instantly to users.

You have many solutions to check that will depends on your business logic and will be way more efficient than what we could do as micro-optimisations from inside the Carbon library.

That's why I would not go further for this from our side unless we could identify a big bottleneck that we can solve without breaking features.

Thanks.

**Comment by pjadanowski** [comment]
thank you for your detailed answer. Unfortunately it is not so easy to do some basic math with it. I know you could take begin and end, calculate difference in minutes and divide it by interval, because actually i have filtering within this so code would be 

```php
foreach ($week as $day) {
    $period = CarbonInterval::minutes(15)
                             ->toPeriod($start, $end);
    $period->addFilters(...); // some booked appointments  etc. 
    $count = $period->count();   // and i need to know how many slots are left for each day     
}
```

would you give me advice in this case?
