### ISSUE TITLE
Incorrect `->forHumans()` result when the interval is negative

### ISSUE THREAD

**Issue by Abdul-fattah-Tayih** [briannesbitt/Carbon#2619]
Hello,

I encountered an issue with the following code:
```php
$interval = \Carbon\CarbonInterval::weeks(-1);
echo $interval->forHumans(\Carbon\CarbonInterface::DIFF_RELATIVE_TO_NOW);
```

Carbon version: **2.57.0**

PHP version: **8.1.2**

I expected to get:

```
1 week ago
```

But I actually get:

```
1 second ago
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, 👋 

In this case, it's a bit tricky, because the interval is not negative (as per `invert` property), only the week number is.

For instance:
`echo \Carbon\CarbonInterval::weeks(-1)->hours(48)->forHumans(\Carbon\CarbonInterface::DIFF_RELATIVE_TO_NOW);`
displays "48 hours ago" because the negatives values are skipped.

Here is 2 work-arounds:
```php
$interval = \Carbon\CarbonInterval::weeks(-1);
echo $interval->cascade()->forHumans(\Carbon\CarbonInterface::DIFF_RELATIVE_TO_NOW);
```

Or:
```php
$interval = \Carbon\CarbonInterval::weeks(1)->invert();
echo $interval->forHumans(\Carbon\CarbonInterface::DIFF_RELATIVE_TO_NOW);
```

The dynamic way to create an inverted interval when negative number (note: this will work only if you have 1 single unit when creating interval):
```php
function createWeekInterval(int $numberOfWeeks): \Carbon\CarbonInterval
{
  $interval = \Carbon\CarbonInterval::weeks(abs($numberOfWeeks));

  if ($numberOfWeeks < 0) {
    $interval->invert();
  }

  return $interval;
}

$interval = createWeekInterval(-1);
echo $interval->forHumans(\Carbon\CarbonInterface::DIFF_RELATIVE_TO_NOW);
```

The very problem while we can't do this right into the constructor is that when creating the object we don't know yet if other units will be added after and if they will be negative or positive and so if it's meant to be a whole negative interval or a mixed one. So when the interval has multiple unit if should be either resolved by `->cascade()` or by a custom application logic.
