### ISSUE TITLE
Carbon::parse('2012') become today, Why ?

### ISSUE THREAD

**Issue by foremtehan** [briannesbitt/Carbon#2620]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2012');
```

Carbon version: ^2.53.1

PHP version: 8.1.1

I expected to get:

```
2012-01-01 00:00:00
```

But I actually get:

```
2022-05-30 20:12:00
```

I'm using carbon in laravel 9, Can you tell why it converts to Today? How can i parse this correctly ?

**Comment by kylekatarnls** [comment]
Hello,

Carbon doesn't convert, PHP itself does:
```php
$date = new DateTime('2012');

echo $date->format('Y-m-d H:i:s'); // 2022-05-30 20:12:00
```

By default PHP new DateTime gives you the "current value" for any unit you didn't specify when giving only the year or only the time, e.g. it takes "now" (and use the default timezone as per php.ini), then it changes the year to 2012.

While it's unspecified, it's not completely crazy, it's arbitrary and it would have been arbitrary too to assume that unspecified unit should be `01-01 00:00:00`.

So my recommendation is to be explicit in what you want. So PHP does not have to make any assumption:

```php
$year = 2012;

echo Carbon::createFromFormat('!Y', $year);
// or
echo Carbon::parse($year . '-01-01 00:00:00.000000 UTC');
```
`!` is the reset character see: https://www.php.net/manual/en/datetime.createfromformat.php

I recommend the `Carbon::parse($year . '-01-01 00:00:00.000000 UTC')` because this way it's clear for anyone reading the code what you will exactly get.

Last, if your input can be 4 digits but can also be other format, you can go with your own parsing to enforce custom rules over the PHP default behavior to decide what it should mean:

```php
$input = '2012'; // or can be also '2012-05-23' but let's say you don't know in advance:

if (preg_match('/^\d{4}$/', $input)) {
  $input .= '-01-01 00:00:00.000000';
} 

$date = Carbon::parse($input);
```

Thanks.
