### ISSUE TITLE
Time am and pm not working with locale fr_FR

### ISSUE THREAD

**Issue by bilalmalkoc** [briannesbitt/Carbon#2642]
Hello,

I encountered an issue with the following code: I want to show pm, am time in French language.
```php
$carbon = new Carbon\Carbon();
echo $carbon::parse( '2022-08-01 09:30' )->locale( 'fr_FR' )->isoFormat( 'h:mm a' );
```

Carbon version: **2.59**

PHP version: **8.0.0**

I expected to get:

```
9:30 du
```

But I actually get:

```
9:30 am
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

For the record, "du" is meaningless in French, maybe you mean "du matin" which would indeed be understandable by French people, but "du" would definitely not?

Here is the whole translations file for fr_FR:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/fr.php

`meridiem` is not changed in fr_FR, because AM and PM actually are Latin abbreviations, they are not specific to English language and French people will understand them just fine.

However, France doesn't use the 12-hours format, it uses hours from 0 to 23 as specified in the `LT` format, having "20:00" is way more common than "8:00 PM" or "8:00 du soir" (and it's way less ambiguous, honestly I don't get why some prefer the AM/PM notation :p )

```php
echo $carbon::parse( '2022-08-01 09:30' )->locale( 'fr_FR' )->isoFormat( 'LT' );
```

`LT` is the recommended way as it will translate and also pick the more common format for the given language.

If you still really want to give a specific FR translations to them, you can override the language:

```php
\Carbon\Translator::get('xx')->setTranslations([
    'meridiem' => function ($hour) {
        if ($hour < 12) {
            return 'du matin';
        }

        if ($hour < 18) {
            return "de l'après-midi";
        }

        return 'du soir';
    },
]);
```

**Comment by bilalmalkoc** [comment]
Thanks. Can i convert this `2022-08-01 09:30` to this '9h30'? It is true French version.

**Comment by kylekatarnls** [comment]
It's used, but it's not the most common, take a look at times on the main TV website in France:
https://www.tf1.fr/

You can see `19:10`

Same if you try to search "heure" using the "fr" locale in Google:
https://www.google.com/search?q=heure&hl=fr

I can guarantee to you `'LT' => 'HH:mm'` as it is now in the `fr` file of Carbon is perfectly standard, `h` is not more "true".

While `9h30` is understandable, it more likely refers to an interval, example:

13:00 + 1h30 = 14:30

"h" as an abbreviation of "heure" is indeed standard in French and suit to relative time, but is less common when referring to absolute time.

If you still want to tweak it to have your custom format, it's exactly the same principle:
```php
\Carbon\Translator::get('fr_FR')->setTranslations([
    'formats' => [
        'LT' => 'H\hmm',
    ],
]);
echo Carbon::now()->locale('fr_FR')->isoFormat('LT');
```
