### ISSUE TITLE
diffForHumans gives wrong amount of days

### ISSUE THREAD

**Issue by Slubby** [briannesbitt/Carbon#2673]
Hello,

I encountered an issue with the following code:
```php
$deletedDate = Carbon::now()->startOfDay()->addDays(31);

echo $deletedDate->diffForHumans(Carbon::now()->startOfDay(), [
    'syntax' => CarbonInterface::DIFF_ABSOLUTE,
    'skip' => ['m', 'w'],
    'minimumUnit' => 'd'
]);;
```

Carbon version: 2.61.0

PHP version: 8.1.8

I expected to get:

```
31 days
```

But I actually get:

```
28 days
```

Thanks!

**Comment by kylekatarnls** [comment]
Thanks for the report, indeed when month and year of the interval are either 0 or skipped, it makes sense to use the total number of days instead of the `DateInterval` representation which loose the context.

It will be fixed in 2.64.0, you can test the fix with `composer require "nesbot/carbon:dev-master as 2.64.0"`
