### ISSUE TITLE
DST Switchover Workaround

### ISSUE THREAD

**Issue by fritzfelix** [briannesbitt/Carbon#2695]
Hello,

sadly during the last DST switch on October 30th, we ran into a bug where `diffInMinutes()` yielded 60 during the switchover hour instead of expected 0. We think we tracked it down to this line:

https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Traits/Difference.php#L133

Here, a workaround seems to be implemented for version *greater than 8.1.0-dev*, however the 2 related bugs both seem to be fixed in the PHP version we are running, namely 8.1.9. Running the examples from the bugs both yield the expected result in 8.1.9.

I'm wondering whether this version comparison has to be rewritten.

Carbon version: **2.62.1**

PHP version: **8.1.9**

**Comment by kylekatarnls** [comment]
Those bugs are sadly not solved, if I removed the work-around, it's failing even up to PHP 8.2,

> I'm wondering whether this version comparison has to be rewritten.

Answering it is quite simple, here is what happen when we remove the hack:
https://github.com/briannesbitt/Carbon/pull/2696

See the results in unit: this gives terribly wrong results for common case, while DST is also more scoped issue.

If you want me to investigate more this issue I would need you to fill the template:

- [ ] minimal code allowing to reproduce the issue in https://play.phpsandbox.io/embed/nesbot/carbon
- [ ] expected behavior
- [ ] actual behavior

**Comment by fritzfr** [comment]
> Running the examples from the bugs both yield the expected result in 8.1.9.

Just to clarify, when you take the 2 short test scripts from the linked bugs on bugs.php.net, you are not getting the "expected result" when running with 8.1 or 8.2? I'm getting the expected result, therefore I assumed they are fixed.

**Comment by kylekatarnls** [comment]
The very exact cases in the bugs.php.net were fixed before stable release but more complexe cases like the one failing in our unit tests or here you can see it with vanilla PHP are still giving crazy results:

https://3v4l.org/ObD5g

That's the reason why we still have the work-around which translated in vanilla PHP is:

https://3v4l.org/68nEE

That's why we don't rely just on PHP release notes to decides a bug is fixed. Carbon has its own unit tests for expected behavior, some Carbon bugs root causes are PHP bugs but it doesn't mean the fix PHP team decide to use to solve the issue is enough or also good regarding Carbon expected behavior.

So please provide for your exact case:

- [ ] minimal code allowing to reproduce the issue in https://play.phpsandbox.io/embed/nesbot/carbon
- [ ] expected behavior
- [ ] actual behavior

And note that a solution for it would be acceptable only if does not cause regressions in other places unless proving the current expectations are not good or it's really worth it because it solves a more critical use case.

**Comment by fritzfelix** [comment]
Alright, I think I found the bug:

```php
$first = \Carbon\Carbon::create(2022, 10, 30, 2, 30, 0, 'Europe/Berlin');
$second = \Carbon\Carbon::create(2022, 10, 30, 3, 30, 0, 'Europe/Berlin');
printf($first->diffInMinutes());
printf($second->diffInMinutes());
```

Set your local system time to 30th October 2022, 1:59:50 **Europe/Berlin** and wait until 2:00:00 is reached.

With php8.1:
Actual result:
--------
90
90

Expected result:
--------
30
90

With php7.4:
Actual & Expected Result:
-------
30
90

**Comment by kylekatarnls** [comment]
Hum, for the record, removing the [work-around your mentioned in the first message](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Traits/Difference.php#L133) wont' change the result above.

And I don't reproduce your `Actual result`, I got:
`90` and `150` in PHP 7.4, 8.1.3 and 8.1.12 [as you can see in the sandbox too](https://play.phpsandbox.io/nesbot/carbon?version=2.62.1.0&input=%3C%3Fphp%0D%0A%0D%0Adate_default_timezone_set(%27Europe%2FBerlin%27)%3B%0D%0A%0D%0ACarbon%3A%3AsetTestNow(Carbon%3A%3Acreate(2022%2C%2010%2C%2030%2C%201%2C%2059%2C%2050%2C%20%27Europe%2FBerlin%27))%3B%0D%0A%0D%0A%24first%20%3D%20Carbon%3A%3Acreate(2022%2C%2010%2C%2030%2C%202%2C%2030%2C%200%2C%20%27Europe%2FBerlin%27)%3B%0D%0A%24second%20%3D%20Carbon%3A%3Acreate(2022%2C%2010%2C%2030%2C%203%2C%2030%2C%200%2C%20%27Europe%2FBerlin%27)%3B%0D%0A%0D%0Aecho%20%24first-%3EdiffInMinutes()%20.%20%22%5Cn%22%3B%0D%0Aecho%20%24second-%3EdiffInMinutes()%20.%20%22%5Cn%22%3B)

`diffInMinutes()` can take a relative date in parameter which should be the same than changing device clock; it's also possible to use `Carbon::setTestNow()` and so you would be able to write a code that is testable in and always give the same output.

Also it's not obvious that 30 is expected, as `2:30` here is ambiguous, it can be 02:30+02:00 (CEST) or 02:30+01:00 (CET).

And here I can confirm we are dealing with still unsolved PHP bugs:
https://3v4l.org/TUTol

You can see that the timezone of the +1 hour date also changed since `8.1.7` (of course date/time breaking change always happen on a patch release 🤦) and Carbon just give you a strictly correct answer from the object PHP gave: `02:30+02:00` is indeed 30 minutes (and 10 seconds) after `01:59:50+02:00` while `02:30+01:00` is 90 minutes after `01:59:50+02:00`.

If you look at the result, everything is wrong. From a timeline perspective what happen if you pick the real time every hour is:
01:30+02:00
02:30+02:00
02:30+01:00

This is what we get if we pass by UTC:
https://3v4l.org/4m4N3

PHP team declared it's solved because +1 hour does not mean going 1 hour in the future but adding 1 to the hour number, which is in my opinion in contradiction with the fact that passing a DST datetime change automatically apply the new timezone.

Using the `shiftDate()` above you can see the `Carbon::diffInMinutes()` is actually consistent across PHP versions:

```php
function shiftDate(DateTime $date, int $hours): DateTime
{
    $timezone = $date->getTimezone();
    $date->setTimezone(new DateTimeZone('UTC'));
    $date->modify("+$hours hours");
    
    return $date->setTimezone($timezone);
}

$before = shiftDate(new Carbon('2022-10-30 01:59:50 Europe/Berlin'), 0);
$cest = shiftDate(new Carbon('2022-10-30 01:30 Europe/Berlin'), 1);
$cet = shiftDate(new Carbon('2022-10-30 01:30 Europe/Berlin'), 2);

echo $cest->diffInMinutes($before) . "\n";
echo $cet->diffInMinutes($before) . "\n";
```

Here you'll get 30 and 90 for PHP 7.4, 8.0 or 8.1.

-----------------

So to sum-up: when you say `2022-10-30 02:30 Europe/Berlin` you don't say if you want 02:30 before or after DST, it's up to PHP `DateTime` constructor (`Carbon` has no control over this part) to decide what to give you, PHP < 8.1.7 gives Winter time, PHP >= 8.1.7 gives Summer time, it's arbitrary but both are correct, expected behavior between those 2 options is a user point of view.

What to do?

=> Don't let PHP decide, tell what you mean:
```php
$before = new Carbon('2022-10-30 01:59:50+02:00');
$cest = new Carbon('2022-10-30 02:30+02:00');
$cet = new Carbon('2022-10-30 02:30+01:00');

echo $cest->diffInMinutes($before) . "\n"; // 30
echo $cet->diffInMinutes($before) . "\n"; // 90
```
If it's a user input, check for DST and if it's in, prompt user with some "This time exists in CET and CEST, please select one"

=> or use UTC:
```php
$before = new Carbon('2022-10-30 01:59:50 Europe/Berlin');
$cest = new Carbon('2022-10-30 00:30 UTC');
$cet = new Carbon('2022-10-30 01:30 UTC');

echo $cest->diffInMinutes($before) . "\n";
echo $cet->diffInMinutes($before) . "\n";
```
If you're not manipulating a date that actually have a localized context, then you should use only UTC. See [Always Use UTC Dates And Times](https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164)

**Comment by fritzfelix** [comment]
In the process I realized and fully agree, this has nothing to do with Carbon. 

> it's not obvious that 30 is expected

In comparison to 7.4, this is what I expected. But in the bigger picture, you are right.

> PHP < 8.1.7 gives Winter time, PHP >= 8.1.7 gives Summer time

In the end, this is what broke the logic of my code. Will work around it as you advised!

I would like to thank you very much for this thorough insight! I'm closing this.
