### ISSUE TITLE
Locale is now ignored on weekday()

### ISSUE THREAD

**Issue by christiangroothuis** [briannesbitt/Carbon#2702]
Hello,

Since upgrading to the latest version of Carbon (2.63.0), I noticed that a few tests we're failing, because the weekday method was returning a different value. By looking at this [pull request](https://github.com/briannesbitt/Carbon/pull/2687/files), it looks like the method is now ignoring the set locale when no value parameter is given.

Code example that since the 2.63.2 update gives a different value in e.g. locale 'nl':
```php
echo Carbon::parse('2022-04-18')->weekday();
```
I expect to get the value `0` with locale 'nl', since in my locale the week starts on a monday.

However, since the locale is now ignored, I receive the value `1`, as it assumes that the week starts on Sunday.

Is this supposed to be the expected behavior and if so, how do I get the weekday in a given locale?

Carbon version: 2.63.0

PHP version: 8.1.12

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

The method has been aligned with is documentation: `Get/set the weekday from 0 (Sunday) to 6 (Saturday).` which also match the constants: `CarbonInterface::MONDAY` (1), `CarbonInterface::TUESDAY` (2), etc.

As per unit tests, the method was always meant to get those constants as parameter (when used as a setter) and return constants: https://github.com/briannesbitt/Carbon/pull/2687/files#diff-fae468fcdb02ece2c068a30a8db1e2d4483a823e13e697883c30ee2ddbfbb4deR5412

The start of week is used in this method to find start/end when this method is used as a setter. You can see that:
```php
echo Carbon::parse('2022-11-13')->locale('nl_NL')->weekday(CarbonInterface::MONDAY) . "\n";
echo Carbon::parse('2022-11-13')->locale('en_US')->weekday(CarbonInterface::MONDAY) . "\n";
```
With nl_NL: you get the previous Monday, with en_US: you get the next Monday.

`weekday` was initially implemented following momentjs implementation, but then it mismatch the documentation, the constants and actually don't take the start of week from locale into account when used as a setter (so the bug #2675 which is the reason for the pull request you're mentioning).

The use case you refer (i.e. counting the number of days since the start of the week) could deserve a different method(s).

Meanwhile you can safely use this alternative for the getter:
```php
use Carbon\CarbonImmutable;

$date = CarbonImmutable::parse('2022-11-13')->locale('nl_NL');

echo (int) $date->diffIndays($date->startOfWeek(), true); // 6

$date = CarbonImmutable::parse('2022-11-14')->locale('nl_NL');

echo (int) $date->diffIndays($date->startOfWeek(), true); // 0

$date = CarbonImmutable::parse('2022-11-15')->locale('nl_NL');

echo (int) $date->diffIndays($date->startOfWeek(), true); // 1
```

If you want a perfect match with previous implementation (which will be also a bit faster to execute than the above):
```php
use Carbon\CarbonImmutable;
use Carbon\CarbonInterface;

function daysSinceStartOfWeek(CarbonInterface $date): int {
     return (int) (($date->dayOfWeek + 7 - (int) ($date->getTranslationMessage('first_day_of_week') ?? 0)) % 7);
}

$date = CarbonImmutable::parse('2022-11-13')->locale('nl_NL');

echo daysSinceStartOfWeek($date) . "\n";

$date = CarbonImmutable::parse('2022-11-14')->locale('nl_NL');

echo daysSinceStartOfWeek($date) . "\n";

$date = CarbonImmutable::parse('2022-11-15')->locale('nl_NL');

echo daysSinceStartOfWeek($date) . "\n";
```

For the setter part, I recommend the explicit way:
```php
echo CarbonImmutable::parse('2022-11-13')->locale('nl_NL')->startOfWeek()->addDays(2); // 2022-11-09
echo CarbonImmutable::parse('2022-11-14')->locale('nl_NL')->startOfWeek()->addDays(2); // 2022-11-16
echo CarbonImmutable::parse('2022-11-15')->locale('nl_NL')->startOfWeek()->addDays(0); // 2022-11-14
```

I will think about how we can make this method consistent without having code that make no sense such as:
```php
CarbonImmutable::parse('2022-11-14')->locale('nl_NL')->weekday() === CarbonInterface::SUNDAY
```
which was `true` before 2.63.0.

**Comment by kylekatarnls** [comment]
Alternative methods will be provided in the next version to replace the old behavior of `weekday`:

`getDaysFromStartOfWeek()`
`setDaysFromStartOfWeek()`
