### ISSUE TITLE
Regression on `addDays(null)` & `subDays(null)` after upgrading from `2.63.0` to `2.64.0`

### ISSUE THREAD

**Issue by crynobone** [briannesbitt/Carbon#2714]
Hello,

I encountered an issue with the following code:
```php
$start = Carbon\CarbonImmutable::now()->subDays(null);
$end = Carbon\CarbonImmutable::now();

var_dump([
  $start->toDatetimeString(),
  $end->toDatetimeString(),
]);
```

Carbon version: 2.64.0

PHP version: 8.1.12

I expected to get:

```
[
  "2022-12-04 02:26:36",
  "2022-12-05 02:26:36",
] // This is working as expected in 2.63.0
```

But I actually get:

```
[
  "2022-12-05 02:26:36",
  "2022-12-05 02:26:36",
]
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Signature for this method is `subDays(int $value = 1)` it was never meant to support explicitly passing `null` (actually I would highly recommend not to omit the parameter neither, using `subDay()` is in this case is way less ambigous).

It's not crashing because of magic method `__call` used under the hood and legacy limitations. But `addDays(null)` or `subDays(null)` adding/subtracting 1 day is far from being logical.

We might simply throw an exception in the next major version when trying to pass `null` values here because it has no intuitive meaning and is very error-prone. It also become even more dangerous to make such an assertion because it will support `int|float` in 3.x.

Please consider the `$value` parameter of all add/sub methods as mandatory and strictly expecting `int`: `addDays(int $value)` / `subDays(int $value)`, this way, what happen when receiving `null` values is handled by your code explicitly instead of relying on arbitrary behavior from the library, I really think it would benefit to other coders and future you reading the code:

```php
$days = null;
$start = Carbon\CarbonImmutable::now()->subDays($days ?? 1); // Be explicit about what null means in your context
```

**Comment by wokenlex** [comment]
Well... it made a really good chain of problem's from other libs, there they didn't know about it (yet), like in DoctrineExtensions

Good news - now I know what this lib exists :-)

**Comment by kylekatarnls** [comment]
I'm not sure to follow. You mean `DoctrineExtensions` is calling `->subDays()` or `->addDays()` internally? As per the code of the last version I don't see such calls. If they do and the value passed here can be `null` it sounds quite buggy.

Also `DoctrineExtensions` does not require `nesbot/carbon` it does not even `suggests` it in the composer.json, it's only requiring it as a dev-dependency to verify it's compatible with it during unit tests, but it won't install it. If you have Carbon in your app, it would not be because of `DoctrineExtensions`, it must be some other package requiring it.

**Comment by wokenlex** [comment]
Yes, still investigating, right now I already not sure it caused my problem, sorry.

**Comment by dododedodonl** [comment]
@kylekatarnls I ran into this problem today.

In version 2.63.0, `Carbon::now()->addMonths(null)` gives the same result as `Carbon::now()->addMonths(1)`.
Since version 2.64.0 `Carbon::now()->addMonths(null)` gives the same result as `Carbon::now()->addMonths(0)`.

Due to an incorrect `config()` (not set and thus defaulting to null), `Carbon::now()->addMonths(null)` was being called. It took quite some time to find this difference. I'm not sure if this should just be changed in a minor version update, as it can easily result in off-by-one bugs without a specific mention in the changelog.

**Comment by dododedodonl** [comment]
I agree the previous behavior was more harmful. It has silently hidden a bug for at least two years. A type error would indeed be even better. Thank you for the quick response and addition to the release notes!
