### ISSUE TITLE
Wrong return type of change() method in dockblock

### ISSUE THREAD

**Issue by aivchen** [briannesbitt/Carbon#2717]
Hello,

I encountered an issue with the following code:
```php
var_dump(get_class(@Carbon::now()->change('blablabla')));
```

Carbon version: **2.64.0**

PHP version: **8.1**

I expected to get:

```
string(13) "Carbon\Carbon"
```

In dockblock of the `change` method return type is `static` (https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Traits/Modifiers.php#L454). So it can't return false.

But I actually get:

```
TypeError: get_class(): Argument #1 ($object) must be of type object, bool given
```

Thanks!

**Comment by kylekatarnls** [comment]
Thanks.

I would not recommend to use mute operator (`@`) instead prefer to convert error to exception ([see first example here](https://www.php.net/manual/en/language.exceptions.php#language.exceptions.notes), also most framework already do it by default) and catch/work with the exception so you have a type and a precise message to verify the error that happened the one you allow instead of a silent catch-all that can also catch some errors you didn't want to.

But for the PHPDoc as it's documented this way for `DateTime::modify()` in PHP, I'm OK to align. 👌
