### ISSUE TITLE
tr_TR.UTF8 problem

### ISSUE THREAD

**Issue by drtzack** [briannesbitt/Carbon#278]
~~~
setlocale(LC_ALL, 'tr_TR.UTF-8');
require __DIR__.'/bootstrap/autoload.php';
$dt = Carbon\Carbon::now();
print( $dt->formatLocalized('%d %B %Y %A'));
exit(0);
~~~

When I refresh page. Sometimes It shows in Turkish and sometimes in English.
But it's okay when 'tr_TR' but this time result is not UTF8

**Comment by briannesbitt** [comment]
I doubt this is a Carbon issue since this function really just forwards the call on to strftime. To make it work for me (windows) I had to make the locale string just "tr" to get "28 Ìubat 2015 Cumartesi".

I saw this warning on the php site:
Warning
The locale information is maintained per process, not per thread. If you are running PHP on a multithreaded server API like IIS, HHVM or Apache on Windows, you may experience sudden changes in locale settings while a script is running, though the script itself never called setlocale(). This happens due to other scripts running in different threads of the same process at the same time, changing the process-wide locale using setlocale().
