### ISSUE TITLE
Non-Latin Numbers Not Localized Correctly

### ISSUE THREAD

**Issue by tasmynsmale** [briannesbitt/Carbon#2783]
Hello,

When using Carbon to format dates and times, non-Latin numbers are not taken into account when localizing the time. This results in incorrect formatting for languages that use non-Latin numerals, such as Arabic or Hindi.

```php
use Carbon\Carbon;

// Set locale to Arabic
Carbon::setLocale('ar');

// Set date to April 25, 2023
$date = Carbon::create(2023, 4, 25);

// Format the date with time
$formattedDate = $date->format('l، j F Y، h:i A');

echo $formattedDate;

```

Carbon version: **PUT HERE YOUR CARBON VERSION (exact version, not the range)**

PHP version: **PUT HERE YOUR PHP VERSION**

I expected to get:

```
الأحد، ٢٥ أبريل ٢٠٢٣، ١٢:٠٠ صباحًا

```

But I actually get:

```
الأحد، 25 أبريل 2023، 12:00 صباحًا

```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

`ar` does not have the alternative numbers because (as per CLDR) it's not the usage in every `ar` country. However the following locales have it:
- ar_AE
- ar_BH
- ar_EG
- ar_IQ
- ar_JO
- ar_KW
- ar_LB
- ar_OM
- ar_PS
- ar_QA
- ar_SA
- ar_SD
- ar_SY
- ar_YE

And as it's not implemented on date numbers (for now it's only in diffs (such as in "2 years ago"), then you need to replace on the fly with some:
So if you use for instance:

```php
Carbon::setLocale('ar_AE');

$date = Carbon::create(2023, 4, 25);

echo preg_replace_callback(
    '/\d+/',
    static fn (array $match) => $date->translateNumber((int) $match[0]),
    $date->isoFormat('dddd، D MMMM YYYY، hh:mm A')
);
```

You'll get `الثلاثاء، ۲٥ أبريل ۲۰۲۳، ۱۲:۰۰ ص`

I hope this work-around can fit.

Thanks.
