### ISSUE TITLE
[Request] endOfSeason

### ISSUE THREAD

**Issue by foremtehan** [briannesbitt/Carbon#2796]
In a project, I needed a method to cache data until the end of the season, but it seems like we don't have it yet.

I managed to create a macro (in a Laravel app)
```php
Carbon::macro('endOfSeason', function () {
    $seasons = [
        'spring' => ['month' => 3, 'day' => 20],
        'summer' => ['month' => 6, 'day' => 21],
        'fall' => ['month' => 9, 'day' => 22],
        'winter' => ['month' => 12, 'day' => 21],
    ];

    foreach ($seasons as $date) {
        $season = Carbon::parse(date('Y').'-'.$date['month'].'-'.$date['day']);

        $currentDate = now();

        if ($season->equalTo($currentDate)) {
            return $season->addMonths(3);
        }

        $diffDays = $season->diffInDays($currentDate);

        if ($diffDays < 90) {
            if ($currentDate->lessThan($season)) {
                return $currentDate->addDays($diffDays);
            }

            $nextSeasonItem = next($seasons);

            $nextSeason = Carbon::parse(date('Y').'-'.$nextSeasonItem['month'].'-'.$nextSeasonItem['day']);

            return $currentDate->addDays($nextSeason->diffInDays($currentDate));
        }
    }
});
```
but I don't like it, and I'm not even sure if it covers all the issues.

It would be great if we had endOfSeason with better implementation

**Comment by kylekatarnls** [comment]
Hello, as a generic suggestion, I recommend to use `static::this()` instead of `now()`, this way the macro can be used both statically `Carbon::endOfSeason()` and dynamically `Carbon::parse('2024-10-26')->endOfSeason()`.

And `date('Y')` should use `$currentDate->year` (so it also refers to the current object) plus it can be mocked in tests.

The `if ($season->equalTo($currentDate))` sounds wrong to me, as you just add 3 months there, you can ends with day = 20 instead of 21 or the opposite.

Also you get the right date but you keep current time. The end of the season if consistent with the other `endOf*` helpers should be at 23:59:59.999999. An extra `->endOfDay()` should help.

Also it's possible to use a bit more math (take advantage of the fact that the month is always a multiple of 3 so using `% 3` allow to calculate the date without actually trying every season, and so also preparing numbers to create less object.

So this is my proposal for the implementation of this, it will be faster to process and address the issues above:

```php
Carbon::macro('endOfSeason', static function () {
    $now = static::this();
    $firstDaysOfSeason = [
        3 => 20, // spring
        6 => 21, // summer
        9 => 22, // fall
        12 => 21, // winter
    ];
    $dayInCurrentMonth = $firstDaysOfSeason[$now->month] ?? null;

    if ($dayInCurrentMonth && $now->day < $dayInCurrentMonth) {
        return $now->setDay($dayInCurrentMonth - 1)->endOfDay();
    }

    $expectedMonth = ($now->month + (3 - $now->month % 3) - 3) % 12 + 3;
    $expectedDay = $firstDaysOfSeason[$expectedMonth] - 1;
    $expectedYear = $now->year + ($expectedMonth < $now->month ? 1 : 0);

    return $now->setDate($expectedYear, $expectedMonth, $expectedDay)->endOfDay();
});
```

I will take some more time to consider it would be useful to enough people to be worth being part of the lib.

**Comment by kylekatarnls** [comment]
Created a separate library for that, with links for the methods in the official documentation: https://github.com/kylekatarnls/season
