### ISSUE TITLE
Carbon period does not accept intervals smaller than 1

### ISSUE THREAD

**Issue by VitorTS** [briannesbitt/Carbon#2836]
Hello,

I encountered an issue with the following code:

```php
$period = \Carbon\CarbonPeriod::since('2018-04-21 00:00:00')->hours(0.5)->until('2018-04-21 02:00:00');
$timestamps = [];
foreach ($period->toArray() as $date) {
    $timestamps[]= $date->format('Y-m-d H:i:s');
}
var_export($timestamps);
```

Carbon version: **2.66.0**

PHP version: **8.2.4**

I expected to get:

```
array (
  0    '2018-04-21 00:00:00',
  1    '2018-04-21 00:30:00',
  2    '2018-04-21 01:00:00',
  3    '2018-04-21 01:30:00',
  4    '2018-04-21 02:00:00',
)
```

But I actually get:

```
Carbon\Exceptions\InvalidIntervalException with message 'Empty interval is not accepted.'
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

The `hours` method actually set the `h` of the interval of the `CarbonInterval` which is extending `DateInterval`, and as it's an `int` https://www.php.net/manual/en/class.dateinterval.php#dateinterval.synopsis `float` values get truncated.

You can do:

```php
$period = \Carbon\CarbonPeriod::since('2018-04-21 00:00:00')->interval('0.5 hours')->until('2018-04-21 02:00:00');
```
Because in this case the whole interval is parsed and cascaded to smaller units if possible. (While `hours` method is meant to ensure only the `hour` value of the interval can be set.)

Or:
```php
$period = \Carbon\CarbonPeriod::since('2018-04-21 00:00:00')->minutes(0.5 * 60)->until('2018-04-21 02:00:00');
```

For backward-compatibility and because there are acceptable alternative for that. I would opt not to change this behavior.

**Comment by VitorTS** [comment]
@kylekatarnls Thanks for your reply. I'm aware of some alternatives, but in my mind, is a shame that such semantically rich and expressive library has to rely on "workarounds" like putting the interval value and unit into a string, which is not intuitive and has no indication of having a different semantic than `->hour(0.5)`, or going down to a smaller unit that's not the one I'm interested in working with.

**Comment by kylekatarnls** [comment]
Hello, with the version 2.70.0, you can now run

```php
CarbonInterval::enableFloatSetters();
```

on bootstrap to allow decimal numbers in interval setters such as `->hours(0.5)`
