### ISSUE TITLE
Cannot set Hour to 0 in daylight savings day, diffInDays broken?

### ISSUE THREAD

**Issue by christoferd** [briannesbitt/Carbon#2845]
Hello,

I encountered an issue with the following code:

```php
// set date time locale to some place in Chile for the daylight savings issue to occur
Carbon::setLocale('America/Santiago');
$c = Carbon()->parse('2023-09-03 01:00:00');
$c->hour(0);
echo $c->toDateTimeString();
```
Carbon version: 2.68.1

PHP version: 8.1.17

I expected to get:

```
2023-09-03 00:00:00
```

But I actually get:

```
2023-09-03 01:00:00
// NOTE that this is the day that daylight savings changes time.
// startOfDay() sets it to 01:00:00
// I expected to be able to force it to 00:00:00
// If you want to know why, it's because I want to do a diffInDays and it's messing up my calendar!
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello 👋 

Sadly, Carbon is not in control of what happen here because it inherit timezone behavior from `DateTime` and as you can see if you try the code below, having a `DateTime` object for `2023-09-03 00:00:00 America/Santiago` and so as `Carbon extends DateTime` it's not possible neither for a `Carbon` object:

```php
<?php

$d = new DateTime('2023-09-03 01:00:00 America/Santiago');
$d->modify('00:00:00');

echo $d->format('Y-m-d H:i:s e');
```

And actually it's not a bug as the PHP team position on this is to immediately overflow to next valid date if you try to set to a date that does not exist. For instance `->modify('2023-02-30')` will give `2023-03-02` as February 30th does not exist as per the calendar rule. The same way `2023-09-03 00:00:00 America/Santiago` does not exist as per the timezone rule so it converts it to whatever match as closely as possible and exist as per all calendar and timezone rules.

If you are calculating `diffInDays`, you actually don't need to use a particular timezone and so for anything where timezone is not strictly needed and meaningful, then you should stick to UTC:

```php
// Whatever event happened earlier, you should store it in UTC in your DB
// And so you create UTC Carbon object for it:
$event = CarbonImmutable::parse('2023-09-03 04:23:45', 'UTC');

// Let's say you know the user timezone from some request header/input/cookie and you save it in session/variable:
$userTimeZone = 'America/Santiago';

$now = CarbonImmutable::now('UTC');

$eventDateInUserTimeZone = $event->tz($userTimeZone)->format('Y-m-d');
$todayDateInUserTimeZone = $now->tz($userTimeZone)->format('Y-m-d');

$daysDiff = CarbonImmutable::parse($todayDateInUserTimeZone, 'UTC')->diffInDays($eventDateInUserTimeZone);
```
Note 1: as you can see calculation is made in UTC, and you can just replace on a case-by-case basis whatever is the `$userTimeZone`, BTW, the 'UTC' argument can just be removed if you properly set it as your default system and application timezone (you should).

Note 2: `Carbon::setLocale('America/Santiago');` has no effect, the locale is for the language, not for the timezone and `$c = Carbon()->parse('2023-09-03 01:00:00');` is not a valid syntax neither, you're expected to use:
```php
$c = Carbon::parse('2023-09-03 01:00:00 America/Santiago');
```
I strongly recommend you keep UTC as the default timezone any way and work with city timezone only when you need it to output/parse dates to/from users you know are in this timezone, but keep your back-end agnostic of where are user/where it is installed. As this kind of daylight issue is only what of the many problems that you will hit if you try to work with a city timezone for calculations on your backend.

**Comment by christoferd** [comment]
The only way I could get diffInDays to work on daylight savings DST 
was to create a custom function. 

```php
    // Calc how many days since a long time ago for two separate dates and then subtracting one from the other.
    static function diffInDaysOfDateOnly(Carbon &$c, Carbon &$cc): int
    {
        $c01012000 = Carbon::parse('2000-01-01');
        $c01012000->hour($c->format('G')); // 24h without leading zeros
        $c01012000->minutes($c->format('i'));
        $c01012000->seconds($c->format('s'));
        $diff = $c01012000->diffInDays($c);
        $c01012000->hour($cc->format('G'));
        $c01012000->minutes($cc->format('i'));
        $c01012000->seconds($cc->format('s'));
        $diff2 = $c01012000->diffInDays($cc);
        // dump( "diffs: $diff2 - $diff = ".($diff2-$diff));
        return ($diff2-$diff);
    }
```

I tried a few different ways, but this was the only one that passed all my tests for the situation I was in.

**Comment by kylekatarnls** [comment]
Not sure I fully understand but the problem will actually depends which is the skipped hour in the timezone you pick, some TZ change at midnight, some at 1AM, some at 2AM. As it's typically during night, you should be safe comparing dates at noon, but an even safer way is to use UTC which does not suffer those ~~stupid~~ smart DST changes:

```php
    static function diffInDaysOfDateOnly(Carbon $c, Carbon $cc): int
    {
        return Carbon::parse($c->format('Y-m-d'), 'UTC')->diffInDays($cc->format('Y-m-d'));
    }
```

That also allow to have a way shorter (and more readable IMO) code.

Side note: remove `&`, you very likely don't want to change those variables as you are just calculating a diff.
