### ISSUE TITLE
UnknownGetterException on serialization

### ISSUE THREAD

**Issue by gjespo85** [briannesbitt/Carbon#2850]
Hello,

I encountered an issue with the following code in Serialization.php file:

```php
    public function __serialize(): array
    {
        // @codeCoverageIgnoreStart
        if (isset($this->timezone_type)) {
            return [
                'date' => $this->date ?? null,
                'timezone_type' => $this->timezone_type,
                'timezone' => $this->timezone ?? null,
            ];
        }
    ...
```
Package Laravel: nesbot/Carbon v2.70.0
Carbon version: 2.70.0
PHP version: 8.1.23
Laravel version: 10.23.0

The 
```php
$this->timezone_type
```
and the
```php
$this->date
```
not work properly and they throws an UnknownGetterException in Date Trait get() method because only 
```php
$this->getTimezone()->getType();
```
returns a timezone_type value and only a 
```php
$this->format("Y-m-d H:i:s.u");
```
returns the full date value with microseconds.

Can you resolve this issue or tell me what i can do?

**Comment by kylekatarnls** [comment]
Please give the code you run in your application (not the code frim this library) as a minimum chunk of code to use to reproduce your issue and give the output you expect from it, so we can check it matchrs the common expectation and that it can be fixed in a way that will return what you need.

Thanks.
