### ISSUE TITLE
Feature: add `weekdays` support to CarbonInterval

### ISSUE THREAD

**Issue by Nielsvanpach** [briannesbitt/Carbon#2855]
Hi there,

I would like to propose a new feature for Carbon. Currently, CarbonInterface allows us to work with weekdays using the `Carbon::addWeekdays()` method. However, when it comes to CarbonInterval, this functionality is missing. I believe implementing this feature could be quite beneficial, especially in scenarios like the one illustrated below:

```php
public function totalSeconds(int $length, string $unit = 'days'): int
{
    $interval = CarbonInterval::$unit($length);

    return $interval->totalSeconds;
}

now()->add($this->totalSeconds(5)); // should add 5 days
```

In the code snippet above, the `$unit` parameter can take values like 'minutes,' 'hours,' 'days,' and more. However, there's currently no support for weekdays. Here's what I have in mind:

```php
$interval = CarbonInterval::weekdays(5);

now()->add($interval); // should add 7 days
```

A less ideal workaround could look like this:

```php
$fullWeeks = (int) floor($length / 7);
$weekendDaysInInterval = $fullWeeks * 2;

for ($i = 0; $i < ($length % 7); $i++) {
    $date = (new CarbonImmutable())->addDays($fullWeeks * 7 + $i);

    if ($date->isWeekend()) {
        $weekendDaysInInterval++;
    }

    if ($i === ($length % 7) && $date->isSaturday()) {
        $weekendDaysInInterval++;
    }
}

return CarbonInterval::days($length + $weekendDaysInInterval);
```

I don't have deep knowledge of this topic, so I'm uncertain if this feature is easy to implement.
Nevertheless, I appreciate your consideration of this feature and I'm interested to hear what you think.

----

Carbon version: **2.70.0**
PHP version: **8.2**

**Comment by kylekatarnls** [comment]
Hello, 👋 

I think it's the wrong tooling for that, because:

For instance, what would be the result of:
```php
CarbonInterval::weekdays(2)->totalDays
```

Actually it depends. Starting on Tuesday, it's 2, starting on Friday, it's 4. 🤷

A `CarbonInterval` object is not bound to any date, it's only an amount of time that you can put anywhere. We already have this issue with month and have to take an approximation to cascade months to days. With weekday, the approximation would be so huge that I don't even think it makes sense.

Because it needs a start point to actually work dynamically with any number of days, I would not try to be smart and implicitly choose an arbitrary start with the risk users don't understand what's done under the hood.

Instead I would encourage to explicitly write in code what is the start point taken:

```php
$startPoint = '2023-10-23 00:00:00.0';
$interval = CarbonImmutable::parse($startPoint)->diffAsCarbonInterval("$startPoint + 5 weekdays");
```

Side note about `now()->add($this->totalSeconds(5));` why having a function for that? And why stepping by seconds, why not adding the days directly and explicitly?

```php
$unit = 'days';
$length = 5;

now()->add(CarbonInterval::$unit($length));
```

Or even simpler:
```php
now()->add($length, $unit);
```
