### ISSUE TITLE
CarbonPeriodImmutable use Carbon::setTestNow() value instead of CarbonImmutable::setTestNow()

### ISSUE THREAD

**Issue by EraTorr** [briannesbitt/Carbon#2874]
Hello,

I encountered an issue with the following code:

```php
\Carbon\CarbonImmutable::setTestNow('2023-05-01');
\Carbon\CarbonPeriodImmutable::create('23:30', \Carbon\CarbonImmutable::parse('23:30')->addMinutes(30));
```

Carbon version: 2.71.0

PHP version: 8.2.10

I expected to get: 
**Discrepancy in startDate**

```
Carbon\CarbonPeriodImmutable {#6979
    dateClass: "Carbon\CarbonImmutable",
    dateInterval: Carbon\CarbonInterval {#6970
      interval: + 1d,
    },
    isDefaultInterval: true,
    filters: [
      [
        [
          "Carbon\CarbonPeriod",
          "filterEndDate",
        ],
        null,
      ],
    ],
    startDate: Carbon\CarbonImmutable @1698269400 {#6971
      date: 2023-05-01 23:30:00.0 Europe/Paris (+02:00),
    },
    endDate: Carbon\CarbonImmutable @1682978400 {#6972
      date: 2023-05-02 00:00:00.0 Europe/Paris (+02:00),
    },
    options: 4,
  }

```

But I actually get:

```
Carbon\CarbonPeriodImmutable {#6979
    dateClass: "Carbon\CarbonImmutable",
    dateInterval: Carbon\CarbonInterval {#6970
      interval: + 1d,
    },
    isDefaultInterval: true,
    filters: [
      [
        [
          "Carbon\CarbonPeriod",
          "filterEndDate",
        ],
        null,
      ],
    ],
    startDate: Carbon\CarbonImmutable @1698269400 {#6971
      date: 2023-10-25 23:30:00.0 Europe/Paris (+02:00),
    },
    endDate: Carbon\CarbonImmutable @1682978400 {#6972
      date: 2023-05-02 00:00:00.0 Europe/Paris (+02:00),
    },
    options: 4,
  }

```

I made some test by doing the following 
```php
\Carbon\Carbon::setTestNow('2023-05-01');
\Carbon\CarbonImmutable::setTestNow('2023-05-01');
\Carbon\CarbonPeriodImmutable::create('23:30', \Carbon\CarbonImmutable::parse('23:30')->addMinutes(30));
```

The result is the expected one. 
Giving me a `startDate: 2023-05-01 23:30:00.0 Europe/Paris (+02:00)`

I know `CarbonPeriodImmutable` extends `CarbonPeriod` but shouldn't he use the value set by `\Carbon\CarbonImmutable::setTestNow()` instead of the one set by `\Carbon\Carbon::setTestNow()` ?

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Issue understood.

Indeed `CarbonPeriod` is using `Carbon::` to create intermediate date instead of using it's $dateClass dynamically:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/CarbonPeriod.php#L2688

We'll change that.

For the record, I recommend to keep all your time system synchronized in tests, the reason is that in prod/real life, you should never have different components of your app using inconsistent times.

For instance if you also use Symfony clock, it's relevant to mock synchronously `Carbon`, `CarbonImmutable` on it:
```php
Carbon::setTestNow(static fn () => new Carbon(Clock::get()->now()));
CarbonImmutable::setTestNow(static fn () => new CarbonImmutable(Clock::get()->now()));

// Now when you mock/change the Symfony clock, Carbon will use it too
Clock::set(new MockClock());
```

If you use only `Carbon`, then you can synchronize both like this:
```php
Carbon::setTestNow(static fn () => CarbonImmutable::now()->toMutable());

CarbonImmutable::setTestNow('2023-05-01'); // Will also apply this date to Carbon
```

[`Carbonite`](https://github.com/kylekatarnls/carbonite) which add some more time mocking tooling [also synchronize both Carbon and CarbonImmutable and can drive other clocks](https://github.com/kylekatarnls/carbonite#example-with-psr-20-clock-and-frameworks-such-as-symfony)
