### ISSUE TITLE
October DST issue with diffInRealSeconds

### ISSUE THREAD

**Issue by ageshev** [briannesbitt/Carbon#2876]
Hello,

I encountered an issue with the following code:
```php
$startsAt = Carbon::parse('2023-10-29 00:00:00')->subDay()->addDay();
$endsAt = Carbon::parse('2023-10-29 01:00:00')->subDay()->addDay();

// outputs 3600
echo $startsAt->diffInRealSeconds($endsAt);

$startsAt = Carbon::parse('2023-10-29 00:00:00');
$endsAt = Carbon::parse('2023-10-29 01:00:00');

// outputs 7200
echo $startsAt->diffInRealSeconds($endsAt);
```

Carbon version: 2.71.0

PHP version: 8.2.11

I expected to get:
The same result from both, but I don't understand why there is a difference

Thanks!

**Comment by kylekatarnls** [comment]
Hello, both output `3600` when `date_default_timezone_set('UTC')` or even with a timezone having DST such as `date_default_timezone_set('Europe/Paris')`

Please provide your timezone to make it reproducible.

By the way it's a bad practice to have anything else but UTC as default timezone server-side, timezone is part of the user context to be applied on input/output operation for a given user or to process an isolated calculation in user context, but this should be done explicitly and scoped to isolated functions needing it, not by changing globally the application/server default timezone.

**Comment by ageshev** [comment]
Hi @kylekatarnls ,
Our default timezone is Europe/London. Please let me know if I can help with anything else.

**Comment by kylekatarnls** [comment]
Hello, you can see what issue by dumping the timezone short name:
```php
$startsAt = Carbon::parse('2023-10-29 00:00:00')->subDay()->addDay();
$endsAt = Carbon::parse('2023-10-29 01:00:00')->subDay()->addDay();

echo $startsAt->format('Y-m-d H:i T') . "\n";
echo $endsAt->format('Y-m-d H:i T') . "\n";
echo $startsAt->diffInRealSeconds($endsAt) . "\n";

$startsAt = Carbon::parse('2023-10-29 00:00:00');
$endsAt = Carbon::parse('2023-10-29 01:00:00');

echo $startsAt->format('Y-m-d H:i T') . "\n";
echo $endsAt->format('Y-m-d H:i T') . "\n";
echo $startsAt->diffInRealSeconds($endsAt) . "\n";
```

```
2023-10-29 00:00 BST
2023-10-29 01:00 BST
3600
2023-10-29 00:00 BST
2023-10-29 01:00 GMT
7200
```

Even if we'd like to change the behavior here, it's not on Carbon side, you get the exact same result working with pure `DateTime`:
```php
$startsAt = (new DateTime('2023-10-29 00:00:00'))->modify('-1 day')->modify('+1 day');
$endsAt = (new DateTime('2023-10-29 01:00:00'))->modify('-1 day')->modify('+1 day');

echo $startsAt->format('Y-m-d H:i T') . "\n";
echo $endsAt->format('Y-m-d H:i T') . "\n";
echo ($endsAt->getTimestamp() - $startsAt->getTimestamp()) . "\n";

$startsAt = new DateTime('2023-10-29 00:00:00');
$endsAt = new DateTime('2023-10-29 01:00:00');

echo $startsAt->format('Y-m-d H:i T') . "\n";
echo $endsAt->format('Y-m-d H:i T') . "\n";
echo ($endsAt->getTimestamp() - $startsAt->getTimestamp()) . "\n";
```

PHP `DateTime` switch from GMT to BST when `->modify('-1 day')` but not back from BST to GMT when `->modify('+1 day')`.

It's actually not really a bug. You're working with `Europe/London` so when you ask for `2023-10-29 01:00` you implicitly ask for `2023-10-29 01:00 Europe/London` but as it uses named timezone (London) and not offset timezone (GMT or GMT+1).

And due to DST, `2023-10-29 01:00 Europe/London` actually happen twice (once at `2023-10-29 00:00 UTC` and a second time at `2023-10-29 01:00 UTC`)

PHP won't keep track of what was the initial timezone. When it starts from `2023-10-29 01:00 GMT` -1 day = -25 hours (the DST is inside the interval), but then when starting from `2023-10-28 01:00 BST`, +1 day = +24 hours (it uses the default day interval because DST is after the interval, so no particular reason to include it yet).

If PHP or us would try to smartly guess if we should include the DST-hour when it's just after or just before an added/subtracted interval, it might be more convenient for some users but it would surely also break flows for many users.

There is no way to be correct with a time information that can mean two different moments. The bug is not how PHP handles the DST, DST is the bug to be removed, it happened in several countries that used to have it, it's likely to eventually happen in all countries still using it.

With or without DST, the recommendation remains: it's not good to have anything else but `UTC` as your default application timezone. UTC is also the best way to transmit date infos: to save them in your DB or to pass it in a JSON, for instance Carbon objects in a JSON would be converted into `2023-10-29T01:00:00Z` which will be properly localized by most of the languages/devices, such as in JS `new Date("2023-10-29T01:00:00Z")` will convert this into the proper timezone set on the current device.
