### ISSUE TITLE
[Translation tool] sk_SK,cz_CZ,sv_SE

### ISSUE THREAD

**Issue by miso93** [briannesbitt/Carbon#2880]
|English|sk_SK|comments|
|--|--|--|
|Jan|jan|Jan|
|Feb|feb|Feb|
|Mar|mar|Mar|
|Apr|apr|Apr|
|May|máj|Máj|
|Jun|jún|Jún|
|Jul|júl|Júl|
|Aug|aug|Aug|
|Sep|sep|Sep|
|Oct|okt|Okt|
|Nov|nov|Nov|
|Dec|dec|Dec|

|English|cz_CZ|comments|
|--|--|--|
|Jan|jan|Led|
|Feb|feb|Úno|
|Mar|mar|Bře |
|Apr|apr|Dub|
|May|máj|Kvě|
|Jun|jún|Čvn|
|Jul|júl|Čvc|
|Aug|aug|Srp|
|Sep|sep|Zář|
|Oct|okt|Říj|
|Nov|nov|Lis|
|Dec|dec|Pro|

|English|sv_SE|comments|
|--|--|--|
|Jan|jan|Jan|
|Feb|feb|Feb|
|Mar|mar|Mar|
|Apr|apr|Apr|
|May|máj|Maj|
|Jun|jún|Jun|
|Jul|júl|Jul|
|Aug|aug|Aug|
|Sep|sep|Sep|
|Oct|okt|Okt|
|Nov|nov|Nov|
|Dec|dec|Dec|

----
When I use `j M Y` date format together with `translatedFormat` method I expect to have short month to be capital as it is in english version and also here https://www.php.net/manual/en/datetime.format.php

**Comment by kylekatarnls** [comment]
Hello, it's capitalized in English because it's a grammar rule in English that months and week days are always capitalized. `monday` does not exist in English, it's literally underlined by my spellchecker as I type it here.

The same will happen in German as any noun need to start with an uppercase.

However it's not the case in Slovakian:
https://glosbe.com/en/sk/Monday
![Sans titre](https://github.com/briannesbitt/Carbon/assets/5966783/762c1c64-b32c-49c0-b058-cc24af611c91)

This is the reason for the bold warning that appear before days on months on the translation contribution page:

> Warning, do not uppercase the first letter if it's not required, days/months are always uppercase in English, so "Monday" is written this way even in a sentence like "See you Monday", please translate the following as if it could be in the middle of such sentences. Short versions are used in short date formats and minimalist days are used calendar headings and such custom usages.

Following strictly the grammar rules you should not capitalize it unless it's the beginning of a sentence.

But Carbon cannot know if it will be used in such context, so if you need capitalization, you should apply at a higher level using `ucfirst()` on the whole sentence for instance.

Thanks,
