### ISSUE TITLE
PHPStan interface mismatch

### ISSUE THREAD

**Issue by CalebDW** [briannesbitt/Carbon#2887]
Hello,

Running PHPStan on my project yields the following error:

![image](https://github.com/briannesbitt/Carbon/assets/4176520/3735a90c-8aeb-40c0-9c76-2fced3dc0e57)

Carbon: 2.71.0
PHPStan 1.10.43
Thanks!

**Comment by buffcode** [comment]
In the reversal commit https://github.com/phpstan/phpstan-src/commit/d0c09389bcbb65a0d5ec8a12987c55e04eec0f2f of https://github.com/phpstan/phpstan-src/commit/ad6703d253edbda410c23627bc93cbe76cf049a6 the nullable types were removed.

before:
```php
BuiltinMethodReflection::getReflection(): ?ReflectionMethod
```

after:
```php
BuiltinMethodReflection::getReflection(): ReflectionMethod
```

Not sure if this was intended.

**Comment by Temepest74** [comment]
+1

**Comment by kylekatarnls** [comment]
Because extending the macro class was the only way to support properly Carbon macro, even some patches in PHPStan updates can be breaking changes it and it's hard to be compatible with new version without dropping the previous versions (which if we proceed to fast also raises complains).

I'm open to pull-request that would fix this while still supporting PHPStan from 1.10.20 to 1.10.43.

**Comment by kylekatarnls** [comment]
Side note to people adding comments/reactions not helping fixing the issue.

As a open-source provided to you for free, there is no obligation for anyone to immediately jump and fix something. Mostly if the bug was introduced by another library, and mostly if it's not a core feature.

Carbon core feature is enhancing `DateTime` PHP class with human-friendly methods. The support of PHPStan analysis is a nice-to-have side-feature.

All you have via OSS out of the box is quite a miracle, but it's still not a reason to expect everything you need to get done by someone else. If you want it, you can get your hands dirty and craft the pull-request.

**Comment by buffcode** [comment]
See comment: https://github.com/phpstan/phpstan-src/commit/d0c09389bcbb65a0d5ec8a12987c55e04eec0f2f#r133136268

> Hi, please note that I reverted this as a courtesy to nesbot/carbon package. You shouldn't be interested in this interface because it's not part of the backward compatibility promise: https://phpstan.org/developing-extensions/backward-compatibility-promise
> 
> It will be removed in the future.
> 
> Please open a discussion with your use-case and I'll guide you what to replace the usage with.

**Comment by kylekatarnls** [comment]
Hello, I won't personally invest time in this. If this get removed with no alternative and no one proposed another way to support analysis for the macro methods, then we'll just remove the PHPStan extension from Carbon, and we'll delegate that to whoever is interested in building a library for that.

I have to be a bit picky with what we support because every piece asked/added even when it's done by another volunteer contributor typically ends with maintenance burden on core team.

**Comment by buffcode** [comment]
@kylekatarnls Is it viable to extract this functionality into a separate package? This way it won't affect the core package and maintenance could (or could not) progress separately.

I'm not too much into the PHPStan internals and don't know, if this must reside in the `nesbot/carbon` package or could be supplied by a third-party package.
