### ISSUE TITLE
Error parsing narrow no-break space.

### ISSUE THREAD

**Issue by cthorne91** [briannesbitt/Carbon#2895]
Hello,

I encountered an issue with the following code:

```php
Carbon::parse("2023-11-22 6:51:34 am");
```
It's important to note that the space between the seconds and the 'am' is a narrow no-break space. An easier way to see what I mean is with this:

```php
Carbon::parse(urldecode("2023-11-22%206%3A51%3A34%E2%80%AFam"));
```

From my understanding, as of iOS 17, dates are no longer formatted with a standard space but rather with a narrow no-break space. My clients are submitting these formatted dates and my backend is unable to parse. More information [here](https://developer.apple.com/forums/thread/731850).

Carbon version: **2.72.0**

PHP version: **8.1.26**

I expected to get:

```
an instance of Carbon that references 2023-11-22 6:51:34 am
```

But I actually get:

```
Carbon\Exceptions\InvalidFormatException Could not parse '2023-11-22 6:51:34 am': Failed to parse time string (2023-11-22 6:51:34 am) at position 18 (?): Unexpected character.
```

![Screenshot 2023-12-05 at 7 38 30 AM](https://github.com/briannesbitt/Carbon/assets/1942641/f819fe88-cd68-4d2a-8a03-9b6cf86195cb)

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I can reproduce with PHP 8.1, but it's now fixed in PHP >= 8.2.

And the same behavior will happen with `new \DateTime(urldecode("2023-11-22%206%3A51%3A34%E2%80%AFam"))`, Carbon just inherit this behavior.

So I would not add tricks to replace if from inside Carbon, you can upgrade to latest stable PHP version to get rid of this issue, it can also easily be worked around on your side by replacing any kind of space you might get with a normal space:

```php
$date = "2023-11-22 6:51:34 am";
$date = preg_replace('/[\s ]/', ' ', $date);
Carbon::parse($date);
```

Thanks,
