### ISSUE TITLE
CarbonInterval Issue

### ISSUE THREAD

**Issue by proilyxa** [briannesbitt/Carbon#2898]
Why is this

CarbonImmutable::parse('2023-11-09 20:12:18+00')->diffAsCarbonInterval(CarbonImmutable::parse('2023-12-08 20:12:18+00'))->totalHours

is larger than this is 

CarbonImmutable::parse('2023-11-08 20:12:18+00')->diffAsCarbonInterval(CarbonImmutable::parse('2023-12-08 20:12:18+00'))->totalHours

**Comment by kylekatarnls** [comment]
Hello,

It's because `diffAsCarbonInterval` produce an interval that does not remember which dates created it.

- `2023-11-08 - 2023-12-08` => `CarbonInterval::month(1)`
- `2023-11-09 - 2023-12-08` => `CarbonInterval::days(29)`
- `2023-11-09 - 2023-12-09` => `CarbonInterval::month(1)`

And default length for 1 month is 4 weeks.

You can change the default length using `CarbonInterval::setCascadeFactors()`

For difference based on the actual dates, it's better to use `diffInHours()`
