### ISSUE TITLE
carbon 3 spec method return values differ from 2 when timezone is set

### ISSUE THREAD

**Issue by sakarikl** [briannesbitt/Carbon#2902]
Hello,

I encountered an issue with the following code:

```php
$seconds = 1267200;

$zone = new \DateTimeZone('Europe/Helsinki');
$currentTime = Carbon::create(2022, 10, 17, 12, 1, 10);
$currentTime->setTimezone($zone);

$now = new CarbonImmutable($currentTime);
$end = $now->addSeconds($seconds);

$duration = $now->diffAsCarbonInterval($end);

$duration->roundMinutes();

echo $seconds . ' : ' . $duration->spec() . \PHP_EOL;
```

output for 3:

```
1267200 : P14DT15H

```

output for 2:

```
1267200 : P14DT16H

```

Results differ with one hour when timezone is set

Carbon 3 version: cc423b87ec22a4da922578817730e1b80ed411e1 from dev branch

AND 

Carbon 2 version:  2.71.0

PHP version: 8.2.13

**Comment by sakarikl** [comment]
DST change happens in the middle of that duration.

**Comment by kylekatarnls** [comment]
Output for v2 was wrong, and v3 corrected the bug, because in Helsinki timezone, the 29th is a 25-hour long day.

If you want to get `14 days 16 hours` from `1267200 seconds` it implies that you actually don't care about the timezone nor about whatever is the value of `$currentTime` and you can just get it from any arbitrary UTC reference point:

```php
$seconds = (14 * 24 + 16) * 3600;

$start = CarbonImmutable::parse('2000-01-01 UTC');
$end = $start->addSeconds($seconds);

$duration = $start
    ->diffAsCarbonInterval($end)
    ->roundMinutes();

echo $seconds . ' : ' . $duration->spec() . \PHP_EOL;
```
