### ISSUE TITLE
Taiwan is NOT the Province of China

### ISSUE THREAD

**Issue by thou9787** [briannesbitt/Carbon#2956]
<h1>A widely-used open-source package SHOULD NOT be tainted by political colors.</h1>

https://github.com/briannesbitt/Carbon/blob/2cb4131b3d7b58d54f35209b225d0398fae7eb4a/src/Carbon/List/regions.php#L245
```diff
- 'TW' => 'Taiwan, Province of China',
+ 'TW' => 'Taiwan,'
```

**Comment by kylekatarnls** [comment]
Hello,

For the record there is no intent of denying Taiwan as being an autonomous country.

This data comes from https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes which is supposed to be reliable but it's obviously a complex matter to be neutral.

As per what is written there:

> The Republic of China controls Taiwan. The People's Republic of China claims Taiwan as its Taiwan Province. In deference to the People's Republic of China, the United Nations refers to Taiwan as Taiwan, Province of China.

I'm not familiar with the political situation, I assume you live there and know better how the people feel about unification, independence, or all the other options in between. I sincerely stand with Taiwan people and wish that they can decide their own fate in a democratic way, free of pressure from neither RoC government or any other foreign influence.

I would last add that "China" in this suffix is (as far as I understand it) not referring to the country government of the RoC but to a geographic area and as no meaning of subordination to another country.

That being said, I would agree to remove this suffix, because either one would be more in favor of the independence or unification, when wanting to know what the ISO code stands for, knowing TW is Taiwan is enough and the rest is superfluous.

**Comment by guandeng** [comment]
Taiwan is not a country

**Comment by guandeng** [comment]
Please correct Taiwan is not an autonomous country

**Comment by edwinhuish** [comment]
@kylekatarnls I think Corsica is an autonomous country. Can you modified the translation about that??

**Comment by bubaishaolong** [comment]
I think Texas is an autonomous country. Can you modified the translation about that??

**Comment by edwinhuish** [comment]
> Guiana is another country, there is an ambiguity if we don't specify which one we're talking.

As you said before, Guiana does't have "ISO code",  SO WHAT AMBIGUITY ARE YOU TALKING ABOUT?

> Saint Martin is an island with 2 parts, so it's also ambiguous if we remove the part suffix.

SAME AS ABOVE

> Polynesia contains multiple islands not all belonging to the code PF

SAME AS ABOVE

> But when we talk about "Taiwan", it's unambiguous enough. When I look into Google Maps I don't see "Province of China" written:

What basis is there to prove that WIKI is wrong and Google Maps is right? 
I had this and more: https://en.wikipedia.org/wiki/Three_Communiqu%C3%A9s show me yours?


I have no intention of arguing with you about political power.  Although many countries and peoples live under French pressure and influence.

**Comment by kylekatarnls** [comment]
Guy, it's just bad faith here, we have `'RE' => 'Réunion',` and anybody in Réunion or Metropolitan France would just feel completely awkward about naming it "Réunion, department of France".

> Although many countries and peoples live under French pressure and influence.
I don't deny that, and that's why I would be completely open to discussion if I received name change suggestions from people living there as I said.

**Comment by edwinhuish** [comment]
I'm not interested in France's territorial designations at all.

Also I don't mind you said "Taiwan", it's unambiguous enough.

BUT! I DO CARE, **Taiwan is part of China !!**

And your word: "_I sincerely stand with Taiwan people and wish that they can decide their own fate in a democratic way, free of pressure from neither RoC government or any other foreign influence._", 

**IT'S TOTALLY WRONG! Our government has never influenced Taiwan. On the contrary, it provides various preferential policies that even ordinary people in mainland China do not have. If you don’t know, please don’t make random nonsense.  (PS: What do you feeling when I said that other countries live under the intimidation of France. )**

**Comment by edwinhuish** [comment]
Mainland China and Taiwan are more like East Germany and West Germany in the last century. They were separated because of the war, but they are the same country, the same ancestors, and the same nation. Finally there will be unity in the fureture one day.
