### ISSUE TITLE
Can't get the UTC+0 timestamp

### ISSUE THREAD

**Issue by jevantang** [briannesbitt/Carbon#2960]
Laravel Version: 11.0.3

Carbon Version: 3.0.2

PHP Version: 8.2.16

Database Driver & Version: MySQL 5.7.44 for Ubuntu 22

### Description

I've tried three methods and I can't get the UTC+0 timestamp.

The time value is correct until it is converted to a timestamp.

### Steps To Reproduce

```php
$now = now('UTC');
$nowTimestamp = $now->getTimestamp();
```

```php
$nowTimestamp = time();
```

```php
$now = now('UTC');
$nowTimestamp = strtotime($now);
```

**Comment by kylekatarnls** [comment]
This report miss the actual and expected results you want. `->getTimestamp()` is returning the timestamp and the timestamp is always UTC+0 (by definition it's the number of seconds since January 1st 1970 00:00 UTC, so it cannot be anything else than UTC+0).

If you get different values for `now('UTC')->getTimestamp()` and `time()` double-check that you're not mocking time using `Carbon::setTestNow()` or travel utils of Laravel.
