### ISSUE TITLE
isSameUnit not working like in previous versions and accepting "null" as argument

### ISSUE THREAD

**Issue by glamorous** [briannesbitt/Carbon#2965]
Hello,

I encountered an issue with the following code:

```php
$myDay = null;
echo Carbon::parse('2018-06-01')->isSameDay($myDay);
```

Carbon version: **3.1.1**

PHP version: **8.3**

I expected to get:

```
true
```

But I actually get:

```
Carbon\\Carbon::isSameUnit(): Argument #2 ($date) must be of type DateTimeInterface|string, null given
```

It seems that "null" is not allowed anymore but it's still in Carbon\Carbon.php as comment and argument in the docs.

Thanks!

**Comment by glamorous** [comment]
I just tested it with v3.x-dev an there it works (again)!

**Comment by kylekatarnls** [comment]
Hello, I confirm this is expected since PHPDoc types were turned into concrete type: https://github.com/briannesbitt/Carbon/commit/c65082903bdcd83ec68b931500ba9c2505825951

All the `isSame*` method will now only accept non-option `DateTimeInterface|string $date` parameter.

I will align the PHPDoc.

**Comment by kylekatarnls** [comment]
Documentation fixed in [e7c9d37](https://github.com/briannesbitt/Carbon/commit/e7c9d37931f6490077e3f186e0cfc5b6df272a88)

**Comment by glamorous** [comment]
> Hello, I confirm this is expected since PHPDoc types were turned into concrete type: [c650829](https://github.com/briannesbitt/Carbon/commit/c65082903bdcd83ec68b931500ba9c2505825951)
> 
> All the `isSame*` method will now only accept non-option `DateTimeInterface|string $date` parameter.
> 
> I will align the PHPDoc.

Don't want to offend you, but that's a breaking change since Carbon 2.x version and has nothing to do with the strict type change because in the commit you've shared, In the referenced commit the change was made to have al fallback for isNext (for passing null), but the same fallback wasn't added to isSame

https://github.com/briannesbitt/Carbon/commit/c65082903bdcd83ec68b931500ba9c2505825951#diff-ede373ba22ef24bd43ba5f8bbc290b90d23d78caf63b8c75cb0971534df3da4bR2707

So changing the docs will indeed align the docs with the behaviour, but that will make a breaking change and in my opion nothing to do with "strict types"

**Comment by glamorous** [comment]
To my defense it was used like this:

`$formatPattern = $this->start_initial->isSameDay($this->end_initial) ? 'H:i' : 'd/m H:i';`

Where my workaround/fix now is:

`$formatPattern = $this->start_initial->isSameDay($this->end_initial ?? now()) ? 'H:i' : 'd/m H:i'`

because the `end_initial` is a Carbon but can also be null. So because it was supported in 2.x I assumed i could just use it off course. The workaround works too, but feels a bit more "ugly" 🤷

**Comment by kylekatarnls** [comment]
No, it's not ugly at all! That's way cleaner because in the first code you have a completely non obvious implicit knowledge that `$this->end_initial === null` means "ending now". Other business cases could give to `null` a completely different meaning (such as "never ends", "end not yet decided or calculated", "end not known")

For the record `$this->end_initial ?? 'now'` would also work as the functions accepts string representing date-time.

With your new code, new developers and your future you no longer have to guess and remember this implicit rule as it's made explicit.

You can find a lot of articles telling you why returning null or giving a specific meaning to null values is typically considered like a bad practices for many other reasons. And comparing `null` to another value is one of those code smells which does not just apply to dates but also to any other objects or scalar values.
