### ISSUE TITLE
Carbon v3 diffInDays is not consistent

### ISSUE THREAD

**Issue by rbzachary** [briannesbitt/Carbon#2971]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::parse('2024-03-01', "America/New_York")->addDays(10)->diffInDays(Carbon::parse('2024-03-01', "America/New_York"));
echo Carbon::parse('2024-04-01', "America/New_York")->addDays(10)->diffInDays(Carbon::parse('2024-04-01', "America/New_York"));
```

Carbon version: **3.1.1**

PHP version: **8.1.23**

I expected to get:

```
-10
-10
```

But I actually get:

```
-9.9583333333333
-10
```

So, technically it is correct that it is fewer than 10 days between midnight on March 1 and March 11 in Eastern Time; however there are situations where you are dealing with 2 dates where you want to get the difference between the two and it isn't always obvious why you aren't getting the correct results.

Thanks!

**Comment by ankurk91** [comment]
I see different results as well in Laravel

Laravel 10 with Carbon 2
```php
> now()->addMonths(12)->diffInMinutes(now())
= 525599
```

Laravel 11 with Carbon 3
```php
> now()->addMonths(12)->diffInMinutes(now())
= -525599.99999737
```

Notice carbon 3 results in negative value

**Comment by kylekatarnls** [comment]
Hello @ankurk91 it's a different concern.

The difference in the original post above happen because of daylight saving time (I'm currently evaluating how to best handle that so the result may change in the future).

Your difference is expected, in Carbon 2, the diff was always `int` (truncated down) and by default `$absolute = true` so you don't have the notion of which date is earlier, in Carbon 3 the entire value including sign, decimal part is kept and so you can decide on your side what you want or not.

> P.S - All of diff methods are resulting in negative values

No `$a->diffInMinutes($b)` returns negative values only if `$a > $b`

If you want absolute value, you can use one of the any of the options below:
```php
$value = now()->diffInMinutes(now()->addMonths(12));
$value = now()->addMonths(12)->diffInMinutes(now(), true);
$value = abs(now()->addMonths(12)->diffInMinutes(now()));
```

Then from this `$value` if you don't want the decimal part, it's up to you to decide if you prefer: `floor($value)`, `round($value)` or `ceil($value)`.

**Comment by zachweix** [comment]
Thank you for this, and also for taking care of it so quickly

**Comment by rbzachary** [comment]
Thank you for this, and also for taking care of it so quickly

**Comment by helderneves91** [comment]
Hi, is this actually resolved? I'm facing the same issue with v3 up-to-date.

**Comment by kylekatarnls** [comment]
The initial issue post is indeed fixed. Other topics was discussed in this thread, so I suggest you open a new issue with all the infos required by the issue template to inspect it.
