### ISSUE TITLE
Feature request: auto convet to int on diffIn* methods

### ISSUE THREAD

**Issue by sts-ryan-holton** [briannesbitt/Carbon#2977]
Hi, I'm wondering whether you can automatically convert to `(int)` on the `diffIn*` methods as per the [upgrade guide](https://carbon.nesbot.com/docs/#api-carbon-3)?

I'm finding myself constantly putting `(int)` before them like:

```php
(int) $after->diffInSeconds($before, true)
```

**Comment by kylekatarnls** [comment]
Hello,

No we actually want you to be aware and in control of the truncation.

On Carbon 2, we constantly had issues raised about problem with codes such as:
```php
$after = Carbon::now();
$before = Carbon::now()->subSeconds(2);

echo $before->diffInSeconds($after);
```
Where users complained: why do I get `1`, it's obviously `2`, and actually it's `1.999` because the code is not ran instantly and few microseconds elapsed between the 2 calls of `Carbon::now()`.

Now by always getting a floating number it's made clear that calculation is microsecond-precise and that developers must account for the actual time the code takes to run.

At this point different users may have different expectations on how to get an `int` out of this `float`, depending on the use case, one may prefer `floor()`, `ceil()` or `round()` and it might need the same or a different operation if the number is negative (for instance `floor()` and `(int)` cast gives the same result for positive numbers but not for negative ones). And it would just be even more confusing to have methods for all possible rounding ways of the results. It's way better and clear for other developers or the future you if this truncation/rounding is done in your own code.

Another point to consider is: is the integer-type a relevant constraint or is it actually arbitrary. In many cases application code would actually support float just fine and would then be able to produce a more precise result in the end. So before taking any arbitrary decision about putting `(int)` cast or something else everywhere, it might be a good occasion to re-check assertions and see if it wouldn't just work fine with `float`.

More explanations can be found on #2119

**Comment by sts-ryan-holton** [comment]
@kylekatarnls I'm not sure I'm clear, what I mean is this:

```php
$after->diffInSeconds($before, true) // automatically cast to int when true is passed
```

Presumably passing **true** as a second argument parameter is creating the same behaviour as that of Carbon v2. If so, can this auto-apply `(int)`. Presuming the without passing **true** and just leaving that out it returns a float, which is fair enough

**Comment by kylekatarnls** [comment]
The second parameter is already used, it's `$absolute`, which BTW I'm not a huge fan of, it's there for consistency with the native PHP method `DateTime::diff` but I also recommend not to use it and to instead use `abs()` on the result, it's way more clear to read.

`$absolute` is about signed vs. unsigned, so nothing to do with float vs. int.

Let's imagine we would add a third argument `$castToInteger` so you could do:
```php
$after->diffInSeconds($before, castToInteger: true)
// or:
$after->diffInSeconds($before, false, true)
```
What's the benefit? Why would you do that instead of simply do:
```php
(int) $after->diffInSeconds($before)
// or:
floor($after->diffInSeconds($before))
```

As an application developer I would strongly recommend the cast/floor option rather than delegating this trivial operation to a library.
