### ISSUE TITLE
Type error when calling canBeCreatedFromFormat with null date

### ISSUE THREAD

**Issue by naudelasticweb** [briannesbitt/Carbon#2996]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::canBeCreatedFromFormat(null, '!Y-n-j G:i:s.u');
```

Carbon version: 3.2.4

PHP version: 8.3.4

I expected to get:

```
false
```

But I actually get:

```
Carbon\Carbon::rawCreateFromFormat(): Argument #2 ($time) must be of type string, null given, called in /vendor/nesbot/carbon/src/Carbon/Traits/Comparison.php on line 845
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello.

I think the current behavior is fine.

You can simply do:
```php
$value = null;

$creatable = is_string($value) && Carbon::canBeCreatedFromFormat($value, '!Y-n-j G:i:s.u');
```

This way we don't need to do this check inside `canBeCreatedFromFormat` which will make it more efficients for places where the passed value is already ensured to be a string.

And in case where it's not, it can be more efficiently tested also, for instance if you know your value can only be `null` or `string` then you use `$value !== null` instead of `is_string` which is even better.

As a matter of comparison, you cannot pass `null` or any non-array value to the native PHP function `array_is_list`.

There is no strict standard about either this kind of method should accept `string`, `string|null` or `mixed`, but I think libraries should be tolerant to a certain point and not accept mixed/null value everywhere if it does not make sense. Your application side, you can predict statically that `null` will be a valid input to create a `Carbon` object (whatever the format is by the way). Checking that your input is a string is a trivial operation you should likely not delegate to a library tool and stay in control of that part. As `string` is the only type that actually make sense to use in `createFromFormat` it's better to filter out of your flow as early as possible.

**Comment by naudelasticweb** [comment]
Hi,

I already added the null check on my side.

But...

it is a valid point that you make but the only confusing part is that `canBeCreatedFromFormat` accepts `?string` instead of `string` which lets me assume that it will not throw a type error when passing a null value to it.

**Comment by kylekatarnls** [comment]
Arf, you're right, I incorrectly converted PHPDoc type to the strict type:
![image](https://github.com/briannesbitt/Carbon/assets/5966783/096de0f1-8264-4220-b1bd-7e0c1dc9aec6)

Now narrowing the type would be a BC, so I will just add the `null`-check and revisit on next major version.
