### ISSUE TITLE
Carbon createFromTimestampMs no default time zone if it is set in env variable of Laravel app

### ISSUE THREAD

**Issue by doraemonxxx** [briannesbitt/Carbon#3017]
Before commit https://github.com/briannesbitt/Carbon/commit/fe08985c28d24a339d3a419cfa5d596e11ccb034#diff-10f11ebb873c766d138778fa336054091dce401f3f4ffa79c1d36b8061366cf5 the
```php
Carbon::createFromTimestampMs()
```

is working fine without timeZone in the arguments. **Question** -> What was the reasoning behind this modification
Apologies for not following the usual format
```php
 public static function createFromTimestamp(float|int|string $timestamp, DateTimeZone|string|null $tz = null): static
    {
        $date = static::createFromTimestampUTC($timestamp);

        return $tz === null ? $date : $date->setTimezone($tz);
    }
```

In my code now, I always have to specify the time zone when using the createFromTimestampMs method.

**Comment by kylekatarnls** [comment]
Hello, as explained in #2966 and in the documentation, first section of [Migrate to Carbon 3](https://carbon.nesbot.com/docs/#api-carbon-3)

It was previously using `date_default_timezone_get()` as a fallback value, which is:
- not consistent with what happens when you do `new DateTime('@' . $timestamp)`
- not reliable (changing php.ini setting, hosting, etc. will modify the behavior of your app)
- can be modified globally by any code in your third party dependencies that could call `date_default_timezone_set()` to override it and mess up

We try to move the blackbox effect away (avoid behaviors driven by settings that the application/develop is maybe not aware of).

We want you to actually specify explictly: `Carbon::createFromTimestamp($timestamp, date_default_timezone_get())` is that's really what you want, making you intent of using the setting from php.ini clear and acknowledging you're aware of what it implies (that you understand all the way it can get modified globally on the system side or at any moment at runtime).

But we also actually encourage you to reconsider why you would ever need a default timezone being anything else than `UTC`.

Timezone is a thing that belongs to your users (to real humans reading a real clock), it's not something that the system needs, your server-side code does not need a global arbitrary setting for the timezone, it can use UTC which is universal rather than the name of the city and should be able to handle requests from anywhere in the world.

You may need to do a particular operation using timezone (to answer a user who is in this timezone for instance) but it should be scoped only to the objects needed for this operation (using `->setTimezone()` on thos particular dates), it has not reason then to change the default timezone setting.

So we actually suggest you use `Carbon::createFromTimestampMsUTC()`

An old essai on this topic I made, but it's still relevant IMO:
[Always Use UTC Dates And Times](https://kylekatarnls.medium.com/always-use-utc-dates-and-times-8a8200ca3164)
