### ISSUE TITLE
Misleading error message in `createFromFormat`

### ISSUE THREAD

**Issue by sebastianhelbig** [briannesbitt/Carbon#3066]
About `Carbon::createFromFormat($format, $time, …)`

The error message `'createFromFormat() will only accept string or integer for 1-letter format representing a numeric unit int next version'` indicates an error with the first parameter `$format` but it is actually thrown if the second parameter `$time` is not a string.

This commit introduced that: https://github.com/briannesbitt/Carbon/commit/9f64d55935107ad2ea6e0ae20c79d9745c870c60

**Comment by kylekatarnls** [comment]
Indeed there is a typo it's meant to be:
```php
createFromFormat() will only accept string or integer for 1-letter format representing a numeric unit in the next version
```

But the thing about format is correct, what is 1-letter is the format:
- when `$format` is a 1-letter format representing a numeric unit
  - => it accept either a string of 1 or more digits, or an integer
- when `$format` is anything else
  - => it accept only string (matching the format)

**Comment by kylekatarnls** [comment]
Typo fixed in 9fe157c

**Comment by kylekatarnls** [comment]
Feel free to suggest a better wording for this (either here or opening a merge request).

**Comment by sebastianhelbig** [comment]
@kylekatarnls We ran into this problem when using `createFromFormat('d-m-Y', null)` as it worked in previous versions. But the error message is only about $format. There is no indication that the second parameter $time is the problem here.

**Comment by kylekatarnls** [comment]
> message is only about $format

Actually the message is not about `$format`, it was meant to be about the format that `$time` needs to respect.

So I updated the error message to explicitly mention `$time`: 4a4b502

Also, please let me highly recommend to never pass `null`, `false` or whatever value there.

Basically you're strongly encouraged to follow the signature from [PHP DateTime doc itself](https://www.php.net/manual/en/datetimeimmutable.createfromformat.php) which is the same as our PHPDoc:
```php
@param string $format
@param string $time
```

It does not make actual sense to pass anything but `string` for `$time` Because a `$format` is used to represent how a date-time is represented as a string. The `format()` always returns a `string` even when the result only has 1 number/digit, so it's the good to do the same and pass only `string` for the reverse operation of `createFromFormat()`

I suggest the same best-practice when using `parse()` or the like.

**Comment by sebastianhelbig** [comment]
We now check the passed values before calling the function. However, it would be better to just throw an exception here and not raise an error.

**Comment by kylekatarnls** [comment]
It's not an error, it's a deprecation and it's still "working" (with silent cast) for the moment. So not to introduce a breaking change and let time for users to fix before next major version.

**Comment by kylekatarnls** [comment]
How you handle deprecation is part of your own application strategy, but I would suggest you don't make them blocking and instead log them somewhere aggregated in a way that you can address them according to their priority, for instance, I can tell you Carbon 4 is still far so it's nothing urgent.

But as it's deprecated for reason it's of course still better to fix sooner if you can.
