### ISSUE TITLE
Type Error with setUnit() function in Date.php file

### ISSUE THREAD

**Issue by JohnnyQ352** [briannesbitt/Carbon#3067]
Hello,

I encountered an issue with the following code:

$timeframe = $request->timeframe ?? 'Full_Year';
$year = Carbon::now()->format('Y');
Carbon::now()->month($timeframe)->format('F').' '.$year;

Carbon version: 3.7.0

PHP version: 8.3.10

I expected to get:      01

But I actually get:

TypeError: Carbon\Carbon::setUnit(): Argument #2 ($value) must be of type Carbon\Month|int|float|null, string given, called in /var/www/vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 2880

For your information: I added "string" under setUnit and it works. I am using it as a temporary fix unless I am doing something wrong and you guys let me know.
EG: 
public function setUnit(string $unit, Month|int|float|string|null $value = null): static{
.................  Your Code  ..................
}

Thanks!

**Comment by kylekatarnls** [comment]
Hello, which are exactly the strings that you would like to be supported? `Full_Year`? What else `$request->timeframe` could contain?

And then for those strings, what would it mean? For instance I don't get what behavior `->month('Full_Year')` should trigger.

**Comment by JohnnyQ352** [comment]
> Hello, which are exactly the strings that you would like to be supported? `Full_Year`? What else `$request->timeframe` could contain?
> 
> And then for those strings, what would it mean? For instance I don't get what behavior `->month('Full_Year')` should trigger.

Kyle, buddy. That was just a sample run. what seems to be happening is that when a number is going into the setUnit function say it is "01", it won't evaluate it because there is no string accepted for $value the function is like this: 
public function setUnit(string $unit, Month|int|float|null $value = null): static
AND it should be like this: 
public function setUnit(string $unit, Month|int|float|string|null $value = null): static

I added the "string" in the parameter so that it works on my end, but thought I let you know so you can either add it or change it.  In the 2.x.x versions it would evaluate it because the function was setup different, but when I updated my version I saw that little detail and decided to let you know. 

Now if you want to add a "string" parameter so we can say FULL_YEAR, FULL_MONTH so that it returns the 4-digit year of a date or the 2-digit month , that would be cool too.

Thanks.

Johnny

**Comment by kylekatarnls** [comment]
> AND it should be like this:
> public function setUnit(string $unit, Month|int|float|string|null $value = null): static

No it shouldn't. We could also not have type anywhere so it's all just `mixed` everywhere and we just hope that it will work as expected.

The problem is: "as expected" is not the same for everyone. That's the reason why it's that that "cool" to accept anything anywhere and why we try to increase the type-safety, not to decrease it.

If you have `string("01")` as an input, it actually means `int(1)`, so now the question is: why would it be the responsibility of the library to guess that, why not being explicit in you application:

```php
// Validate the string so you ensure what you pass can actually be a month number
if (!preg_match('/^(0?[1-9]|1[0-2])$/', $timeframe)) {
   throw new InvalidArgumentException("Expected a month number from 01 to 12, received: $timeframe");
}

// Cast it explicitly into an integer now that you know your value is safe
Carbon::now()->month((int) $timeframe)->format('F');
```

If we delegate the responsibility to Carbon library, it raises the question: what should we do if we get "February" string? Be smart, convert to 2? What if we get "febbraio", it means February in Italian so why not supporting it also? Then now what to do with invalid values "lorem ipsum"? Or string containing number but not between 1 and 12? Etc. If we just allow `string` with no check at all, we can just end up with silent broken results for all those cases which make things way less reliable; if we add all the relevant validation, we end up with potentially a lot of logic decreasing performance and when wanting to be smart we need to take opinionated decisions that would work for all the business case, that's why at some point, the business logic should stay where it belongs: in your own application code.

I recommend you do the cast explicitly and validate the input according to your own needs.

As a side note: if you want to open a new feature request at some point, please keep the code-section tags (` ` `php) and use a code snippet free from unknown value (a code chunk that anyone can just copy-paste and get the same result as you).

**Comment by JohnnyQ352** [comment]
No need to get offended my friend. I thought it should be that way due to the past version accepting string to integer conversion.  
 
It personally makes no difference to me as I find any work around to any situation. But I wanted to note this to you as PhP doesn't care when calculating.
 
Example: 
 
<?php

$strNumber = '01';
$intNumber = 1;
$intNumber2 = 3;
$strNumber2 = '33';
echo $strNumber + $intNumber;
echo ", ";
echo $strNumber2 * $intNumber2;
echo ", ";
echo $strNumber + $strNumber2;


 
Result: 2, 99, 34
 
That being a fact, I also noted this to you in case you did want to have the same flexible function as you did in version 2.0 of your tool, where it did not care if it was 
sent as character or number. This making your prior version more flexible with the function.
 
And no I do not believe you need to accept strings like "Febrero" or "February", but say if they send any numbers with quotes, it should work without any issues.  I actually noted that by just adding |string| in the parameter it handled it just find, due to the upper mentioned functionality of PhP.
 
Again, I never meant my post to offend you guys, as I believe you guys are doing a great thing creating this tool.
 
Final Note:  My values sometime come across as text instead of numeric as it makes formatting easier in the front end (HTML). True, I can change all my code to convert to INT before using the tool, but it was easier to change the tool to strip characters leaving only INT values as it use to do in prior version, without changing hundreds of thousands of lines of code that use it. That because my project has well over 2 million lines of code between Controllers, Middleware, Helpers and Blades, so this was just easier for me.
 
Thank you always.
 
 Johnny.
 
 
-----Original Message-----

**Comment by kylekatarnls** [comment]
And I did not get offended, there is a misinterpretation here I think. I explained why we changed the types of this and methods in the version 3. I'm fully aware it was silently casting string to int in previous version and mathematical operators triggers such implicit cast. Those kind of behaviors are ambiguous and error-prone (because it opens to any strings, not just strings representing numbers). You can call it flexible, many call it dangerous and want to avoid such patterns. It's called type-safety.

If you don't see the interest of this, I can understand, and you may also consider staying on Carbon v2.
