### ISSUE TITLE
firstOfMonth gives the next month

### ISSUE THREAD

**Issue by cognitus** [briannesbitt/Carbon#3068]
Hello,

I encountered an issue with the following code:

```php

Carbon::createFromFormat('m-Y', '04-2024')->firstOfMonth()

```

Carbon version: * 3.8.0

PHP version: 8.3.10

I expected to get:

```
    date: 2024-04-01 00:00:00.0 UTC (+00:00)
```

But I actually get:

```
 Carbon\Carbon @1714521600 {#7653
    date: 2024-05-01 00:00:00.0 UTC (+00:00),
  }
```
Btw, this happened yesterday 31-08-2024 on my servers, Today I get the expected result `date: 2024-04-01 00:00:00.0 UTC (+00:00)`. For testing I changed the system date.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

`createFromFormat` is directly inherited from `DateTime`, see:
https://www.php.net/manual/en/datetimeimmutable.createfromformat.php

![image](https://github.com/user-attachments/assets/49d149c5-81ab-404b-be56-9fd6cdf01628)

```php
Carbon::createFromFormat('!m-Y', '04-2024')
```

And you don't need `->firstOfMonth()` since `!` does it already.

Thanks.
