### ISSUE TITLE
Month abbreviation issue for fr_BE

### ISSUE THREAD

**Issue by c-Rolland** [briannesbitt/Carbon#3109]
Hello,
I believe that the month abbreviations 'fr_BE' is incorrect.

Some references : 

- https://man.archlinux.org/man/DateTime::Locale::fr_BE.3pm.en
- http://www.polarhome.com/service/man/?qf=DateTime%3A%3ALocale%3A%3Afr_BE&tf=2&of=Oracle&sf=3pm
- https://carta.tech/man-pages/man3/DateTime::Locale::fr_BE.3pm.html
- https://helpmanual.io/man3/DateTime::Locale::fr_BE-pm/
- https://www.localeplanet.com/icu/fr-BE/index.html

I encountered an issue with the following code:

```php
echo Carbon::parse(new \DateTime('2024-08-30'))->locale('fr_BE')->isoFormat('ll')
```

Carbon version: "nesbot/carbon": "^3.8.1",

PHP version: 8.1

I expected to get:

```
30 août 2024
```

But I actually get:

```
30 aoû 2024
```

Impacted file : https://github.com/briannesbitt/Carbon/blob/3.x/src/Carbon/Lang/fr_BE.php

Thanks!

**Comment by kylekatarnls** [comment]
Bonjour 👋 

`fr_BE` was initially built from glibc (because before embedding localizations, Carbon was relying on `strftime`, so it was the closest match)

And it's still using `aoû` at the moment
https://github.com/bminor/glibc/blob/7f045c0b48633b198b42bebdff0024d7cfab3901/localedata/locales/fr_BE#L103

For the record we have also this exception for Luxembourg:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/fr_LU.php

Those 2 are the only ones with custom month lists. Sounds to be something regional but also it's there in glibc for more than 24 years.

ICU is a more reliable and updated source for translation so I would be fine to make `fr_BE.php` and `fr_LU.php` simply aliasing `fr`:
```php
return require __DIR__.'/fr.php';
```

Feel free to propose a pull-request if you wish. 🙏

**Comment by c-Rolland** [comment]
Thanks for your reactivity @kylekatarnls

**Comment by kylekatarnls** [comment]
It can be tested using `composer require nesbot/carbon:dev-master` for now.

**Comment by c-Rolland** [comment]
@kylekatarnls Unit tests are missing for these mapping files, it is because is hard to test or s?
