### ISSUE TITLE
PHP 8.4 on v2?

### ISSUE THREAD

**Issue by jasonvarga** [briannesbitt/Carbon#3114]
Hello, we author a package that uses Carbon v2 and cannot upgrade to v3 for a while, but we want to support PHP 8.4.

Everything seems to work fine except for all the deprecation notices.

Would you be open to make v2 support PHP 8.4? (If it's even possible.) We'd be happy to contribute it ourselves.

Thought I'd ask before spending time on it. Thanks!

**Comment by kylekatarnls** [comment]
Hello, Carbon v2 will continue to receive security fixes for a while, but we won't work on providing any new feature or support for newest PHP versions.

If we receive a pull-request to provide such support and that it does not cause any regression, we'll consider merging it and tagging a new v2 with it. But we don't plan to work ourselves on this.

Why we think it's not necessary:
- Because if you can stay with an old version of Carbon, you can probably also stay with and old version of PHP (or at least you don't need the last-week newest release)
- On the opposite if you are willing to be PHP 8.4 compatible, then you should also really consider being Carbon v3 compatible.
- As long as it's deprecation, in practice, it's not incompatible, you can mute them or at least make them unblocking and just log them; and they are actually meant for that: meant to warn you about future incompatibilities, and it's rather expected to see deprecation when using older versions of libraries, but it's still not preventing you to use it. Concretely Carbon v2 is supporting PHP 8.4.

So despite there are probably better options, I'm not against reviewing work to solve PHP 8.4 deprecations on v2.

**Comment by jasonvarga** [comment]
Thank you.

**Comment by kylekatarnls** [comment]
Hello thanks to @thecaliskan work (https://github.com/CarbonPHP/carbon/pull/13), next 2.x patch should be compatible with PHP 8.4.

You can test it with `composer require nesbot/carbon:2.x-dev`

**Comment by kylekatarnls** [comment]
Should happen mid-february.

**Comment by kylekatarnls** [comment]
Released via [2.73.0](https://github.com/briannesbitt/Carbon/releases/tag/2.73.0)
