### ISSUE TITLE
Deprecate implicitly nullable parameter types

### ISSUE THREAD

**Issue by yuzshs** [briannesbitt/Carbon#3128]
Description
Related to https://wiki.php.net/rfc/deprecate-implicitly-nullable-types

Right now, the deprecation message looks like:

```
admin_redirect(): Implicitly marking parameter $request as nullable is deprecated, the explicit nullable type must be used instead
```

```
Return type of Carbon\Traits\Date::createFromTimestamp($timestamp, $tz = null) should either be compatible with DateTime::createFromTimestamp(int|float $timestamp): static, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

#### PHP Version
```
PHP 8.4
```

**Comment by kylekatarnls** [comment]
What is your Carbon version?

**Comment by kylekatarnls** [comment]
This method has strong types in 3.8.4:
https://github.com/briannesbitt/Carbon/blob/3.8.4/src/Carbon/Traits/Timestamp.php#L29

And this is the only branch that receives updates to support PHP 8.4 since it's not that relevant to upgrade PHP version to the latest while sticking to library versions several years old.

If you cannot upgrade, you should just consider muting deprecations all together.
