### ISSUE TITLE
Is there timezone support for $carbonInstance->diffForHumans()

### ISSUE THREAD

**Issue by jofrysutanto** [briannesbitt/Carbon#336]
Perhaps I missed it, but is it possible to generate difference for human, in specific timezone?

> When comparing a value in the past to default now:
>  * 1 hour ago
>  * 5 months ago

It's helpful to have the same result format (`ago`, `from now`), but the ability to specify timezone.

**Comment by briannesbitt** [comment]
Not built-in now.  Since now and now in a different timezone aren't really different at UTC time.  You could easily adjust the time based on the tz differences though.

```php
$here = Carbon::now();
$there = Carbon::now('America/Vancouver');

echo $here . PHP_EOL;
echo $there . PHP_EOL;

echo $here->diffForHumans($there) . PHP_EOL;
$there->addSeconds($here->offset - $there->offset);
echo $here->diffForHumans($there) . PHP_EOL;
```

The above will give 3 hours which is the difference between me and Vancouver time in Canada.

```
2015-04-01 21:11:14
2015-04-01 18:11:14
1 second before
3 hours before
```

**Comment by jofrysutanto** [comment]
I agree that it'll be very easy to adjust the time based on the tz differences, however the main reason I think it's good to have timezone support for default ```->diffForhumans()``` is the resulting string format.

```
$here = Carbon::now();

echo $here->diffForHumans() . PHP_EOL;
echo $here->diffForHumans($here) . PHP_EOL;
```
The above will give me
```
1 second before
1 second ago
```
The difference between `before` and `ago` give very different meanings, and I can't get the former result since I am forced to use ```$here->diffForHumans($adjustedNowWithTzOffset)```

Does that makes sense?

**Comment by briannesbitt** [comment]
Not really.   2015-04-01 21:11:14 EST === 2015-04-01 18:11:14 PST

Timezones don't represent a time difference.
It feels like you are trying to get the difference between timezones instead of the actual time.

You can do `$here->diffForHumans($adjustedNowWithTzOffset)` or if you want the opposite either do `$adjustedNowWithTzOffset->diffForHumans($here)` or use `subSeconds()` instead of addSeconds when adjusting the time with the tz offsets.

Also just a note that the function always returns at least 1 second and never 0 seconds even if the values are the same.

**Comment by jofrysutanto** [comment]
I guess I might've missed the marks here still. To quote your original example:

```
$here = Carbon::now();
$there = Carbon::now('America/Vancouver');

echo $here . PHP_EOL;
echo $there . PHP_EOL;

echo $here->diffForHumans($there) . PHP_EOL;
$there->addSeconds($here->offset - $there->offset);
echo $here->diffForHumans($there) . PHP_EOL;

// --- Results:

2015-04-01 21:11:14
2015-04-01 18:11:14
1 second before
3 hours before
```

How should one, in best practice, using the same code but achieve these results:
```
2015-04-01 21:11:14
2015-04-01 18:11:14
1 second ago // Notice it says 'ago' instead of 'before'
3 hours ago // Notice it says 'ago' instead of 'before'
```

Again, I'm sorry if this doesn't make much sense.

**Comment by briannesbitt** [comment]
`ago` is only used when comparing against now.... ie no parameter.  Just adjust an instance by the difference in offsets and diff that against now.

```
$here = Carbon::now();
$there = Carbon::now('America/Vancouver');

echo $here . PHP_EOL;
echo $there . PHP_EOL;

$here->subSeconds($here->offset - $there->offset);
echo $here->diffForHumans() . PHP_EOL;
```

**Comment by jofrysutanto** [comment]
Yeah, which is my main point in this feature request; whether or not it's possible to use `ago` format in conjunction with setting timezone in one go. I guess that wouldn't matter if we store the UTC time in our database which we unfortunately didn't. Hence we have to create our own helper method to adjust the timezone before calling ```->diffForHumans()``` like what you showed.
Anyways, I guess this means no; closing this one down.

**Comment by Surt** [comment]
I would really love to see the ``` ->diffForHumans() ``` with timezone support.
Actually I'm saving UTC in database and showing it on front with ```->formatLocalized(..)``` wich translates the dateTime to the timezone of the user. It does not work with ``` ->diffForHumans() ``` wich shows me the difference against the local timezone (it says two hours from now... since my timezone is +2)
