### ISSUE TITLE
DateTime::__construct(): Failed to parse time string

### ISSUE THREAD

**Issue by HMAZonderland** [briannesbitt/Carbon#349]
I got this error 
```cmd
Exception: DateTime::__construct(): Failed to parse time string (1429610783) at position 8 (8): Unexpected character

/var/www/project/vendor/nesbot/carbon/src/Carbon/Carbon.php:195
/var/www/project/vendor/nesbot/carbon/src/Carbon/Carbon.php:223
/var/www/project/test/Persistence/ProductPersistenceTest.php:92
```
when trying to set this timestamp using the following code:

```php
// create a timestamp for 5 minutes ago
$timestamp = \Carbon\Carbon::parse(time())->subMinute(10);
```

**Comment by HMAZonderland** [comment]
Removing `time()` fixes the issue.
```php
// create a timestamp for 5 minutes ago
$timestamp = \Carbon\Carbon::parse()->subMinute(10);
```

**Comment by briannesbitt** [comment]
You might as well use `Carbon::now()` at that point if you are not trying to parse a date input.

**Comment by arborrow** [comment]
I'm trying to use parse on some input from the route (Laravel project). What is the best way to validate that the data provided is actually something parsable? Otherwise, with bad input the user will get DateTime::__construct(): Failed to parse time string when the parse tries to run. I can handle no input without a problem but if something is provided is there a way to validate that it is parsable? Peace - Anthony
