### ISSUE TITLE
Business days

### ISSUE THREAD

**Issue by brunowego** [briannesbitt/Carbon#368]
Will be great add support for diff business days.

**Comment by Adapik** [comment]
Buisiness days are different in different countries. So it's unable to apply

**Comment by brunowego** [comment]
I understood, but what you think about week days?

**Comment by redknitin** [comment]
@brunowego I just wanted to share some information about week days. Week days differ between countries too - a weekend here in Dubai (and most parts of the Middle East) includes a Friday and a Saturday. Also, in Dubai, some industries have a six-day work week instead of a five-day work week. If it does not sound complex enough, Netherlands has a four-day work week in some organizations and a few U.S. firms adopted the idea too! :-)

**Comment by brunowego** [comment]
Ok, thanks @redknitin .
