### ISSUE TITLE
createFromTimeStamp can't handle timestamp in microseconds

### ISSUE THREAD

**Issue by reedgz** [briannesbitt/Carbon#384]
I have timestamps from different APIs; some are in seconds and some are in microseconds.

PHP DateTime does not support it, so I guess Carbon just inherited the same behavior.  However, it would be very nice of Carbon can take timestamp in both seconds and microseconds.

```
// without microseconds
\Carbon\Carbon::createFromTimeStamp('1433193303')->format('Y M j g:i:s a')
// return: 2015 Jun 1 5:15:03 pm  

// with microseconds
\Carbon\Carbon::createFromTimeStamp('1433193303000')->format('Y M j g:i:s a')
// return: 1927 Dec 28 4:28:56 am
```

**Comment by Sverri** [comment]
Timestamps are always in seconds in PHP. All you have to do, to turn microseconds into seconds, is divide the microseconds by `1000`:

    \Carbon\Carbon::createFromTimeStamp('1433193303000' / 1000)->format('Y M j g:i:s a');

Since both seconds and microseconds are numbers there is no way to tell them apart. Sure, you *could* look at how big the numbers are, and infer from that, but then what if someone wants to get a date that is far, far into the future? It just does not work.

The method could take a third argument, `$isMicroseconds`... but it is not really worth it to complicate the code when it is already trivially simple to turn microseconds into seconds.

**Comment by reedgz** [comment]
Okay, I am already using a helper function to sanitize incoming timestamps anyway.
