### ISSUE TITLE
issues with HHVM

### ISSUE THREAD

**Issue by MaxRink** [briannesbitt/Carbon#427]
https://travis-ci.org/briannesbitt/Carbon
https://github.com/briannesbitt/Carbon/blob/master/tests/DiffTest.php

**Comment by nicholas-eden** [comment]
There is a bug with the magic setter and getter on the DateInterval which seems to be fixed in a later version:
https://github.com/facebook/hhvm/issues/2952

Having the Carbon classes call parent::__set and __get seems to solve the problem.

The DatePeriod had a bug as well:
https://github.com/facebook/hhvm/issues/3947

Still trying to work this out.

**Comment by inctor** [comment]
+1 for this, just encountered it, and almost went mental trying to figure out what was going on.

Any work-arounds for this, that does not include altering vendor-files?

**Comment by nicholas-eden** [comment]
I have a pull request that puts in a work around for all but one hhvm bug. If your hhvm version is 3.8 or higher then they ask are fixed.

**Comment by briannesbitt** [comment]
See comments in #541
