### ISSUE TITLE
day() moves whole date forward - expected behaviour?

### ISSUE THREAD

**Issue by scrwdnet** [briannesbitt/Carbon#762]
I came across this issue when setting the year, month and day manually using the set methods:

```
(new \Carbon\Carbon())->year(2016)->month(11)->day(1);

//Result
2016-12-01 10:21:26
``` 

```
(new \Carbon\Carbon())->day(1)->month(11)->year(2016);

//Result
2016-11-01 10:21:26
``` 

If you set the day as the last method it bumps the month forward to rather than just setting the day to X. Is this the expected behaviour? It stung me a couple of times before I realised swapping the methods around fixed it.

**Comment by briannesbitt** [comment]
Lucky you since today is Aug 31.  Setting the month before the day means you set the date to 2016-11-31.  This date doesn't exist so it rolls over to 2016-12-01.  Then you set the day to 1 (which does nothing since it rolled over already).

The 2nd version does 2016-08-31 => 2016-08-01 => 2016-11-01 so you end up with what you expected.

**Comment by scrwdnet** [comment]
****facepalm**** well that makes sense, didn't realise that setting the month would roll you forward but it does make sense!

Thanks for the pointers and keep up the good work with Carbon, it's a great library!
