### ISSUE TITLE
Can DiffForHuman show 2 hours, 12 minutes, 5 second ago ?

### ISSUE THREAD

**Issue by Hujjat** [briannesbitt/Carbon#829]
Hi,

By default, when we apply the diffForHuman to any date, It shows only the second or minutes or hours ago. Is there any way to format it to show all there of them. I mean instead of 1 hours ago, it should show 1 hour, 12 minutes, 5 seconds ago.

Thank's :)

**Comment by Glavic** [comment]
Method `diffForHumans()` now supports that. See last argument, called `$parts`, where you can set how many "parts" will be shown.

https://github.com/briannesbitt/Carbon/blob/9545b4c962713b63c8877c628f71e8f2f816648e/src/Carbon/Carbon.php#L2831

TY and BR

**Comment by Hujjat** [comment]
I needed it in 2016. Thanks anyway. 👍

**Comment by Sly-Ripper** [comment]
No option for a separator? "5 months 3 weeks 3 days" needs commas

**Comment by kylekatarnls** [comment]
No because commas are not universal. `diffForHumans` is translated in 137 languages in the last version and for many of them `,` does not mean anything. So such feature would need first to get translation in each language for `:item, :item` and optionally for `:list and :last-item`.

**Comment by kylekatarnls** [comment]
Yes, it can be easy to implement. I suggest you open an issue dedicated to that because the description of the issue was about returning multiple parts instead of a single part and the answer is yes since Carbon v1.23 (February 2018) and no before. So this issue is closed.

Returning comas would be inconsistent with i18n support as explained (unless having proper translations for it) and returning array (via an option or via an other method) is an other subject in my opinion. I would be OK to plan it for a future release (2.1 or 2.2 probably).  Also feel free to submit a pull-request for that.

Note: we won't implement it ourselves for a 1.x release as Carbon 2 is our priority. But if we receive a PR on the version-1.next branch ready to be merged, then we'll take it.

**Comment by imbrish** [comment]
From my experience ":list and :last" approach for translations worked well, but I worked with no more than a handful of languages. Which locales do not use comma? Chinese etc comes to mind, but maybe there are others. Anyway I think I've seen some localization file in Carbon which used closures for certain keys, maybe that would work here too?
