### ISSUE TITLE
Diff months trouble

### ISSUE THREAD

**Issue by xakzona** [briannesbitt/Carbon#872]
Sorry has not found solution from issues.
I sub 11 months from carbon:
$d = Carbon::parse('2017-01-30');
$diff = $d->subMonth(11)->diff($d);
`$diff = [
y = 0
m = 10
d = 29
h = 0
i = 0
s = 0
]`
Why it is not 11 months? I have tried to use absolute param like this, no success:
$diff = $d->subMonth(11)->diff($d, true);

**Comment by willrowe** [comment]
`Carbon::parse('2017-01-30')->subMonth(11)` will set the date to `2016-03-01` (assuming that month overflow is set to its default value of `true`). This is because February had 29 days in 2016, so in order to match `2017-01-30`, day 30 would be technically be March 1st.

When the diff is calculated it will determine that it is one day off from being 11 months apart, thus a difference of 10 months and 29 days.

Since there is never a 30th day in February (and in most years, no 29th day either), you won't be able to get a diff of exactly 11 months when comparing to a date in another month that is after the 28th. This is also the case when you set Carbon to not use month overflow (`Carbon\Carbon::useMonthsOverflow(false)`). It will attempt to set the date to the last day of the month, which in your example is `2016-02-29`. This is still not the 30th of the month, so the diff will end up being 11 months and 1 day.
