### ISSUE TITLE
ISO8601 Support for weekdays

### ISSUE THREAD

**Issue by nikolaynesov** [briannesbitt/Carbon#905]
According to ISO8601:

`[D] is the weekday number, from 1 through 7, beginning with Monday and ending with Sunday.`
https://en.wikipedia.org/wiki/ISO_8601

while Carbon still has `Carbon::SUNDAY` as 0. 
Is there any way to enable ISO_8601 support or any plans to introduce it?

**Comment by hpkns** [comment]
It’s a major annoyance for anyone living outside Northern America, and it can be fixed with a simple line of code.

Adding `'isoDayOfWeek' => 'N'` at line 666 (it can’t be an accident!) would work just fine!

In the meantime you can use this workaround (which I admit is not as convenient as the fluent getters): `$date->format('N')`.
